QUESTIONS = [
    {
        "slug": "docker-image-layers-caching",
        "question": "How does Docker layer caching work, and how does instruction ordering in a Dockerfile affect build speed?",
        "difficulty": "EASY",
        "tldr": "Each Dockerfile instruction creates a cached layer; Docker reuses cached layers until the first change, then rebuilds everything after it. Order instructions from least- to most-frequently changing to maximize cache hits.",
        "explanation": "A Docker image is a stack of read-only layers, one per build instruction. During a build Docker checks whether an instruction and its inputs are unchanged; if so it reuses the cached layer. Once any layer's input changes, the cache is invalidated for that layer and every layer after it, so placing volatile steps (copying source) before stable steps (installing deps) destroys cache reuse.",
        "code_examples": [
            {"language": "dockerfile", "label": "Cache-friendly ordering",
             "code": "# Good: deps installed first; code changes don't bust the npm cache layer\nFROM node:20-slim\nCOPY package.json package-lock.json ./\nRUN npm ci\nCOPY . ."},
        ],
        "tags": ["images", "caching"],
        "gotchas": ["Changing a layer invalidates the cache for all subsequent layers, not just that one.", "COPY/ADD cache is keyed on file checksums, so editing any copied file busts the layer even if the build command is identical."],
        "follow_ups": ["How would you keep dependency caching working when the lockfile changes only occasionally?", "What is BuildKit and how does its cache mounting differ from classic layer caching?"],
    },
    {
        "slug": "docker-multi-stage-builds",
        "question": "What are multi-stage builds and what problem do they solve?",
        "difficulty": "MEDIUM",
        "tldr": "Multi-stage builds use multiple FROM statements so you can compile/build in a heavy stage and copy only the final artifacts into a lean runtime stage, drastically shrinking the final image.",
        "explanation": "A multi-stage Dockerfile defines several stages, each starting with its own FROM. Earlier stages can contain compilers, build tools, and dev dependencies, while a later stage copies just the produced artifacts via COPY --from. The intermediate stages are discarded, so build-time tooling never ships in the final image, reducing size and attack surface.",
        "code_examples": [
            {"language": "dockerfile", "label": "Go build with distroless runtime",
             "code": "FROM golang:1.22 AS build\nWORKDIR /src\nCOPY . .\nRUN CGO_ENABLED=0 go build -o /app ./cmd/server\n\nFROM gcr.io/distroless/static\nCOPY --from=build /app /app\nENTRYPOINT [\"/app\"]"},
        ],
        "tags": ["multi-stage", "images"],
        "gotchas": ["Forgetting COPY --from and instead rebuilding in the final stage defeats the purpose.", "Naming stages (AS build) is safer than referencing them by numeric index, which shifts if you reorder stages."],
        "follow_ups": ["How can you target and build only a specific stage with --target?", "How do you share a common base stage across multiple final images?"],
    },
    {
        "slug": "docker-cmd-vs-entrypoint",
        "question": "What is the difference between CMD and ENTRYPOINT, and how do they interact?",
        "difficulty": "MEDIUM",
        "tldr": "ENTRYPOINT defines the fixed executable that always runs; CMD provides default arguments (or a default command) that are easy to override at docker run. With both in exec form, CMD becomes the default args appended to ENTRYPOINT.",
        "explanation": "ENTRYPOINT configures the container to run as a specific executable, and arguments passed to docker run are appended to it. CMD sets default arguments that the user can override simply by passing a new command. Using ENTRYPOINT for the binary plus CMD for default flags gives a clean CLI-like UX where the container has a fixed purpose but tunable defaults.",
        "code_examples": [
            {"language": "dockerfile", "label": "ENTRYPOINT + CMD interaction",
             "code": "FROM alpine\nENTRYPOINT [\"ping\"]\nCMD [\"localhost\"]\n# docker run img            -> ping localhost\n# docker run img 8.8.8.8    -> ping 8.8.8.8 (CMD overridden)"},
        ],
        "tags": ["dockerfile", "runtime"],
        "gotchas": ["Shell form (ENTRYPOINT cmd) wraps the process in /bin/sh -c, which breaks signal forwarding and ignores CMD.", "Passing args to docker run replaces CMD entirely but only appends to ENTRYPOINT."],
        "follow_ups": ["How do you override ENTRYPOINT at runtime?", "Why is exec form preferred over shell form for PID 1 signal handling?"],
    },
    {
        "slug": "docker-run-vs-cmd",
        "question": "What is the difference between the RUN and CMD instructions?",
        "difficulty": "EASY",
        "tldr": "RUN executes a command at build time and commits the result as a new image layer; CMD specifies the default command executed at container start time and does not run during the build.",
        "explanation": "RUN is for setting up the image: installing packages, compiling code, creating files. Each RUN produces a new layer baked into the image. CMD, by contrast, runs nothing at build time; it only declares what process the container launches when started, and there can be only one effective CMD.",
        "code_examples": [
            {"language": "dockerfile", "label": "RUN (build time) vs CMD (run time)",
             "code": "FROM ubuntu:22.04\nRUN apt-get update && apt-get install -y curl   # runs during build\nCMD [\"curl\", \"--version\"]                         # runs when container starts"},
        ],
        "tags": ["dockerfile", "runtime"],
        "gotchas": ["Multiple CMD instructions are allowed syntactically but only the last one takes effect.", "Using RUN for something that should happen at startup (e.g. starting a server) won't work because the image build finishes and exits."],
        "follow_ups": ["When would you use ENTRYPOINT instead of CMD?", "Why should you chain apt-get update and install in a single RUN?"],
    },
    {
        "slug": "docker-volumes-vs-bind-mounts",
        "question": "What is the difference between named volumes and bind mounts, and when would you use each?",
        "difficulty": "MEDIUM",
        "tldr": "Named volumes are managed by Docker in its own storage area and are ideal for persistent app data; bind mounts map a specific host path into the container and are great for local development where you want live source code on the host.",
        "explanation": "Named volumes are created and managed by Docker, are portable across hosts via volume drivers, and survive container removal, making them the recommended way to persist databases and stateful data. Bind mounts attach an exact host directory into the container, giving you direct host-filesystem access but coupling the container to the host's layout. Bind mounts shine in development for hot-reloading source code, while volumes are preferred for production state.",
        "code_examples": [
            {"language": "bash", "label": "Named volume vs bind mount",
             "code": "# Named volume (Docker-managed)\ndocker volume create appdata\ndocker run -v appdata:/var/lib/postgresql/data postgres\n\n# Bind mount (host path)\ndocker run -v \"$(pwd)/src:/app/src\" node:20"},
        ],
        "tags": ["volumes", "storage"],
        "gotchas": ["Bind-mounting over a directory that already has image content hides the image's files behind the host's contents.", "Named volumes auto-initialize with the image's existing files on first use; bind mounts never do."],
        "follow_ups": ["How do tmpfs mounts differ from volumes and bind mounts?", "How would you back up and restore a named volume?"],
    },
    {
        "slug": "docker-networking-port-mapping",
        "question": "How does container networking and port mapping work in Docker?",
        "difficulty": "MEDIUM",
        "tldr": "Containers on a user-defined bridge network can reach each other by container name via Docker's embedded DNS. To reach a container from the host, you publish a container port to a host port with -p host:container.",
        "explanation": "By default containers join the bridge network and get their own internal IP. On a user-defined network, Docker provides automatic service discovery so containers resolve each other by name. Ports are only reachable from outside the host if you explicitly publish them with -p or EXPOSE+publish, mapping a host port to the container's listening port.",
        "code_examples": [
            {"language": "bash", "label": "User-defined network + port publishing",
             "code": "docker network create appnet\ndocker run -d --name db --network appnet postgres\ndocker run -d --name api --network appnet myapi   # api connects to host \"db\"\n\n# Publish container port 8080 to host port 80\ndocker run -p 80:8080 myapi"},
        ],
        "tags": ["networking", "ports"],
        "gotchas": ["On the default bridge, name-based DNS resolution does NOT work; you need a user-defined network.", "-p host:container order matters; swapping them silently binds the wrong port."],
        "follow_ups": ["What is the difference between bridge, host, and none network modes?", "How does container-to-container communication differ from host-to-container?"],
    },
    {
        "slug": "docker-compose-basics",
        "question": "What is Docker Compose and what problem does it solve?",
        "difficulty": "EASY",
        "tldr": "Docker Compose lets you define and run multi-container applications declaratively in a single YAML file, so you can spin up an entire stack (app, db, cache) with one docker compose up command.",
        "explanation": "Compose describes services, networks, and volumes in a docker-compose.yml file, replacing long chains of manual docker run commands. It automatically creates a shared network so services can reach each other by service name, and manages startup, environment, and dependencies. This makes local environments reproducible and easy to share.",
        "code_examples": [
            {"language": "yaml", "label": "Minimal multi-service docker-compose.yml",
             "code": "services:\n  web:\n    build: .\n    ports:\n      - \"8080:8080\"\n    depends_on:\n      - db\n  db:\n    image: postgres:16\n    environment:\n      POSTGRES_PASSWORD: secret\n    volumes:\n      - dbdata:/var/lib/postgresql/data\nvolumes:\n  dbdata:"},
        ],
        "tags": ["compose", "orchestration"],
        "gotchas": ["depends_on only waits for the container to start, not for the service to be ready; use healthchecks with condition: service_healthy.", "Service names become DNS hostnames, so connect to 'db' not 'localhost' from another service."],
        "follow_ups": ["How do you scale a service to multiple replicas with Compose?", "How do override files (docker-compose.override.yml) work for dev vs prod?"],
    },
    {
        "slug": "docker-env-vars-secrets",
        "question": "How should you handle environment variables and secrets in Docker images and containers?",
        "difficulty": "MEDIUM",
        "tldr": "Use ENV for non-sensitive config and inject runtime config via -e or env files; never bake secrets into image layers. Use Docker secrets, build secrets (--mount=type=secret), or an external secrets manager for sensitive values.",
        "explanation": "ENV values and ARG build args are stored in image metadata and layer history, so any secret put there is recoverable by anyone with the image. Sensitive values should be supplied at runtime (environment variables, mounted files) or via BuildKit secret mounts that never persist in layers. In orchestrators, dedicated secret stores (Docker/Swarm secrets, Kubernetes Secrets, Vault) keep credentials out of images and logs.",
        "code_examples": [
            {"language": "dockerfile", "label": "BuildKit secret mount",
             "code": "# syntax=docker/dockerfile:1\nFROM alpine\nRUN --mount=type=secret,id=npm_token \\\n    NPM_TOKEN=$(cat /run/secrets/npm_token) npm ci"},
        ],
        "tags": ["secrets", "config"],
        "gotchas": ["ARG and ENV values are visible in docker history and image inspect — never use them for passwords.", "An env var set with ENV persists into the running container and child processes, which can leak via logs or crash dumps."],
        "follow_ups": ["How do Docker Swarm secrets differ from Kubernetes Secrets?", "Why is a base64-encoded Kubernetes Secret not actually encrypted?"],
    },
    {
        "slug": "docker-dockerignore",
        "question": "What is a .dockerignore file and why is it important?",
        "difficulty": "EASY",
        "tldr": "A .dockerignore file excludes files and directories from the build context sent to the Docker daemon, speeding up builds, shrinking images, and preventing secrets or junk (like .git or node_modules) from leaking in.",
        "explanation": "When you run a build, Docker sends the entire build context to the daemon; a large context (node_modules, .git, build artifacts) slows builds and can be accidentally COPY'd into the image. .dockerignore uses gitignore-style patterns to keep those out. It also reduces the risk of copying credentials (.env, keys) into image layers.",
        "code_examples": [
            {"language": "bash", "label": "Typical .dockerignore",
             "code": "# .dockerignore\n.git\nnode_modules\n*.log\n.env\ndist\nDockerfile\nREADME.md"},
        ],
        "tags": ["build-context", "images"],
        "gotchas": ["Without .dockerignore, COPY . . can pull in secrets like .env or local credentials.", "A huge build context (e.g. an un-ignored .git) is uploaded to the daemon on every build, slowing things even when cached."],
        "follow_ups": ["How do .dockerignore negation patterns (!) work?", "Why doesn't .dockerignore affect bind mounts at runtime?"],
    },
    {
        "slug": "docker-image-size-optimization",
        "question": "What techniques reduce Docker image size?",
        "difficulty": "MEDIUM",
        "tldr": "Use small base images (alpine/slim/distroless), multi-stage builds, combine and clean up in single RUN layers, leverage .dockerignore, and avoid installing unnecessary packages or leaving caches behind.",
        "explanation": "Image size is driven by base image choice and what each layer adds. Multi-stage builds discard build tooling, while consolidating commands and cleaning package caches in the same RUN avoids bloating layers. Removing dev dependencies, avoiding unnecessary tools, and choosing a minimal base together can cut images from hundreds of MB to tens of MB.",
        "code_examples": [
            {"language": "dockerfile", "label": "Single-layer install + cleanup",
             "code": "FROM debian:12-slim\n# Clean apt cache in the SAME layer or it stays in history\nRUN apt-get update \\\n && apt-get install -y --no-install-recommends ca-certificates \\\n && rm -rf /var/lib/apt/lists/*"},
        ],
        "tags": ["optimization", "images"],
        "gotchas": ["Cleaning up in a later RUN doesn't shrink the image — the deleted files still live in the earlier layer.", "Alpine's musl libc can break glibc-dependent binaries, sometimes negating its size benefit."],
        "follow_ups": ["How would you analyze which layers contribute most to image size?", "What are the tradeoffs of distroless images for debugging?"],
    },
    {
        "slug": "docker-copy-vs-add",
        "question": "What is the difference between COPY and ADD, and which should you prefer?",
        "difficulty": "EASY",
        "tldr": "COPY simply copies local files/directories into the image; ADD does that plus auto-extracts local tar archives and can fetch remote URLs. Prefer COPY for clarity and use ADD only when you specifically need its extra behaviors.",
        "explanation": "Both instructions move files into the image, but ADD has 'magic' behaviors: it transparently unpacks recognized tar files copied from the build context and can download from URLs. These implicit behaviors make builds harder to reason about, so the best practice is to use COPY by default and reserve ADD for the rare cases where auto-extraction is genuinely wanted.",
        "code_examples": [
            {"language": "dockerfile", "label": "COPY vs ADD behaviors",
             "code": "# Prefer COPY for plain file copies\nCOPY app.jar /opt/app/app.jar\n\n# ADD auto-extracts a local tar into /opt\nADD release.tar.gz /opt/"},
        ],
        "tags": ["dockerfile", "images"],
        "gotchas": ["ADD silently extracts local tar archives, which can surprise you if you meant to copy the archive as-is.", "ADD from a URL doesn't verify checksums and can't use the build cache well; prefer RUN curl with verification."],
        "follow_ups": ["When is ADD's tar auto-extraction actually useful?", "How does COPY --from interact with multi-stage builds?"],
    },
    {
        "slug": "docker-container-vs-image-vs-registry",
        "question": "Explain the difference between a container, an image, and a registry.",
        "difficulty": "EASY",
        "tldr": "An image is an immutable, layered template; a container is a running (or stopped) instance of an image with a writable layer; a registry is a server that stores and distributes images (e.g. Docker Hub, GHCR, ECR).",
        "explanation": "An image is a read-only blueprint built from a Dockerfile, composed of stacked layers. A container is a runtime instance created from an image, adding a thin writable layer where its changes live; you can run many containers from one image. A registry is the storage and distribution service where images are pushed and pulled by tag/digest.",
        "code_examples": [
            {"language": "bash", "label": "Image, container, registry lifecycle",
             "code": "docker build -t myapp:1.0 .          # create an image\ndocker run -d --name c1 myapp:1.0    # run a container from the image\ndocker push registry.example.com/myapp:1.0   # push image to a registry\ndocker pull registry.example.com/myapp:1.0   # pull it elsewhere"},
        ],
        "tags": ["concepts", "registry"],
        "gotchas": ["Changes inside a running container live in its writable layer and vanish when the container is removed unless persisted to a volume.", "A tag like :latest is mutable and can point to different image digests over time, so pin by digest for reproducibility."],
        "follow_ups": ["What is an image digest and why pin to it instead of a tag?", "How does a private registry handle authentication?"],
    },
    {
        "slug": "docker-healthchecks",
        "question": "What are container healthchecks and how do they work?",
        "difficulty": "MEDIUM",
        "tldr": "A HEALTHCHECK defines a command Docker runs periodically to determine if a container is healthy; the result (healthy/unhealthy) can drive orchestration decisions like restarts, load-balancer routing, and dependency ordering.",
        "explanation": "HEALTHCHECK runs a command on an interval, marking the container healthy if it exits 0 and unhealthy after a configurable number of consecutive failures. Orchestrators and Compose use this status to decide when a service is ready to receive traffic or needs replacement. A good healthcheck probes actual application readiness (e.g. an HTTP endpoint), not just process existence.",
        "code_examples": [
            {"language": "dockerfile", "label": "HTTP healthcheck in Dockerfile",
             "code": "FROM nginx:alpine\nHEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \\\n  CMD curl -f http://localhost/ || exit 1"},
        ],
        "tags": ["healthcheck", "reliability"],
        "gotchas": ["The healthcheck command must exist in the image; curl/wget may be absent in minimal/distroless images.", "Without start_period, a slow-booting app can be marked unhealthy and restarted before it ever finishes starting."],
        "follow_ups": ["How does Compose's condition: service_healthy use this status?", "How do Kubernetes liveness/readiness probes compare to Docker healthchecks?"],
    },
    {
        "slug": "docker-restart-policies",
        "question": "What are Docker restart policies and when would you use each?",
        "difficulty": "MEDIUM",
        "tldr": "Restart policies (no, on-failure, always, unless-stopped) tell the Docker daemon whether and when to automatically restart a container after it exits or the daemon restarts.",
        "explanation": "Setting a restart policy lets containers recover from crashes or host reboots without manual intervention. on-failure restarts only on non-zero exit (with an optional max retry count), always restarts regardless and on daemon start, and unless-stopped behaves like always but respects a manual stop. Choosing the right policy balances resilience against masking crash loops.",
        "code_examples": [
            {"language": "bash", "label": "Restart policy flags",
             "code": "docker run -d --restart on-failure:5 myapp     # retry up to 5 times on crash\ndocker run -d --restart unless-stopped myapp   # survive reboots, honor manual stop"},
        ],
        "tags": ["reliability", "runtime"],
        "gotchas": ["always will restart the container even after you manually stop it once the daemon restarts; use unless-stopped if that's not what you want.", "Restart policies interact subtly with graceful docker stop versus crashes — semantics differ by policy."],
        "follow_ups": ["How does the daemon apply exponential backoff between restart attempts?", "How do restart policies relate to orchestrator-level self-healing in Kubernetes?"],
    },
    {
        "slug": "docker-cicd-pipeline-stages",
        "question": "What are the typical stages of a CI/CD pipeline for a containerized application?",
        "difficulty": "MEDIUM",
        "tldr": "A common pipeline runs: checkout, build, test, build & scan the image, push to a registry, then deploy to an environment — often gated by approvals between staging and production.",
        "explanation": "Continuous Integration covers building the code and running automated tests on every change to catch regressions early. Continuous Delivery/Deployment then packages the app (here, a Docker image), scans it for vulnerabilities, pushes it to a registry, and rolls it out to environments. Stages are typically ordered fast-to-slow and cheap-to-expensive so failures surface as early as possible.",
        "code_examples": [
            {"language": "yaml", "label": "Pipeline stages in GitHub Actions",
             "code": "jobs:\n  ci:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - run: npm ci && npm test\n      - uses: docker/build-push-action@v6\n        with:\n          push: true\n          tags: ghcr.io/org/app:${{ github.sha }}"},
        ],
        "tags": ["cicd", "pipeline"],
        "gotchas": ["Tagging images with :latest in CI makes rollbacks and traceability hard; tag with the commit SHA.", "Running slow end-to-end tests before fast unit tests wastes feedback time and CI minutes."],
        "follow_ups": ["Where would you insert image vulnerability scanning in the pipeline?", "How do you promote the exact same image artifact across environments instead of rebuilding?"],
    },
    {
        "slug": "docker-blue-green-vs-rolling-deploys",
        "question": "Compare blue-green and rolling deployment strategies.",
        "difficulty": "HARD",
        "tldr": "Blue-green keeps two full environments and switches all traffic from old (blue) to new (green) at once for instant cutover and rollback; rolling deploys gradually replace instances in batches, using fewer resources but mixing versions during the rollout.",
        "explanation": "Blue-green provisions a complete parallel environment running the new version, then flips a router/load balancer to it; rollback is just flipping back, but it requires double the capacity. Rolling updates incrementally swap a few replicas at a time, keeping resource usage flat and avoiding a big-bang switch, at the cost of running two versions simultaneously and slower rollback. The choice depends on resource budget, tolerance for mixed versions, and rollback speed.",
        "code_examples": [
            {"language": "yaml", "label": "Rolling update config (K8s)",
             "code": "spec:\n  strategy:\n    type: RollingUpdate\n    rollingUpdate:\n      maxSurge: 1\n      maxUnavailable: 0"},
        ],
        "tags": ["deployment", "cicd"],
        "gotchas": ["Rolling deploys run old and new versions at once, so backward-incompatible DB migrations can break the old pods mid-rollout.", "Blue-green needs roughly double the infrastructure during the switch, which can be costly for large services."],
        "follow_ups": ["How does canary deployment differ from both strategies?", "How do you handle database schema changes safely during a rolling update?"],
    },
    {
        "slug": "docker-layer-caching-in-ci",
        "question": "How do you make Docker layer caching effective in a CI environment where each run starts fresh?",
        "difficulty": "HARD",
        "tldr": "CI runners are usually ephemeral, so the local layer cache is empty each run; use BuildKit with a remote/registry cache (--cache-from / --cache-to) or the CI provider's cache backend to persist and reuse layers across runs.",
        "explanation": "On a fresh CI runner there is no prior build cache, so every build is cold unless you import one. BuildKit can export cache metadata to a registry or external store and import it on the next run via cache-from, so dependency layers are reused even on new machines. Combining this with cache-friendly Dockerfile ordering yields dramatically faster CI builds.",
        "code_examples": [
            {"language": "yaml", "label": "GitHub Actions cache backend",
             "code": "- uses: docker/build-push-action@v6\n  with:\n    push: true\n    tags: ghcr.io/org/app:${{ github.sha }}\n    cache-from: type=gha\n    cache-to: type=gha,mode=max"},
        ],
        "tags": ["caching", "cicd"],
        "gotchas": ["mode=max caches all layers including intermediate stages but produces a larger cache; mode=min only caches the final image layers.", "Cache-from a stale ref can silently reuse outdated layers if your cache key/ref isn't invalidated properly."],
        "follow_ups": ["How does the inline cache (type=inline) differ from a dedicated registry cache ref?", "How would you cache language-specific dependency directories with RUN --mount=type=cache?"],
    },
    {
        "slug": "docker-base-image-alpine-vs-slim",
        "question": "How do you choose between alpine, slim, and full base images?",
        "difficulty": "MEDIUM",
        "tldr": "Alpine is tiny but uses musl libc (can break glibc binaries and cause subtle bugs); slim trims a Debian/Ubuntu base while keeping glibc compatibility; full images are largest but most convenient. Choose based on compatibility, build complexity, and size needs.",
        "explanation": "Alpine images are very small because they use musl libc and BusyBox, but musl can cause compatibility problems and performance differences (e.g. DNS, Python wheels, native extensions). Slim variants are stripped-down glibc-based Debian images that avoid those pitfalls while still being far smaller than full images. Full images bundle compilers and tools, easing builds at the cost of size and attack surface.",
        "code_examples": [
            {"language": "dockerfile", "label": "Common Python base image variants",
             "code": "# Alpine: smallest, musl libc\nFROM python:3.12-alpine\n\n# Slim: glibc, good size/compat balance (often the safe default)\nFROM python:3.12-slim\n\n# Full: largest, includes build tooling\nFROM python:3.12"},
        ],
        "tags": ["images", "base-image"],
        "gotchas": ["Python on Alpine often can't use prebuilt manylinux wheels and must compile from source, making builds slower and sometimes larger.", "musl vs glibc differences can cause hard-to-debug runtime issues that don't appear on slim/full images."],
        "follow_ups": ["When would distroless be a better choice than slim?", "How do you measure the real security/size tradeoff between these bases?"],
    },
    {
        "slug": "docker-expose-instruction",
        "question": "What does the EXPOSE instruction actually do, and what does it NOT do?",
        "difficulty": "EASY",
        "tldr": "EXPOSE is documentation/metadata declaring which ports the container listens on; it does NOT publish the port to the host. You still need -p (or -P) at run time to actually map ports.",
        "explanation": "EXPOSE records the intended ports in the image metadata, helping humans and tools understand the container's interface and enabling docker run -P to auto-publish them to random host ports. By itself it opens nothing to the outside world. Actual host accessibility requires explicit publishing with -p.",
        "code_examples": [
            {"language": "dockerfile", "label": "EXPOSE as metadata",
             "code": "FROM nginx:alpine\nEXPOSE 80           # documentation only; does not publish\n# docker run -p 8080:80 myimg  <- this is what actually maps the port"},
        ],
        "tags": ["networking", "dockerfile"],
        "gotchas": ["Beginners assume EXPOSE makes a port reachable from the host — it does not; only -p/-P does.", "Containers on the same network can talk on unexposed ports anyway; EXPOSE doesn't act as a firewall."],
        "follow_ups": ["What does docker run -P do with EXPOSEd ports?", "Does EXPOSE affect container-to-container communication at all?"],
    },
    {
        "slug": "docker-non-root-user",
        "question": "Why and how should you run containers as a non-root user?",
        "difficulty": "HARD",
        "tldr": "By default container processes run as root, so a container breakout or vulnerability can grant root-equivalent access; create and switch to an unprivileged user with USER to follow least privilege and reduce blast radius.",
        "explanation": "Running as root inside the container means the process maps to root on the host kernel (absent user namespace remapping), so an escape or a writable-mount exploit is far more dangerous. Best practice is to create a dedicated unprivileged user/group in the Dockerfile and switch to it with USER, ensuring the app only has the permissions it needs. You must also make sure files the app needs to write are owned by or writable to that user.",
        "code_examples": [
            {"language": "dockerfile", "label": "Create and switch to a non-root user",
             "code": "FROM node:20-slim\nRUN groupadd -r app && useradd -r -g app app\nWORKDIR /app\nCOPY --chown=app:app . .\nRUN npm ci --omit=dev\nUSER app\nCMD [\"node\", \"server.js\"]"},
        ],
        "tags": ["security", "non-root"],
        "gotchas": ["Switching to non-root can break the app if it needs to write to root-owned paths or bind to ports below 1024.", "Setting USER doesn't remap UIDs on the host; without user-namespace remapping, UID 0 in the container is UID 0 on the host."],
        "follow_ups": ["How do Linux capabilities and --cap-drop reduce privileges further?", "How does Docker's user-namespace remapping (userns-remap) change the host UID mapping?"],
    },
    {
        "slug": "docker-exec-vs-run",
        "question": "What is the difference between docker exec and docker run?",
        "difficulty": "EASY",
        "tldr": "docker run creates and starts a brand-new container from an image; docker exec runs an additional command inside an already-running container.",
        "explanation": "docker run instantiates a fresh container from an image, applying its own config, network, and writable layer. docker exec targets an existing running container to launch a secondary process in its namespaces — commonly used to open a debugging shell. If the target container isn't running, exec fails, whereas run always starts something new.",
        "code_examples": [
            {"language": "bash", "label": "run (new) vs exec (existing)",
             "code": "# Start a new container\ndocker run -d --name web nginx\n\n# Run an extra command inside the running container (debug shell)\ndocker exec -it web sh"},
        ],
        "tags": ["cli", "runtime"],
        "gotchas": ["Processes started with exec are not the container's main process; the container still lives or dies by its PID 1.", "Files created via an exec shell live in the writable layer and disappear when the container is removed."],
        "follow_ups": ["Why does the container stop when its PID 1 exits even if exec'd processes are still running?", "How do you attach to the main process instead of starting a new one?"],
    },
    {
        "slug": "docker-k8s-pod-deployment-basics",
        "question": "Explain the basic Kubernetes concepts of a Pod and a Deployment and how they relate to containers.",
        "difficulty": "HARD",
        "tldr": "A Pod is the smallest deployable unit wrapping one or more tightly-coupled containers sharing network and storage; a Deployment manages a ReplicaSet that keeps a desired number of identical Pods running and handles rolling updates and self-healing.",
        "explanation": "Containers in Kubernetes never run bare — they run inside Pods, which share a network namespace (same IP) and can share volumes. Because individual Pods are ephemeral, you rarely create them directly; instead a Deployment declares the desired state (image, replica count, update strategy) and its underlying ReplicaSet continuously reconciles reality to match, recreating failed Pods and rolling out new versions. This declarative, self-healing model is the core of Kubernetes orchestration.",
        "code_examples": [
            {"language": "yaml", "label": "Deployment managing 3 Pod replicas",
             "code": "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: web\nspec:\n  replicas: 3\n  selector:\n    matchLabels: { app: web }\n  template:\n    metadata:\n      labels: { app: web }\n    spec:\n      containers:\n        - name: web\n          image: ghcr.io/org/app:1.2.3\n          ports:\n            - containerPort: 8080"},
        ],
        "tags": ["kubernetes", "orchestration"],
        "gotchas": ["Deleting a Pod managed by a Deployment won't permanently remove it — the controller recreates it to maintain replica count.", "Multiple containers in one Pod are co-scheduled and share an IP, so they must not bind the same port."],
        "follow_ups": ["How does a Service provide stable networking in front of ephemeral Pods?", "What is the role of the ReplicaSet between a Deployment and its Pods?"],
    },
]
