QUESTIONS = [
    {
        "slug": "fastapi-depends-basics",
        "question": "What is dependency injection in FastAPI and how does the Depends function work?",
        "difficulty": "EASY",
        "tldr": "Depends declares a callable whose return value FastAPI resolves and injects into your endpoint, enabling shared logic like auth, DB sessions, and common parameters.",
        "explanation": "FastAPI's dependency injection lets you declare reusable components as functions (or callables) and request them in path operations via Depends. FastAPI calls the dependency, resolves any of its own sub-dependencies, and passes the result into your function. This keeps cross-cutting concerns like authentication, pagination, and database access DRY and testable.",
        "code_examples": [
            {"language": "python", "label": "A shared query-parameter dependency",
             "code": "from fastapi import Depends, FastAPI\n\napp = FastAPI()\n\nasync def common_params(q: str | None = None, skip: int = 0, limit: int = 100):\n    return {\"q\": q, \"skip\": skip, \"limit\": limit}\n\n@app.get(\"/items/\")\nasync def read_items(params: dict = Depends(common_params)):\n    return params"},
        ],
        "tags": ["dependency-injection", "depends"],
        "gotchas": ["Calling the dependency yourself (Depends(common_params())) instead of passing the callable (Depends(common_params)) is a common mistake.", "Dependencies are resolved per-request, not once at startup."],
        "follow_ups": ["How can a class be used as a dependency?", "How does FastAPI cache dependency results within a single request?"],
    },
    {
        "slug": "fastapi-async-def-vs-def",
        "question": "What is the difference between defining a path operation with async def versus def in FastAPI?",
        "difficulty": "EASY",
        "tldr": "async def runs the handler on the event loop; plain def runs it in an external threadpool so blocking calls don't stall the loop.",
        "explanation": "FastAPI supports both async def and def endpoints. An async def handler runs directly on the event loop and must never call blocking I/O without awaiting. A plain def handler is automatically run in a threadpool (via anyio), so synchronous/blocking libraries are safe there without freezing concurrency.",
        "code_examples": [
            {"language": "python", "label": "Async vs sync handlers",
             "code": "from fastapi import FastAPI\nimport httpx, time\n\napp = FastAPI()\n\n@app.get(\"/async\")\nasync def async_endpoint():\n    async with httpx.AsyncClient() as client:\n        r = await client.get(\"https://example.com\")\n    return {\"status\": r.status_code}\n\n@app.get(\"/sync\")\ndef sync_endpoint():\n    time.sleep(1)  # blocking is OK: runs in threadpool\n    return {\"ok\": True}"},
        ],
        "tags": ["async", "concurrency"],
        "gotchas": ["Calling blocking I/O (time.sleep, sync DB driver) inside an async def will block the entire event loop and tank throughput.", "The threadpool has a limited size, so heavy use of def handlers can exhaust worker threads."],
        "follow_ups": ["How would you offload CPU-bound work without blocking the event loop?", "How do you tune the anyio threadpool size?"],
    },
    {
        "slug": "fastapi-pydantic-request-models",
        "question": "How do you use a Pydantic model to validate and parse a JSON request body in FastAPI?",
        "difficulty": "EASY",
        "tldr": "Declare a Pydantic BaseModel as a parameter type; FastAPI reads the JSON body, validates it, and gives you a typed instance.",
        "explanation": "When you type-annotate a parameter with a Pydantic model, FastAPI infers it comes from the request body, parses the JSON, validates types and constraints, and raises a 422 on failure. The validated model instance is passed to your function with full editor autocompletion. This is the canonical way to accept structured input.",
        "code_examples": [
            {"language": "python", "label": "Body validation with a BaseModel",
             "code": "from fastapi import FastAPI\nfrom pydantic import BaseModel, Field\n\napp = FastAPI()\n\nclass Item(BaseModel):\n    name: str\n    price: float = Field(gt=0)\n    tags: list[str] = []\n\n@app.post(\"/items/\")\nasync def create_item(item: Item):\n    return {\"received\": item.model_dump()}"},
        ],
        "tags": ["pydantic", "validation"],
        "gotchas": ["A single scalar param won't be treated as the body unless you use Body(); models are auto-detected as body.", "Field constraints like gt/min_length raise 422, not a generic 400."],
        "follow_ups": ["How do you accept multiple body parameters in one request?", "How do you provide example values in the OpenAPI schema?"],
    },
    {
        "slug": "fastapi-path-query-parameters",
        "question": "How does FastAPI distinguish between path, query, and body parameters?",
        "difficulty": "EASY",
        "tldr": "Names in the route path become path params, Pydantic models become the body, and remaining scalar params default to query params.",
        "explanation": "FastAPI uses the function signature plus the route template to classify parameters. If a parameter name appears in the path string it's a path parameter; if its type is a Pydantic model it's read from the body; otherwise singular types (str, int, etc.) become query parameters. You can override this with Path(), Query(), and Body() to add validation and metadata.",
        "code_examples": [
            {"language": "python", "label": "Path and query parameters with validation",
             "code": "from fastapi import FastAPI, Path, Query\n\napp = FastAPI()\n\n@app.get(\"/items/{item_id}\")\nasync def read_item(\n    item_id: int = Path(ge=1),\n    q: str | None = Query(default=None, max_length=50),\n):\n    return {\"item_id\": item_id, \"q\": q}"},
        ],
        "tags": ["parameters", "validation"],
        "gotchas": ["Required query params have no default; adding =None makes them optional.", "A path param type mismatch (e.g. non-int for int) yields 422, not 404."],
        "follow_ups": ["How do you declare a query parameter that accepts a list of values?", "How do you make a query parameter required while still using Query()?"],
    },
    {
        "slug": "fastapi-response-model",
        "question": "What does the response_model parameter do on a FastAPI route?",
        "difficulty": "EASY",
        "tldr": "response_model validates, filters, and serializes the response data to a declared schema and documents it in OpenAPI.",
        "explanation": "Setting response_model tells FastAPI to coerce the returned data into the given Pydantic model before sending it. This filters out extra fields, enforces types, and shapes the OpenAPI response schema. It's the standard way to avoid leaking internal fields (like password hashes) from a richer internal object.",
        "code_examples": [
            {"language": "python", "label": "Filtering output with response_model",
             "code": "from fastapi import FastAPI\nfrom pydantic import BaseModel\n\napp = FastAPI()\n\nclass UserIn(BaseModel):\n    username: str\n    password: str\n\nclass UserOut(BaseModel):\n    username: str\n\n@app.post(\"/users/\", response_model=UserOut)\nasync def create_user(user: UserIn):\n    return user  # password is stripped from the response"},
        ],
        "tags": ["response-model", "serialization"],
        "gotchas": ["Returning a field not present in the response_model silently drops it; a missing required field raises a server error.", "response_model_exclude_unset is needed to omit default-valued fields."],
        "follow_ups": ["How do you exclude unset or None fields from the response?", "How does response_model interact with the return type annotation in newer FastAPI?"],
    },
    {
        "slug": "fastapi-httpexception-status-codes",
        "question": "How do you return custom HTTP status codes and errors in FastAPI?",
        "difficulty": "EASY",
        "tldr": "Set status_code on the decorator for the success case and raise HTTPException for errors with a status code and detail.",
        "explanation": "Use the status_code argument on the route decorator (often with the status module constants) to set the default success status. For error conditions, raise HTTPException with a status_code and detail, which FastAPI converts into a JSON error response. You can also attach custom headers to an HTTPException.",
        "code_examples": [
            {"language": "python", "label": "Status codes and HTTPException",
             "code": "from fastapi import FastAPI, HTTPException, status\n\napp = FastAPI()\nitems = {\"foo\": \"bar\"}\n\n@app.post(\"/items/\", status_code=status.HTTP_201_CREATED)\nasync def create():\n    return {\"created\": True}\n\n@app.get(\"/items/{key}\")\nasync def get_item(key: str):\n    if key not in items:\n        raise HTTPException(status_code=404, detail=\"Item not found\")\n    return {\"value\": items[key]}"},
        ],
        "tags": ["http", "errors"],
        "gotchas": ["Returning a dict with an error key still sends 200; you must raise HTTPException to change the status.", "HTTPException must be raised, not returned."],
        "follow_ups": ["How do you register a custom exception handler?", "How do you add headers to an error response?"],
    },
    {
        "slug": "fastapi-class-based-dependencies",
        "question": "How do you implement a class-based dependency and why is it useful?",
        "difficulty": "MEDIUM",
        "tldr": "A class with typed __init__ params can be passed to Depends; FastAPI treats __init__ params as the dependency's parameters and injects an instance.",
        "explanation": "Because a class is callable, you can use Depends(SomeClass) and FastAPI will populate the constructor arguments from the request (query, path, etc.), giving your endpoint a fully initialized instance. This is cleaner than a function when you want autocompletion on the result and to group related parameters. You can even abbreviate the annotation as a shortcut.",
        "code_examples": [
            {"language": "python", "label": "Class as a dependency with the Depends() shortcut",
             "code": "from fastapi import Depends, FastAPI\n\napp = FastAPI()\n\nclass Pagination:\n    def __init__(self, skip: int = 0, limit: int = 100):\n        self.skip = skip\n        self.limit = limit\n\n@app.get(\"/items/\")\nasync def read_items(page: Pagination = Depends()):\n    return {\"skip\": page.skip, \"limit\": page.limit}"},
        ],
        "tags": ["dependency-injection", "depends"],
        "gotchas": ["Depends() with no argument only works when the parameter is already annotated with the class type.", "Constructor params follow the same path/query/body inference rules as endpoints."],
        "follow_ups": ["When would you prefer a function dependency over a class?", "How do you parameterize a class dependency instance (e.g. role checker)?"],
    },
    {
        "slug": "fastapi-yield-dependencies",
        "question": "How do yield-based dependencies work for setup and teardown in FastAPI?",
        "difficulty": "MEDIUM",
        "tldr": "A dependency that yields runs code before the request (setup), provides the yielded value, then runs post-yield code as teardown after the response.",
        "explanation": "Using yield instead of return lets a dependency act like a context manager: code before yield is setup, the yielded value is injected, and code after yield runs once the response is sent. This is ideal for opening and closing resources such as database sessions. Exceptions can be caught around the yield for cleanup.",
        "code_examples": [
            {"language": "python", "label": "Session lifecycle with a yield dependency",
             "code": "from fastapi import Depends, FastAPI\n\napp = FastAPI()\n\ndef get_db():\n    db = SessionLocal()\n    try:\n        yield db\n    finally:\n        db.close()\n\n@app.get(\"/users/\")\nasync def list_users(db = Depends(get_db)):\n    return db.query_all()"},
        ],
        "tags": ["dependency-injection", "yield"],
        "gotchas": ["Code after yield runs after the response is generated, so raising HTTPException there will not change the already-sent response in older versions.", "Use try/finally to guarantee teardown even when the endpoint raises."],
        "follow_ups": ["How do exceptions raised in the endpoint propagate to the yield dependency?", "How does dependency caching interact with yield dependencies?"],
    },
    {
        "slug": "fastapi-dependency-caching",
        "question": "How does FastAPI cache dependency results within a request, and how do you disable it?",
        "difficulty": "MEDIUM",
        "tldr": "By default a dependency called multiple times in one request is resolved once and cached; pass use_cache=False to Depends to force re-evaluation.",
        "explanation": "If the same dependency callable appears multiple times in a request's dependency tree, FastAPI calls it only once and reuses the result for that request. This avoids redundant work like re-querying the current user. You can opt out with Depends(dep, use_cache=False) when each use must be fresh.",
        "code_examples": [
            {"language": "python", "label": "Controlling dependency caching",
             "code": "from fastapi import Depends, FastAPI\n\napp = FastAPI()\n\ndef expensive():\n    print(\"computing\")  # printed once per request by default\n    return 42\n\n@app.get(\"/\")\nasync def root(\n    a: int = Depends(expensive),\n    b: int = Depends(expensive, use_cache=False),\n):\n    return {\"a\": a, \"b\": b}"},
        ],
        "tags": ["dependency-injection", "caching"],
        "gotchas": ["Caching is per-request, not across requests; it is not a global memoization layer.", "Two dependencies that differ only by parameters are still distinct cache entries."],
        "follow_ups": ["How does caching behave with sub-dependencies shared across the tree?", "When would caching cause subtle bugs?"],
    },
    {
        "slug": "fastapi-background-tasks",
        "question": "How do you run work after returning a response using BackgroundTasks?",
        "difficulty": "MEDIUM",
        "tldr": "Declare a BackgroundTasks parameter and call add_task; the function runs after the response is sent, within the same process.",
        "explanation": "FastAPI's BackgroundTasks lets you schedule a callable to run after the response has been returned to the client, useful for lightweight follow-up work like sending an email or writing a log. You add tasks with add_task(func, *args, **kwargs). It runs in the same event loop/threadpool, so it's not a replacement for a real task queue under heavy load.",
        "code_examples": [
            {"language": "python", "label": "Scheduling a background task",
             "code": "from fastapi import BackgroundTasks, FastAPI\n\napp = FastAPI()\n\ndef write_log(message: str):\n    with open(\"log.txt\", \"a\") as f:\n        f.write(message + \"\\n\")\n\n@app.post(\"/notify/\")\nasync def notify(email: str, tasks: BackgroundTasks):\n    tasks.add_task(write_log, f\"notified {email}\")\n    return {\"queued\": True}"},
        ],
        "tags": ["background-tasks", "async"],
        "gotchas": ["Background tasks share the process, so a crash or long-running task can affect the server; use Celery/RQ for durability.", "Exceptions in background tasks are not reported to the client since the response already went out."],
        "follow_ups": ["When should you reach for Celery instead of BackgroundTasks?", "Can a dependency add background tasks?"],
    },
    {
        "slug": "fastapi-custom-middleware",
        "question": "How do you write custom middleware in FastAPI and what are its limitations?",
        "difficulty": "MEDIUM",
        "tldr": "Use @app.middleware('http') to wrap every request/response, calling await call_next(request) and returning the (possibly modified) response.",
        "explanation": "Middleware in FastAPI (built on Starlette) intercepts every request before it reaches the route and every response before it goes out. You define an async function decorated with @app.middleware('http') that receives the request and a call_next callable. It's ideal for cross-cutting concerns like timing, logging, or adding headers, but can't easily access path-operation-specific dependencies.",
        "code_examples": [
            {"language": "python", "label": "Timing middleware adding a response header",
             "code": "import time\nfrom fastapi import FastAPI, Request\n\napp = FastAPI()\n\n@app.middleware(\"http\")\nasync def add_process_time(request: Request, call_next):\n    start = time.perf_counter()\n    response = await call_next(request)\n    response.headers[\"X-Process-Time\"] = str(time.perf_counter() - start)\n    return response"},
        ],
        "tags": ["middleware", "starlette"],
        "gotchas": ["Reading the request body in middleware can consume the stream so the endpoint sees an empty body unless handled carefully.", "Middleware runs outside the route's dependency/exception-handler context for some error types."],
        "follow_ups": ["What's the difference between middleware and a dependency?", "How does middleware ordering work when multiple are registered?"],
    },
    {
        "slug": "fastapi-oauth2-jwt-auth",
        "question": "How do you implement OAuth2 password flow with JWT bearer tokens in FastAPI?",
        "difficulty": "MEDIUM",
        "tldr": "Use OAuth2PasswordBearer to extract the bearer token, decode/verify the JWT in a dependency, and return the authenticated user.",
        "explanation": "FastAPI provides OAuth2PasswordBearer which declares the token URL and extracts the Authorization: Bearer token from requests. A dependency decodes and validates the JWT (signature, expiry) and loads the user, raising 401 on failure. Protected endpoints simply depend on get_current_user.",
        "code_examples": [
            {"language": "python", "label": "JWT verification dependency",
             "code": "from fastapi import Depends, FastAPI, HTTPException, status\nfrom fastapi.security import OAuth2PasswordBearer\nimport jwt\n\napp = FastAPI()\noauth2_scheme = OAuth2PasswordBearer(tokenUrl=\"token\")\nSECRET = \"change-me\"\n\nasync def get_current_user(token: str = Depends(oauth2_scheme)):\n    try:\n        payload = jwt.decode(token, SECRET, algorithms=[\"HS256\"])\n    except jwt.PyJWTError:\n        raise HTTPException(status.HTTP_401_UNAUTHORIZED, \"Invalid token\")\n    return {\"username\": payload[\"sub\"]}\n\n@app.get(\"/me\")\nasync def me(user: dict = Depends(get_current_user)):\n    return user"},
        ],
        "tags": ["auth", "jwt"],
        "gotchas": ["Always set and verify an expiry (exp) claim; tokens without expiry never become invalid.", "OAuth2PasswordBearer only extracts the token; it does not validate it for you."],
        "follow_ups": ["How do you implement scopes/roles with Security and SecurityScopes?", "Where should you store the JWT on the client and why?"],
    },
    {
        "slug": "fastapi-lifespan-events",
        "question": "How do you run startup and shutdown logic using the lifespan context manager?",
        "difficulty": "MEDIUM",
        "tldr": "Pass an async context manager to FastAPI(lifespan=...); code before yield runs at startup, code after yield runs at shutdown.",
        "explanation": "The modern way to handle startup/shutdown is the lifespan parameter: an async generator decorated with @asynccontextmanager. Code before yield runs once when the app starts (e.g. open DB pools, load ML models), and code after yield runs at shutdown. It replaces the deprecated @app.on_event handlers and can share state via the yielded dict or app.state.",
        "code_examples": [
            {"language": "python", "label": "Lifespan startup/shutdown",
             "code": "from contextlib import asynccontextmanager\nfrom fastapi import FastAPI\n\n@asynccontextmanager\nasync def lifespan(app: FastAPI):\n    app.state.model = load_model()  # startup\n    yield\n    app.state.model = None         # shutdown\n\napp = FastAPI(lifespan=lifespan)\n\n@app.get(\"/predict\")\nasync def predict():\n    return {\"ready\": app.state.model is not None}"},
        ],
        "tags": ["lifespan", "startup"],
        "gotchas": ["@app.on_event('startup'/'shutdown') is deprecated in favor of lifespan.", "An exception before yield prevents the app from starting; handle errors carefully."],
        "follow_ups": ["How do you share startup-created resources with request handlers?", "How does lifespan interact with TestClient in tests?"],
    },
    {
        "slug": "fastapi-422-validation-errors",
        "question": "What causes a 422 Unprocessable Entity response and how do you customize it?",
        "difficulty": "MEDIUM",
        "tldr": "FastAPI returns 422 when request data fails Pydantic validation; override the RequestValidationError handler to reshape the error body.",
        "explanation": "When incoming data doesn't match the declared types/constraints, FastAPI raises RequestValidationError and returns a 422 with a structured list of errors (location, message, type). You can register a custom exception handler for RequestValidationError to change the format or status code. This is distinct from HTTPException-based errors you raise yourself.",
        "code_examples": [
            {"language": "python", "label": "Customizing validation error responses",
             "code": "from fastapi import FastAPI, Request\nfrom fastapi.exceptions import RequestValidationError\nfrom fastapi.responses import JSONResponse\n\napp = FastAPI()\n\n@app.exception_handler(RequestValidationError)\nasync def validation_handler(request: Request, exc: RequestValidationError):\n    return JSONResponse(\n        status_code=400,\n        content={\"errors\": exc.errors(), \"body\": exc.body},\n    )"},
        ],
        "tags": ["validation", "errors"],
        "gotchas": ["422 (not 400) is the default for body/param validation failures, which can surprise API consumers.", "exc.errors() in Pydantic v2 has a slightly different structure than v1."],
        "follow_ups": ["How do you localize or translate validation messages?", "How can you add custom validators that produce 422 errors?"],
    },
    {
        "slug": "fastapi-routers-modularization",
        "question": "How do you organize a large FastAPI app using APIRouter and include_router?",
        "difficulty": "MEDIUM",
        "tldr": "Split endpoints into APIRouter instances per domain, then mount them with app.include_router, optionally adding prefix, tags, and dependencies.",
        "explanation": "APIRouter is a mini-FastAPI you can define in separate modules to group related routes. You register them on the main app with include_router, where you can apply a common prefix, tags, dependencies, and responses to all the router's routes. This keeps large codebases modular and maintainable.",
        "code_examples": [
            {"language": "python", "label": "Modular routers with shared prefix and dependencies",
             "code": "from fastapi import APIRouter\n\nrouter = APIRouter()\n\n@router.get(\"/\")\nasync def list_users():\n    return [{\"id\": 1}]\n\n# main.py\nfrom fastapi import Depends, FastAPI\nfrom routers import users\n\napp = FastAPI()\napp.include_router(\n    users.router,\n    prefix=\"/users\",\n    tags=[\"users\"],\n    dependencies=[Depends(verify_token)],\n)"},
        ],
        "tags": ["routers", "structure"],
        "gotchas": ["Dependencies passed to include_router run for every route but their return value is not injected unless added to the path operation.", "Prefixes must not end with a trailing slash."],
        "follow_ups": ["What's the difference between include_router dependencies and per-route Depends?", "How do you version an API using routers?"],
    },
    {
        "slug": "fastapi-cors-middleware",
        "question": "How do you configure CORS in a FastAPI application?",
        "difficulty": "MEDIUM",
        "tldr": "Add CORSMiddleware with allow_origins, allow_methods, allow_headers, and allow_credentials to permit cross-origin browser requests.",
        "explanation": "Browsers block cross-origin requests unless the server sends proper CORS headers. FastAPI uses Starlette's CORSMiddleware, which you add via app.add_middleware with the allowed origins, methods, headers, and credential settings. Misconfiguration is a common source of frontend integration bugs.",
        "code_examples": [
            {"language": "python", "label": "Enabling CORS",
             "code": "from fastapi import FastAPI\nfrom fastapi.middleware.cors import CORSMiddleware\n\napp = FastAPI()\n\napp.add_middleware(\n    CORSMiddleware,\n    allow_origins=[\"https://app.example.com\"],\n    allow_credentials=True,\n    allow_methods=[\"*\"],\n    allow_headers=[\"*\"],\n)"},
        ],
        "tags": ["cors", "middleware"],
        "gotchas": ["You cannot use allow_origins=['*'] together with allow_credentials=True; browsers reject that combination.", "Preflight OPTIONS requests must be allowed for non-simple requests to succeed."],
        "follow_ups": ["How do you allow a dynamic set of origins?", "Why might a wildcard origin with credentials fail?"],
    },
    {
        "slug": "fastapi-streaming-responses",
        "question": "How do you stream a large or generated response with StreamingResponse?",
        "difficulty": "MEDIUM",
        "tldr": "Return a StreamingResponse wrapping a (sync or async) generator so data is sent in chunks without buffering it all in memory.",
        "explanation": "StreamingResponse takes an iterator/generator and sends its chunks to the client incrementally, ideal for large files, server-sent events, or token-by-token LLM output. The generator can be sync or async, and you set media_type accordingly. This avoids loading the entire payload into memory.",
        "code_examples": [
            {"language": "python", "label": "Server-sent events with StreamingResponse",
             "code": "import asyncio\nfrom fastapi import FastAPI\nfrom fastapi.responses import StreamingResponse\n\napp = FastAPI()\n\nasync def number_stream():\n    for i in range(5):\n        yield f\"data: {i}\\n\\n\"\n        await asyncio.sleep(0.5)\n\n@app.get(\"/stream\")\nasync def stream():\n    return StreamingResponse(number_stream(), media_type=\"text/event-stream\")"},
        ],
        "tags": ["streaming", "responses"],
        "gotchas": ["Raising HTTPException after streaming starts can't change the already-sent status code.", "Some proxies buffer responses, defeating real-time streaming unless buffering is disabled."],
        "follow_ups": ["How do StreamingResponse and FileResponse differ?", "How do you implement Server-Sent Events vs WebSockets?"],
    },
    {
        "slug": "fastapi-websockets-basics",
        "question": "How do you implement a basic WebSocket endpoint in FastAPI?",
        "difficulty": "MEDIUM",
        "tldr": "Use @app.websocket, await websocket.accept(), then loop on receive_text/send_text, handling WebSocketDisconnect.",
        "explanation": "FastAPI supports WebSockets through Starlette. You decorate an async function with @app.websocket(path), accept the connection, then exchange messages in a loop using receive/send methods. You should catch WebSocketDisconnect to clean up when the client leaves.",
        "code_examples": [
            {"language": "python", "label": "Echo WebSocket endpoint",
             "code": "from fastapi import FastAPI, WebSocket, WebSocketDisconnect\n\napp = FastAPI()\n\n@app.websocket(\"/ws\")\nasync def ws_endpoint(websocket: WebSocket):\n    await websocket.accept()\n    try:\n        while True:\n            data = await websocket.receive_text()\n            await websocket.send_text(f\"echo: {data}\")\n    except WebSocketDisconnect:\n        print(\"client disconnected\")"},
        ],
        "tags": ["websockets", "realtime"],
        "gotchas": ["Forgetting await websocket.accept() leaves the handshake incomplete and the client hangs.", "WebSocket routes don't use response_model or normal HTTP dependencies the same way."],
        "follow_ups": ["How do you broadcast a message to many connected clients?", "How do dependencies work for WebSocket endpoints?"],
    },
    {
        "slug": "fastapi-file-uploads",
        "question": "How do you handle file uploads in FastAPI with UploadFile?",
        "difficulty": "MEDIUM",
        "tldr": "Declare a parameter typed UploadFile = File(...); FastAPI provides a spooled file with async read/write and metadata like filename and content_type.",
        "explanation": "FastAPI handles multipart/form-data uploads via UploadFile, which wraps a SpooledTemporaryFile so large files spill to disk instead of consuming memory. You access bytes with await file.read() and metadata like filename and content_type. It requires the python-multipart package to be installed.",
        "code_examples": [
            {"language": "python", "label": "Receiving an uploaded file",
             "code": "from fastapi import FastAPI, File, UploadFile\n\napp = FastAPI()\n\n@app.post(\"/upload/\")\nasync def upload(file: UploadFile = File(...)):\n    contents = await file.read()\n    return {\n        \"filename\": file.filename,\n        \"content_type\": file.content_type,\n        \"size\": len(contents),\n    }"},
        ],
        "tags": ["file-upload", "forms"],
        "gotchas": ["You must install python-multipart or form/file parsing fails at startup.", "Reading huge files fully into memory with read() defeats the spooling; stream in chunks instead."],
        "follow_ups": ["How do you accept multiple files in one request?", "How do you stream an upload to disk without loading it all into memory?"],
    },
    {
        "slug": "fastapi-pydantic-settings",
        "question": "How do you manage application configuration using pydantic-settings?",
        "difficulty": "MEDIUM",
        "tldr": "Subclass BaseSettings from pydantic-settings; fields are auto-loaded from environment variables (and .env), validated, and type-coerced.",
        "explanation": "pydantic-settings (the v2 successor to Pydantic v1's BaseSettings) reads configuration from environment variables and optional .env files into a typed, validated settings object. You typically expose it via a cached dependency so it's parsed once. This gives type safety and centralizes configuration.",
        "code_examples": [
            {"language": "python", "label": "Typed settings with caching",
             "code": "from functools import lru_cache\nfrom fastapi import Depends, FastAPI\nfrom pydantic_settings import BaseSettings, SettingsConfigDict\n\nclass Settings(BaseSettings):\n    app_name: str = \"MyApp\"\n    database_url: str\n    model_config = SettingsConfigDict(env_file=\".env\")\n\n@lru_cache\ndef get_settings() -> Settings:\n    return Settings()\n\napp = FastAPI()\n\n@app.get(\"/info\")\nasync def info(settings: Settings = Depends(get_settings)):\n    return {\"app\": settings.app_name}"},
        ],
        "tags": ["settings", "configuration"],
        "gotchas": ["In Pydantic v2, BaseSettings moved to the separate pydantic-settings package.", "Without lru_cache the .env file is re-read on every dependency resolution."],
        "follow_ups": ["How do you override settings in tests?", "How do environment variables map to nested settings models?"],
    },
    {
        "slug": "fastapi-testing-testclient",
        "question": "How do you test FastAPI endpoints with TestClient?",
        "difficulty": "MEDIUM",
        "tldr": "Wrap the app in TestClient (requests-style API over the ASGI app) and assert on status codes and JSON, optionally overriding dependencies.",
        "explanation": "FastAPI's TestClient (built on httpx/Starlette) lets you call your app in-process without a running server, using a requests-like interface. You can assert on response status and body, and crucially override dependencies via app.dependency_overrides to inject test doubles like a fake database. Use it inside a context manager if you need lifespan events to run.",
        "code_examples": [
            {"language": "python", "label": "TestClient with dependency override",
             "code": "from fastapi import FastAPI, Depends\nfrom fastapi.testclient import TestClient\n\napp = FastAPI()\n\ndef get_db():\n    return \"real-db\"\n\n@app.get(\"/db\")\nasync def read_db(db=Depends(get_db)):\n    return {\"db\": db}\n\nclient = TestClient(app)\napp.dependency_overrides[get_db] = lambda: \"fake-db\"\n\ndef test_db():\n    resp = client.get(\"/db\")\n    assert resp.status_code == 200\n    assert resp.json() == {\"db\": \"fake-db\"}"},
        ],
        "tags": ["testing", "testclient"],
        "gotchas": ["Lifespan/startup events only run when TestClient is used as a context manager (with TestClient(app) as client).", "Remember to clear dependency_overrides between tests to avoid leakage."],
        "follow_ups": ["How do you test async endpoints with httpx.AsyncClient instead?", "How do you test WebSocket endpoints?"],
    },
    {
        "slug": "fastapi-openapi-docs-customization",
        "question": "How does FastAPI generate OpenAPI docs and how can you customize them?",
        "difficulty": "EASY",
        "tldr": "FastAPI auto-builds an OpenAPI schema from your routes and serves Swagger UI at /docs and ReDoc at /redoc; you can tweak metadata and override the schema.",
        "explanation": "FastAPI introspects your path operations, parameters, and Pydantic models to generate an OpenAPI (Swagger) schema automatically, exposed at /openapi.json with interactive docs at /docs and /redoc. You customize it via FastAPI() metadata (title, version, description), per-route tags/summaries, and can fully override openapi() if needed. Docs URLs can be disabled in production.",
        "code_examples": [
            {"language": "python", "label": "Customizing OpenAPI metadata",
             "code": "from fastapi import FastAPI\n\napp = FastAPI(\n    title=\"My API\",\n    version=\"1.2.0\",\n    description=\"Demo API\",\n    docs_url=\"/docs\",      # set to None to disable\n    redoc_url=None,\n)\n\n@app.get(\"/ping\", tags=[\"health\"], summary=\"Health check\")\nasync def ping():\n    return {\"pong\": True}"},
        ],
        "tags": ["openapi", "docs"],
        "gotchas": ["Setting docs_url=None disables Swagger UI but /openapi.json may still be served unless also disabled.", "Operation IDs default to function-name based and can collide across routers."],
        "follow_ups": ["How do you add authentication to the Swagger UI try-it-out?", "How do you customize generated operation IDs for cleaner client codegen?"],
    },
    {
        "slug": "fastapi-sync-vs-async-db-sessions",
        "question": "How do synchronous and asynchronous database sessions differ in FastAPI, and how do you wire each?",
        "difficulty": "HARD",
        "tldr": "Sync sessions belong in def endpoints (threadpool); async sessions (AsyncSession + async engine) belong in async def endpoints with await on queries.",
        "explanation": "With a sync ORM session (e.g. SQLAlchemy Session), you should use plain def endpoints so blocking DB calls run in the threadpool and don't stall the event loop. With async drivers (asyncpg) and AsyncSession, you use async def endpoints and await your queries, getting true async I/O. Mixing a sync session inside async def blocks the loop; mixing await on a sync session fails.",
        "code_examples": [
            {"language": "python", "label": "Async SQLAlchemy session dependency",
             "code": "from fastapi import Depends, FastAPI\nfrom sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine\nfrom sqlalchemy import text\n\nengine = create_async_engine(\"postgresql+asyncpg://localhost/db\")\nSession = async_sessionmaker(engine, expire_on_commit=False)\napp = FastAPI()\n\nasync def get_db():\n    async with Session() as session:\n        yield session\n\n@app.get(\"/count\")\nasync def count(db: AsyncSession = Depends(get_db)):\n    result = await db.execute(text(\"SELECT count(*) FROM users\"))\n    return {\"count\": result.scalar()}"},
        ],
        "tags": ["database", "async"],
        "gotchas": ["Using a synchronous Session inside an async def endpoint blocks the event loop and silently kills concurrency.", "AsyncSession objects are not safe to share across concurrent tasks/requests."],
        "follow_ups": ["How do you run Alembic migrations with an async engine?", "When is sync SQLAlchemy in a threadpool actually preferable to async?"],
    },
    {
        "slug": "fastapi-pydantic-v2-migration",
        "question": "What are the key Pydantic v2 changes that affect FastAPI applications?",
        "difficulty": "HARD",
        "tldr": "v2 renames core methods (.dict()->.model_dump(), .parse_obj()->.model_validate()), replaces Config class with model_config, moves BaseSettings out, and uses field/model validators.",
        "explanation": "FastAPI's modern versions run on Pydantic v2, which brings a faster Rust core and many API renames. Serialization moved to model_dump()/model_dump_json(), parsing to model_validate(), and the inner Config class to a model_config dict (or ConfigDict). Validators changed from @validator/@root_validator to @field_validator/@model_validator, and BaseSettings now lives in pydantic-settings.",
        "code_examples": [
            {"language": "python", "label": "Pydantic v2 config and validator syntax",
             "code": "from pydantic import BaseModel, ConfigDict, field_validator\n\nclass User(BaseModel):\n    model_config = ConfigDict(from_attributes=True)  # was orm_mode\n    name: str\n    email: str\n\n    @field_validator(\"email\")\n    @classmethod\n    def must_have_at(cls, v: str) -> str:\n        if \"@\" not in v:\n            raise ValueError(\"invalid email\")\n        return v\n\nu = User.model_validate({\"name\": \"Ada\", \"email\": \"a@b.com\"})\nprint(u.model_dump())"},
        ],
        "tags": ["pydantic", "migration"],
        "gotchas": ["orm_mode=True is now from_attributes=True; old name raises a deprecation warning.", ".dict() and .json() still work but are deprecated aliases for model_dump()/model_dump_json()."],
        "follow_ups": ["How do you run v1-style models in compatibility mode under v2?", "What performance differences come from the Rust core?"],
    },
    {
        "slug": "fastapi-global-dependencies-security-scopes",
        "question": "How do you enforce role-based access using Security and SecurityScopes?",
        "difficulty": "HARD",
        "tldr": "Declare scopes on OAuth2 schemes, depend on user-loading via Security(..., scopes=[...]), and verify the token's scopes against required scopes in SecurityScopes.",
        "explanation": "FastAPI's Security (a specialization of Depends) integrates OAuth2 scopes into the dependency tree and OpenAPI. You attach required scopes at each protected endpoint, and a dependency receives a SecurityScopes object listing them, comparing against the scopes encoded in the JWT. This enables fine-grained, documented authorization that also drives the Swagger UI auth flow.",
        "code_examples": [
            {"language": "python", "label": "Scope enforcement with SecurityScopes",
             "code": "from fastapi import Depends, FastAPI, HTTPException, Security, status\nfrom fastapi.security import OAuth2PasswordBearer, SecurityScopes\n\noauth2 = OAuth2PasswordBearer(tokenUrl=\"token\", scopes={\"admin\": \"Admin access\"})\napp = FastAPI()\n\nasync def get_user(scopes: SecurityScopes, token: str = Depends(oauth2)):\n    token_scopes = decode(token).get(\"scopes\", [])\n    for required in scopes.scopes:\n        if required not in token_scopes:\n            raise HTTPException(status.HTTP_403_FORBIDDEN, \"Not enough permissions\")\n    return {\"token\": token}\n\n@app.get(\"/admin\")\nasync def admin(user=Security(get_user, scopes=[\"admin\"])):\n    return {\"ok\": True}"},
        ],
        "tags": ["auth", "security"],
        "gotchas": ["Scopes accumulate down the dependency tree, so a sub-dependency's required scopes are added to the endpoint's.", "Use 403 for insufficient scope vs 401 for missing/invalid authentication."],
        "follow_ups": ["How are required scopes reflected in the OpenAPI security schema?", "How do you model hierarchical or wildcard scopes?"],
    },
    {
        "slug": "fastapi-blocking-cpu-bound-offload",
        "question": "How do you handle CPU-bound or blocking work in an async FastAPI app without harming concurrency?",
        "difficulty": "HARD",
        "tldr": "Don't block the event loop: use a plain def endpoint, run_in_threadpool/anyio.to_thread for I/O, or offload CPU work to a process pool or external task queue.",
        "explanation": "Heavy CPU work or blocking calls inside async def freeze the single event loop and serialize all requests. For blocking I/O, either use a sync def endpoint (auto-threadpooled) or await anyio.to_thread.run_sync. For genuinely CPU-bound work, use a ProcessPoolExecutor or hand it off to a task queue like Celery, since threads don't escape the GIL.",
        "code_examples": [
            {"language": "python", "label": "Offloading blocking I/O and CPU work",
             "code": "import anyio\nfrom concurrent.futures import ProcessPoolExecutor\nimport asyncio\nfrom fastapi import FastAPI\n\napp = FastAPI()\npool = ProcessPoolExecutor()\n\ndef heavy_cpu(n: int) -> int:\n    return sum(i * i for i in range(n))\n\n@app.get(\"/cpu\")\nasync def cpu(n: int = 10_000_000):\n    loop = asyncio.get_running_loop()\n    result = await loop.run_in_executor(pool, heavy_cpu, n)\n    return {\"result\": result}"},
        ],
        "tags": ["async", "performance"],
        "gotchas": ["Threads don't bypass the GIL, so CPU-bound work needs processes, not threads.", "Objects sent to a ProcessPoolExecutor must be picklable, and process startup has overhead."],
        "follow_ups": ["How does anyio's threadpool limiter affect throughput?", "When is a dedicated task queue better than in-process offloading?"],
    },
    {
        "slug": "fastapi-sub-applications-mounting",
        "question": "How do you mount sub-applications (including non-FastAPI ASGI apps) in FastAPI?",
        "difficulty": "HARD",
        "tldr": "Use app.mount(path, sub_app) to attach an independent ASGI app (another FastAPI, Starlette, WSGI-wrapped, or static files) under a path prefix with its own docs.",
        "explanation": "Mounting attaches a completely separate ASGI application at a path prefix, giving it its own routes, middleware, and OpenAPI docs, independent of the parent. This differs from include_router, which merges routes into the same app. Mounting is used for versioned sub-apps, static files (StaticFiles), or integrating a WSGI app via WSGIMiddleware.",
        "code_examples": [
            {"language": "python", "label": "Mounting a sub-app and static files",
             "code": "from fastapi import FastAPI\nfrom fastapi.staticfiles import StaticFiles\n\napp = FastAPI()\nsubapi = FastAPI()\n\n@subapi.get(\"/status\")\nasync def status():\n    return {\"sub\": True}\n\napp.mount(\"/v2\", subapi)              # own /v2/docs\napp.mount(\"/static\", StaticFiles(directory=\"static\"), name=\"static\")"},
        ],
        "tags": ["mounting", "structure"],
        "gotchas": ["Mounted sub-apps have isolated docs and don't share the parent's OpenAPI schema or dependencies.", "Parent middleware wraps mounted apps, but sub-app-specific exception handlers stay local."],
        "follow_ups": ["When should you mount a sub-app versus include a router?", "How do you serve a WSGI (e.g. Flask) app inside FastAPI?"],
    },
    {
        "slug": "fastapi-dependency-overrides-advanced",
        "question": "How do dependency overrides and nested dependency resolution help with testing and environment swapping?",
        "difficulty": "HARD",
        "tldr": "app.dependency_overrides maps a dependency callable to a replacement, swapping it everywhere in the tree (including nested sub-dependencies) for tests or environments.",
        "explanation": "FastAPI resolves dependencies recursively, so overriding a single dependency callable via app.dependency_overrides replaces it everywhere it appears in the tree, including deep sub-dependencies. This is the canonical mechanism for injecting test databases, fake auth, or stub external services without touching production code. Overrides are keyed by the original callable object identity.",
        "code_examples": [
            {"language": "python", "label": "Overriding a nested dependency",
             "code": "from fastapi import Depends, FastAPI\nfrom fastapi.testclient import TestClient\n\napp = FastAPI()\n\ndef get_settings():\n    return {\"env\": \"prod\"}\n\ndef get_service(settings=Depends(get_settings)):\n    return f\"service-{settings['env']}\"\n\n@app.get(\"/svc\")\nasync def svc(service=Depends(get_service)):\n    return {\"service\": service}\n\napp.dependency_overrides[get_settings] = lambda: {\"env\": \"test\"}\nclient = TestClient(app)\nassert client.get(\"/svc\").json() == {\"service\": \"service-test\"}"},
        ],
        "tags": ["testing", "dependency-injection"],
        "gotchas": ["Overrides key on the exact callable object, so importing the same function under two paths can break the match.", "Forgetting to clear app.dependency_overrides leaks state between tests."],
        "follow_ups": ["How do overrides interact with use_cache and yield dependencies?", "How would you scope overrides per-test with a fixture?"],
    },
]
