QUESTIONS = [
    {
        "slug": "js-closures",
        "question": "What is a closure and why is it useful?",
        "difficulty": "MEDIUM",
        "tldr": "A closure is a function that retains access to its lexical scope even after that scope has returned.",
        "explanation": "When a function is created it captures the variables in scope at definition time. Those variables stay alive as long as the closure does — enabling data privacy, factory functions, and stateful callbacks.",
        "code_examples": [
            {"language": "javascript", "label": "Counter via closure",
             "code": "function makeCounter() {\n  let count = 0;\n  return () => ++count;\n}\nconst next = makeCounter();\nnext(); // 1\nnext(); // 2"},
        ],
        "tags": ["fundamentals", "scope"],
        "gotchas": ["`var` in loops shares one binding — use `let` for per-iteration closures."],
        "follow_ups": ["Why does `let` fix the classic loop-closure bug?"],
    },
    {
        "slug": "js-event-loop",
        "question": "Explain the event loop and the difference between microtasks and macrotasks.",
        "difficulty": "HARD",
        "tldr": "The event loop runs the call stack, then drains all microtasks (Promises), then one macrotask (timers), and repeats.",
        "explanation": "After each macrotask and once the stack is empty, the engine drains the entire microtask queue (Promise callbacks, queueMicrotask) before rendering or running the next macrotask (setTimeout, I/O). This is why a Promise callback runs before a setTimeout(0) scheduled earlier.",
        "code_examples": [
            {"language": "javascript", "label": "Ordering",
             "code": "console.log('A');\nsetTimeout(() => console.log('B'), 0);\nPromise.resolve().then(() => console.log('C'));\nconsole.log('D');\n// A D C B"},
        ],
        "tags": ["async", "internals"],
        "gotchas": ["Microtasks always drain fully before the next macrotask."],
        "follow_ups": ["Where does `await` fit?", "What is starvation by microtasks?"],
    },
]

QUESTIONS += [
    {
        "slug": "js-hoisting",
        "question": "What is hoisting in JavaScript, and how does it differ between var, let/const, and function declarations?",
        "difficulty": "EASY",
        "tldr": "Hoisting moves declarations to the top of their scope; var initializes to undefined, function declarations are fully hoisted, and let/const are hoisted but stay in the temporal dead zone until initialized.",
        "explanation": "During the compilation phase the engine registers all declarations in their scope before any code runs. `var` declarations are hoisted and initialized to `undefined`, so reading them early yields `undefined` rather than an error. Function declarations are hoisted with their full body so they can be called before their textual position, while `let` and `const` are hoisted but remain uninitialized in the temporal dead zone, throwing a ReferenceError if accessed early.",
        "code_examples": [
            {"language": "javascript", "label": "Hoisting behaviour by declaration type",
             "code": "console.log(a); // undefined (var hoisted, initialized to undefined)\nvar a = 1;\n\nfoo(); // \"hi\" (function declaration fully hoisted)\nfunction foo() { console.log(\"hi\"); }\n\nconsole.log(b); // ReferenceError (TDZ)\nlet b = 2;"},
        ],
        "tags": ["hoisting", "scope"],
        "gotchas": [
            "Function expressions and arrow functions assigned to var are NOT callable before the assignment line because only the var binding is hoisted (as undefined).",
            "let/const are technically hoisted too — the TDZ is not the same as 'not hoisted'.",
        ],
        "follow_ups": ["Why does accessing a let variable before declaration throw instead of returning undefined?", "What is the difference between a hoisted function declaration and a function expression?"],
    },
    {
        "slug": "js-this-binding",
        "question": "How is the value of `this` determined in JavaScript, and how do call, apply, and bind affect it?",
        "difficulty": "MEDIUM",
        "tldr": "`this` is set by how a function is called: default/global, implicit (the object before the dot), explicit (call/apply/bind), or new binding — while arrow functions inherit `this` lexically.",
        "explanation": "For ordinary functions `this` is resolved at call time using four rules in precedence order: `new` binding, explicit binding via call/apply/bind, implicit binding from the receiving object, then the default (global object or undefined in strict mode). `call` and `apply` invoke immediately with an explicit `this` (call takes comma-separated args, apply takes an array), while `bind` returns a new function permanently bound to the given `this`. Arrow functions ignore all of these and capture `this` from their enclosing lexical scope.",
        "code_examples": [
            {"language": "javascript", "label": "call vs apply vs bind",
             "code": "const obj = { x: 10, get() { return this.x; } };\nconst loose = obj.get;\nconsole.log(loose());            // undefined (lost binding)\nconsole.log(loose.call(obj));    // 10\nconsole.log(loose.apply(obj));   // 10\nconst bound = loose.bind(obj);\nconsole.log(bound());            // 10"},
        ],
        "tags": ["this", "binding"],
        "gotchas": [
            "Passing an object method as a callback loses its implicit `this` binding unless you bind it.",
            "bind cannot be overridden by a later call/apply — the bound `this` wins.",
        ],
        "follow_ups": ["Why can't you use bind to change `this` inside an arrow function?", "What does `this` resolve to in a plain function call under strict mode?"],
    },
    {
        "slug": "js-prototypal-inheritance",
        "question": "Explain prototypes and prototypal inheritance in JavaScript.",
        "difficulty": "MEDIUM",
        "tldr": "Every object has an internal [[Prototype]] link forming a chain; property lookups walk up that chain, which is how JavaScript implements inheritance.",
        "explanation": "Each object has a hidden `[[Prototype]]` reference (accessible via `Object.getPrototypeOf` or the legacy `__proto__`) pointing to another object. When you read a property the engine searches the object, then its prototype, then that prototype's prototype, until it finds the property or reaches `null`. Functions have a `prototype` property whose object becomes the `[[Prototype]]` of instances created with `new`, which is the mechanism behind constructor- and class-based inheritance.",
        "code_examples": [
            {"language": "javascript", "label": "Setting up a prototype chain",
             "code": "function Animal(name) { this.name = name; }\nAnimal.prototype.speak = function () { return this.name + \" makes a sound\"; };\n\nfunction Dog(name) { Animal.call(this, name); }\nDog.prototype = Object.create(Animal.prototype);\nDog.prototype.constructor = Dog;\n\nconst d = new Dog(\"Rex\");\nconsole.log(d.speak()); // \"Rex makes a sound\" (found up the chain)"},
        ],
        "tags": ["prototypes", "inheritance"],
        "gotchas": [
            "Reassigning Constructor.prototype after instances exist does not retroactively change those instances.",
            "Forgetting to reset the constructor property after Object.create leaves it pointing at the parent.",
        ],
        "follow_ups": ["How do ES6 classes relate to the prototype chain under the hood?", "What is the difference between __proto__ and the prototype property?"],
    },
    {
        "slug": "js-equality-operators",
        "question": "What is the difference between == and === in JavaScript?",
        "difficulty": "EASY",
        "tldr": "=== compares value and type without coercion, while == performs type coercion before comparing, which can produce surprising results.",
        "explanation": "The strict equality operator `===` returns true only when operands share the same type and value, with no conversion. The loose equality operator `==` applies the abstract equality algorithm, coercing operands toward a common type (typically number) before comparing. Because coercion rules are non-obvious, most style guides recommend `===` except for the deliberate `== null` check that matches both null and undefined.",
        "code_examples": [
            {"language": "javascript", "label": "Loose vs strict equality",
             "code": "console.log(0 == \"\");        // true  (coercion)\nconsole.log(0 === \"\");       // false\nconsole.log(null == undefined); // true\nconsole.log(null === undefined);// false\nconsole.log(NaN === NaN);    // false (use Number.isNaN)"},
        ],
        "tags": ["equality", "coercion"],
        "gotchas": [
            "NaN is never equal to anything, including itself, under either operator.",
            "`[] == ![]` is true because of multiple coercion steps — a classic trap.",
        ],
        "follow_ups": ["When is using == intentionally acceptable?", "How does Object.is differ from === for NaN and -0?"],
    },
    {
        "slug": "js-type-coercion",
        "question": "How does type coercion work in JavaScript, and what are common pitfalls?",
        "difficulty": "MEDIUM",
        "tldr": "JavaScript automatically converts values between types in many operations, with rules that differ for + (string-biased) versus other operators and comparisons (number-biased).",
        "explanation": "Coercion converts a value to a primitive of another type, either implicitly (during operations) or explicitly (via String, Number, Boolean). The `+` operator favors string concatenation when either operand is a string, while other arithmetic and relational operators coerce toward numbers. Objects are coerced via `Symbol.toPrimitive`, `valueOf`, and `toString`, which explains odd results like `[] + {}` producing `\"[object Object]\"`.",
        "code_examples": [
            {"language": "javascript", "label": "Implicit coercion examples",
             "code": "console.log(1 + \"2\");    // \"12\"  (+ prefers string)\nconsole.log(\"5\" - 2);    // 3     (- forces number)\nconsole.log(true + 1);   // 2\nconsole.log([] + []);    // \"\"    (both toString to \"\")\nconsole.log(Number(\"\")); // 0"},
        ],
        "tags": ["coercion", "types"],
        "gotchas": [
            "`+` is overloaded: with any string operand it concatenates, otherwise it adds numerically.",
            "Empty string and empty array both coerce to 0 with Number(), but to falsy/truthy differently in boolean contexts.",
        ],
        "follow_ups": ["What is the order of methods consulted when coercing an object to a primitive?", "Why does Number([1,2]) return NaN but Number([1]) return 1?"],
    },
    {
        "slug": "js-promises",
        "question": "What is a Promise, and what are its states and core methods?",
        "difficulty": "MEDIUM",
        "tldr": "A Promise represents the eventual result of an async operation, moving once from pending to either fulfilled or rejected, with then/catch/finally to react.",
        "explanation": "A Promise is an object representing a value that may not be available yet. It starts pending and settles exactly once to fulfilled (with a value) or rejected (with a reason); after settling it is immutable. You consume it with `then` for fulfillment, `catch` for errors, and `finally` for cleanup, and combinators like `Promise.all`, `allSettled`, `race`, and `any` coordinate multiple promises.",
        "code_examples": [
            {"language": "javascript", "label": "Promise states and chaining",
             "code": "const p = new Promise((resolve, reject) => {\n  setTimeout(() => resolve(42), 100);\n});\n\np.then(v => v * 2)\n .then(v => console.log(v)) // 84\n .catch(err => console.error(err))\n .finally(() => console.log(\"done\"));\n\nPromise.all([p, Promise.resolve(1)]).then(console.log); // [42, 1]"},
        ],
        "tags": ["promises", "async"],
        "gotchas": [
            "Promise.all rejects as soon as any input rejects; use Promise.allSettled to wait for every outcome.",
            "Returning a value vs returning a promise from then both chain, but forgetting to return breaks the chain's data flow.",
        ],
        "follow_ups": ["How does Promise.race differ from Promise.any?", "What happens to an unhandled rejected promise?"],
    },
    {
        "slug": "js-async-await",
        "question": "How does async/await work, and how does it relate to Promises?",
        "difficulty": "MEDIUM",
        "tldr": "async/await is syntactic sugar over Promises: an async function always returns a Promise, and await pauses its execution until the awaited Promise settles.",
        "explanation": "An `async` function implicitly wraps its return value in a resolved Promise and its thrown errors in a rejected Promise. The `await` operator suspends the async function until the awaited value settles, resuming with the fulfilled value or throwing the rejection reason, which you handle with try/catch. Crucially, awaiting does not block the main thread — control returns to the event loop while the awaited promise is pending.",
        "code_examples": [
            {"language": "javascript", "label": "async/await with error handling and parallelism",
             "code": "async function getUser(id) {\n  try {\n    const res = await fetch(`/users/${id}`);\n    const data = await res.json();\n    return data;\n  } catch (err) {\n    console.error(\"failed\", err);\n    throw err;\n  }\n}\n\n// Run in parallel instead of sequentially:\nconst [a, b] = await Promise.all([getUser(1), getUser(2)]);"},
        ],
        "tags": ["async", "promises"],
        "gotchas": [
            "Awaiting promises sequentially in a loop is often slower than collecting them and using Promise.all.",
            "A rejected awaited promise throws synchronously inside the function, so it needs try/catch, not .catch.",
        ],
        "follow_ups": ["How would you run async tasks concurrently while still awaiting all results?", "What does an async function return if it has no explicit return statement?"],
    },
    {
        "slug": "js-debounce-vs-throttle",
        "question": "What is the difference between debounce and throttle?",
        "difficulty": "MEDIUM",
        "tldr": "Debounce delays execution until activity stops for a set quiet period, while throttle guarantees execution at most once per fixed interval during continuous activity.",
        "explanation": "Both limit how often a function runs in response to frequent events. Debounce resets a timer on every call and only fires after the events pause for the specified delay — ideal for search-as-you-type or resize-end handling. Throttle lets the function run at a steady maximum rate regardless of how many events arrive — ideal for scroll, drag, or mousemove handlers where you want regular updates.",
        "code_examples": [
            {"language": "javascript", "label": "Minimal debounce and throttle implementations",
             "code": "function debounce(fn, wait) {\n  let t;\n  return (...args) => {\n    clearTimeout(t);\n    t = setTimeout(() => fn(...args), wait);\n  };\n}\n\nfunction throttle(fn, interval) {\n  let last = 0;\n  return (...args) => {\n    const now = Date.now();\n    if (now - last >= interval) {\n      last = now;\n      fn(...args);\n    }\n  };\n}"},
        ],
        "tags": ["debounce", "throttle", "performance"],
        "gotchas": [
            "A debounced handler may never fire if events never stop arriving within the wait window.",
            "The leading vs trailing edge variant changes whether the first or last call in a burst runs.",
        ],
        "follow_ups": ["How would you add leading and trailing edge options to debounce?", "Which would you use for an autosave feature and why?"],
    },
    {
        "slug": "js-currying",
        "question": "What is currying in JavaScript, and why is it useful?",
        "difficulty": "MEDIUM",
        "tldr": "Currying transforms a function of multiple arguments into a sequence of functions each taking one argument, enabling partial application and reuse.",
        "explanation": "A curried function takes its arguments one at a time, returning a new function until all arguments are supplied, at which point it produces the result. This enables partial application — pre-filling some arguments to create specialized functions — and improves composability in functional pipelines. It is commonly implemented with closures that accumulate arguments.",
        "code_examples": [
            {"language": "javascript", "label": "Generic curry helper",
             "code": "const curry = (fn) =>\n  function curried(...args) {\n    return args.length >= fn.length\n      ? fn.apply(this, args)\n      : (...rest) => curried.apply(this, args.concat(rest));\n  };\n\nconst add = (a, b, c) => a + b + c;\nconst cadd = curry(add);\nconsole.log(cadd(1)(2)(3)); // 6\nconsole.log(cadd(1, 2)(3)); // 6"},
        ],
        "tags": ["currying", "functional"],
        "gotchas": [
            "fn.length ignores rest parameters and default parameters, so a generic curry breaks for variadic functions.",
            "Currying is not the same as partial application, though they are related.",
        ],
        "follow_ups": ["How does currying differ from partial application?", "How would currying interact with functions that use the rest operator?"],
    },
    {
        "slug": "js-esm-vs-commonjs",
        "question": "What are the differences between ES Modules and CommonJS?",
        "difficulty": "MEDIUM",
        "tldr": "ES Modules are statically analyzable, async, and use import/export with live bindings, while CommonJS is synchronous, dynamic, and uses require/module.exports with value copies.",
        "explanation": "CommonJS (Node's original system) loads modules synchronously at runtime via `require`, exporting through `module.exports`, and its exports are evaluated and resolved dynamically. ES Modules use `import`/`export` syntax that is statically analyzable, enabling tree-shaking, and they expose live read-only bindings rather than copied values. ESM is asynchronous and its imports are hoisted, whereas CommonJS executes top-to-bottom and `require` can be called conditionally anywhere.",
        "code_examples": [
            {"language": "javascript", "label": "CommonJS vs ESM syntax and semantics",
             "code": "// CommonJS\nconst fs = require(\"fs\");\nmodule.exports = { read };\n\n// ES Module\nimport fs from \"node:fs\";\nexport function read() {}\nexport default read;"},
        ],
        "tags": ["modules", "esm", "commonjs"],
        "gotchas": [
            "ESM imports are hoisted and statically resolved, so you cannot conditionally import at top level (use dynamic import()).",
            "CommonJS named imports are value copies taken at require time, while ESM named imports are live bindings.",
        ],
        "follow_ups": ["How do you dynamically import a module in ESM?", "Why does tree-shaking work with ESM but not reliably with CommonJS?"],
    },
    {
        "slug": "js-let-const-var-tdz",
        "question": "What are the differences between let, const, and var, and what is the temporal dead zone?",
        "difficulty": "EASY",
        "tldr": "var is function-scoped and hoisted as undefined, while let and const are block-scoped and live in the temporal dead zone until initialized; const additionally forbids reassignment.",
        "explanation": "`var` is function-scoped, can be redeclared, and is hoisted with an initial value of `undefined`. `let` and `const` are block-scoped and, although hoisted, remain in the temporal dead zone (TDZ) from the start of the block until their declaration executes, throwing if accessed early. `const` requires an initializer and prevents reassignment of the binding, though the referenced object's contents can still mutate.",
        "code_examples": [
            {"language": "javascript", "label": "Scope, TDZ, and const mutability",
             "code": "{\n  // console.log(x); // ReferenceError: x is in the TDZ\n  let x = 1;\n}\n\nconst obj = { a: 1 };\nobj.a = 2;        // allowed (mutation)\n// obj = {};      // TypeError (reassignment)\n\nfor (var i = 0; i < 3; i++) {}\nconsole.log(i);   // 3 (var leaks out of the loop block)"},
        ],
        "tags": ["let-const-var", "scope", "tdz"],
        "gotchas": [
            "const prevents reassignment, not mutation — const objects and arrays are still mutable.",
            "var declarations leak out of blocks like if/for because they are function-scoped, not block-scoped.",
        ],
        "follow_ups": ["How does block scoping of let fix the classic loop-closure problem?", "Can you declare a const without initializing it?"],
    },
    {
        "slug": "js-generators",
        "question": "What are generator functions in JavaScript and how do they work?",
        "difficulty": "HARD",
        "tldr": "Generators are functions that can pause and resume using yield, returning an iterator whose next() drives execution and can pass values back in.",
        "explanation": "Declared with `function*`, a generator returns an iterator object instead of running immediately. Each call to `next()` runs the body until the next `yield`, returning `{ value, done }` and suspending state until the following `next()`. Values can be passed back into the generator through `next(value)`, which becomes the result of the paused `yield` expression, enabling two-way communication, lazy sequences, and cooperative iteration.",
        "code_examples": [
            {"language": "javascript", "label": "Two-way communication with a generator",
             "code": "function* idGen() {\n  let id = 1;\n  while (true) {\n    const reset = yield id++;\n    if (reset) id = 1;\n  }\n}\n\nconst g = idGen();\nconsole.log(g.next().value);     // 1\nconsole.log(g.next().value);     // 2\nconsole.log(g.next(true).value); // 1 (value passed back in)"},
        ],
        "tags": ["generators", "iterators"],
        "gotchas": [
            "The value passed to the very first next() is discarded because there is no preceding yield to receive it.",
            "An infinite generator only produces values lazily; iterating it fully (e.g. spread) would hang.",
        ],
        "follow_ups": ["How can generators be used to implement async control flow?", "What does yield* do?"],
    },
    {
        "slug": "js-map-set-vs-object",
        "question": "When should you use Map and Set instead of plain objects and arrays?",
        "difficulty": "MEDIUM",
        "tldr": "Map allows any key type with insertion order and a size property, Set stores unique values, and both offer better performance and cleaner semantics than objects for frequent additions and lookups by arbitrary keys.",
        "explanation": "Plain objects only support string and symbol keys, inherit prototype properties, and have no built-in size. `Map` accepts keys of any type (including objects), preserves insertion order, exposes `.size`, and is optimized for frequent insertion and deletion. `Set` stores unique values with O(1) membership tests, making deduplication and membership checks far cleaner than array scanning.",
        "code_examples": [
            {"language": "javascript", "label": "Map with object keys and Set deduplication",
             "code": "const m = new Map();\nconst key = { id: 1 };\nm.set(key, \"value\");          // object as key\nconsole.log(m.get(key));       // \"value\"\nconsole.log(m.size);           // 1\n\nconst s = new Set([1, 1, 2, 3]);\nconsole.log([...s]);           // [1, 2, 3]\nconsole.log(s.has(2));         // true"},
        ],
        "tags": ["map", "set", "collections"],
        "gotchas": [
            "Map uses SameValueZero for key equality, so two distinct objects with identical contents are different keys.",
            "Objects coerce all keys to strings, so obj[1] and obj['1'] collide while Map keeps them distinct.",
        ],
        "follow_ups": ["What is the difference between Map and WeakMap?", "How does Set determine whether two values are duplicates?"],
    },
    {
        "slug": "js-immutability-spread",
        "question": "How do you write immutable updates in JavaScript using the spread operator?",
        "difficulty": "MEDIUM",
        "tldr": "The spread operator creates a new array or object copy with selected changes instead of mutating the original, supporting an immutable update style.",
        "explanation": "Immutability means never modifying existing data structures, instead producing new ones with the desired changes. The spread operator (`...`) copies enumerable elements or own enumerable properties into a fresh array or object, letting you append, override, or merge without mutation. This pattern is central to predictable state management (e.g. React/Redux) but only copies one level deep.",
        "code_examples": [
            {"language": "javascript", "label": "Immutable object and array updates",
             "code": "const state = { user: { name: \"Ann\" }, count: 1 };\nconst next = { ...state, count: state.count + 1 };\n\nconst arr = [1, 2, 3];\nconst added = [...arr, 4];        // [1,2,3,4], arr unchanged\n\nconst updated = { ...state, user: { ...state.user, name: \"Bob\" } };"},
        ],
        "tags": ["immutability", "spread"],
        "gotchas": [
            "Spread is a shallow copy — nested objects are shared by reference between the copy and the original.",
            "Object.freeze only freezes the top level, so nested objects remain mutable.",
        ],
        "follow_ups": ["How would you immutably update a deeply nested property?", "What is the difference between Object.freeze and a true deep freeze?"],
    },
    {
        "slug": "js-shallow-vs-deep-copy",
        "question": "What is the difference between a shallow copy and a deep copy, and how do you create each?",
        "difficulty": "MEDIUM",
        "tldr": "A shallow copy duplicates only the top level and shares nested references, while a deep copy recursively clones every level so no references are shared.",
        "explanation": "A shallow copy (via spread, `Object.assign`, or `Array.slice`) creates a new container but its nested objects still point to the originals, so mutating a nested value affects both. A deep copy clones the entire structure recursively, producing fully independent data. Modern environments provide `structuredClone` for deep copying, while `JSON.parse(JSON.stringify(x))` works only for JSON-safe data.",
        "code_examples": [
            {"language": "javascript", "label": "Shallow vs deep copy behaviour",
             "code": "const original = { a: 1, nested: { b: 2 } };\n\nconst shallow = { ...original };\nshallow.nested.b = 99;\nconsole.log(original.nested.b); // 99 (shared reference!)\n\nconst deep = structuredClone(original);\ndeep.nested.b = 7;\nconsole.log(original.nested.b); // 99 (independent)"},
        ],
        "tags": ["copy", "immutability"],
        "gotchas": [
            "JSON.parse(JSON.stringify(x)) drops functions, undefined, Symbols, and breaks Dates, Maps, and circular references.",
            "structuredClone cannot clone functions or DOM nodes and will throw.",
        ],
        "follow_ups": ["What are the limitations of using JSON for deep cloning?", "How does structuredClone handle circular references?"],
    },
    {
        "slug": "js-event-delegation",
        "question": "What is event delegation and why is it useful?",
        "difficulty": "MEDIUM",
        "tldr": "Event delegation attaches a single listener to a common ancestor and uses event bubbling to handle events from many child elements, including ones added later.",
        "explanation": "Because most DOM events bubble up from the target through its ancestors, you can place one listener on a parent and inspect `event.target` to determine which child triggered it. This reduces the number of listeners, improves performance for large or dynamic lists, and automatically handles elements added after the listener was attached. You typically use `closest()` to match the relevant child element.",
        "code_examples": [
            {"language": "javascript", "label": "Delegated click handler on a list",
             "code": "document.getElementById(\"list\").addEventListener(\"click\", (e) => {\n  const item = e.target.closest(\"li\");\n  if (!item) return;            // clicked outside any li\n  console.log(\"clicked\", item.dataset.id);\n});\n// New <li> elements added later are handled without new listeners."},
        ],
        "tags": ["dom", "events"],
        "gotchas": [
            "Some events (like focus, blur, and certain media events) do not bubble, so delegation fails for them — use focusin/focusout instead.",
            "Using event.target without closest() can match nested child elements rather than the intended item.",
        ],
        "follow_ups": ["What is the difference between event.target and event.currentTarget?", "How does the capturing phase differ from the bubbling phase?"],
    },
    {
        "slug": "js-closures-in-loops",
        "question": "Why do closures in loops capture the wrong value with var, and how do you fix it?",
        "difficulty": "MEDIUM",
        "tldr": "var is function-scoped so all loop closures share one variable that ends at its final value; using let creates a fresh block-scoped binding per iteration.",
        "explanation": "A closure captures a variable, not its value at creation time. With `var` the loop counter is a single function-scoped binding, so every closure created in the loop references the same variable, which holds its final value by the time the callbacks run. Using `let` gives each iteration its own block-scoped binding, so each closure captures the value from that specific iteration; alternatively an IIFE can snapshot the value.",
        "code_examples": [
            {"language": "javascript", "label": "var vs let capture in loops",
             "code": "for (var i = 0; i < 3; i++) {\n  setTimeout(() => console.log(\"var\", i), 0); // 3, 3, 3\n}\n\nfor (let j = 0; j < 3; j++) {\n  setTimeout(() => console.log(\"let\", j), 0); // 0, 1, 2\n}"},
        ],
        "tags": ["closures", "scope"],
        "gotchas": [
            "Closures capture the variable binding, not a snapshot of its value — a frequent source of confusion.",
            "let in a for loop creates a new binding each iteration, which is special-cased behaviour worth knowing.",
        ],
        "follow_ups": ["How would you fix this using an IIFE instead of let?", "Does the let fix also apply to for...of and forEach?"],
    },
    {
        "slug": "js-new-keyword",
        "question": "What does the `new` keyword do when calling a function?",
        "difficulty": "MEDIUM",
        "tldr": "`new` creates a fresh object linked to the constructor's prototype, binds `this` to it, runs the constructor, and returns that object unless the constructor returns its own object.",
        "explanation": "When you invoke a function with `new`, the engine creates a new empty object whose `[[Prototype]]` is set to the constructor's `prototype` property, then calls the function with `this` bound to that new object. If the constructor does not explicitly return an object, the newly created object is returned automatically. If it returns a non-object primitive, that return value is ignored and the new object is still returned.",
        "code_examples": [
            {"language": "javascript", "label": "The four steps of new",
             "code": "function Point(x, y) {\n  this.x = x;\n  this.y = y;\n}\n\nconst p = new Point(1, 2);\nconsole.log(p.x, p.y);                       // 1 2\nconsole.log(Object.getPrototypeOf(p) === Point.prototype); // true\n\nfunction Weird() { this.a = 1; return { a: 99 }; }\nconsole.log(new Weird().a);                  // 99 (object return wins)"},
        ],
        "tags": ["new", "constructors"],
        "gotchas": [
            "If the constructor returns an object, that object replaces the freshly created one; a returned primitive is ignored.",
            "Calling a constructor without new leaves `this` as undefined (strict) or the global object, often causing bugs.",
        ],
        "follow_ups": ["How can new.target be used to detect whether a function was called with new?", "How would you implement your own version of the new operator?"],
    },
    {
        "slug": "js-symbol",
        "question": "What is a Symbol in JavaScript and what is it used for?",
        "difficulty": "HARD",
        "tldr": "A Symbol is a unique, immutable primitive often used as a non-colliding object property key and to implement well-known protocols like iteration.",
        "explanation": "`Symbol()` creates a guaranteed-unique primitive value; even two symbols with the same description are not equal. Symbols are used as property keys that won't collide with other keys and are not exposed by normal enumeration like `for...in` or `Object.keys`. Well-known symbols such as `Symbol.iterator` and `Symbol.toPrimitive` let objects hook into built-in language behaviors, while `Symbol.for` creates/looks up shared symbols in a global registry.",
        "code_examples": [
            {"language": "javascript", "label": "Symbol as hidden key and iterator protocol",
             "code": "const id = Symbol(\"id\");\nconst user = { name: \"Ann\", [id]: 123 };\nconsole.log(Object.keys(user));        // [\"name\"] (symbol hidden)\nconsole.log(user[id]);                 // 123\n\nconst range = {\n  [Symbol.iterator]() {\n    let n = 0;\n    return { next: () => ({ value: n, done: n++ >= 3 }) };\n  }\n};\nconsole.log([...range]);               // [0, 1, 2]"},
        ],
        "tags": ["symbol", "primitives"],
        "gotchas": [
            "Symbol keys are skipped by Object.keys/for...in/JSON.stringify but retrievable via Object.getOwnPropertySymbols.",
            "Symbol() and Symbol.for() differ: the latter is registered globally and returns the same symbol for a given key.",
        ],
        "follow_ups": ["How does Symbol.iterator make an object iterable?", "What is the difference between Symbol() and Symbol.for()?"],
    },
    {
        "slug": "js-optional-chaining-nullish",
        "question": "What do optional chaining (?.) and nullish coalescing (??) do, and how do they differ from && and ||?",
        "difficulty": "EASY",
        "tldr": "Optional chaining short-circuits property access when a reference is null or undefined, and nullish coalescing supplies a default only for null or undefined rather than for any falsy value.",
        "explanation": "Optional chaining (`?.`) stops evaluating and returns `undefined` if the value before it is `null` or `undefined`, avoiding 'cannot read property of undefined' errors and working for properties, calls, and indexing. Nullish coalescing (`??`) returns its right-hand operand only when the left is `null` or `undefined`, unlike `||` which falls back for any falsy value such as `0`, `\"\"`, or `false`. Together they make handling optional and defaulted data concise and safe.",
        "code_examples": [
            {"language": "javascript", "label": "Optional chaining and nullish coalescing vs ||",
             "code": "const user = { profile: null };\nconsole.log(user.profile?.name);   // undefined (no error)\nconsole.log(user.getName?.());     // undefined (method may not exist)\n\nconst count = 0;\nconsole.log(count || 10);           // 10  (0 is falsy)\nconsole.log(count ?? 10);           // 0   (0 is not null/undefined)"},
        ],
        "tags": ["optional-chaining", "nullish"],
        "gotchas": [
            "?? treats 0, '', and false as valid values, whereas || would replace them with the default.",
            "You cannot mix ?? with && or || without parentheses — it is a syntax error.",
        ],
        "follow_ups": ["When would using || instead of ?? introduce a bug?", "Does optional chaining short-circuit the rest of the expression after a null?"],
    },
    {
        "slug": "js-array-map-filter-reduce",
        "question": "Explain map, filter, and reduce and when to use each.",
        "difficulty": "EASY",
        "tldr": "map transforms each element into a new array of the same length, filter selects elements matching a predicate, and reduce folds the array into a single accumulated value.",
        "explanation": "`map` applies a function to every element and returns a new array of equal length, leaving the original untouched. `filter` returns a new array containing only elements for which the predicate returns truthy. `reduce` iterates with an accumulator and a callback to combine all elements into one result — a sum, object, or even another array — making it the most general of the three.",
        "code_examples": [
            {"language": "javascript", "label": "map, filter, reduce in action",
             "code": "const nums = [1, 2, 3, 4];\n\nconst doubled = nums.map(n => n * 2);          // [2, 4, 6, 8]\nconst evens = nums.filter(n => n % 2 === 0);   // [2, 4]\nconst sum = nums.reduce((acc, n) => acc + n, 0); // 10"},
        ],
        "tags": ["arrays", "functional"],
        "gotchas": [
            "Calling reduce without an initial value on an empty array throws a TypeError.",
            "These methods return new arrays/values and do not mutate the source, unlike sort or splice.",
        ],
        "follow_ups": ["How would you implement map using reduce?", "Why should you always pass an initial accumulator to reduce?"],
    },
    {
        "slug": "js-microtask-vs-macrotask",
        "question": "What is the difference between microtasks and macrotasks in the event loop?",
        "difficulty": "HARD",
        "tldr": "Microtasks (promise callbacks, queueMicrotask) run to exhaustion immediately after the current task and before the next macrotask (timers, I/O, events), so they always take priority.",
        "explanation": "The event loop processes one macrotask (a task such as a setTimeout callback, I/O, or event handler) at a time. After each macrotask, and after the current synchronous run completes, the engine drains the entire microtask queue before rendering or picking up the next macrotask. Promise reactions (`then`/`catch`/`finally`) and `queueMicrotask` schedule microtasks, while `setTimeout` and `setInterval` schedule macrotasks — which is why promise callbacks fire before a zero-delay timer.",
        "code_examples": [
            {"language": "javascript", "label": "Microtask vs macrotask ordering",
             "code": "console.log(\"start\");\n\nsetTimeout(() => console.log(\"timeout\"), 0);   // macrotask\n\nPromise.resolve().then(() => console.log(\"promise\")); // microtask\n\nqueueMicrotask(() => console.log(\"microtask\"));\n\nconsole.log(\"end\");\n// Order: start, end, promise, microtask, timeout"},
        ],
        "tags": ["event-loop", "async", "microtask"],
        "gotchas": [
            "An infinite stream of microtasks can starve the macrotask queue and block rendering and timers entirely.",
            "Microtasks always drain completely before the next macrotask, so a promise chain finishes before any setTimeout(0).",
        ],
        "follow_ups": ["Why might a long promise chain delay a setTimeout callback?", "Where do node's process.nextTick callbacks fit relative to the microtask queue?"],
    },
]
