QUESTIONS = [
    {
        "slug": "next-app-router-vs-pages-router",
        "question": "What are the key differences between the App Router and the Pages Router in Next.js?",
        "difficulty": "EASY",
        "tldr": "The App Router (app/) uses React Server Components by default, file-based layouts, and colocated conventions like loading.tsx/error.tsx, while the Pages Router (pages/) is client-component-centric with getServerSideProps/getStaticProps data fetching.",
        "explanation": "The Pages Router lives in pages/ and routes each file to a URL, fetching data via getServerSideProps, getStaticProps, and getInitialProps. The App Router lives in app/, treats components as Server Components by default, and uses folder conventions (page.tsx, layout.tsx, loading.tsx, error.tsx) plus async/await data fetching directly in components. Both can coexist, but the App Router is the recommended default for new projects.",
        "code_examples": [
            {"language": "tsx", "label": "Data fetching in each router",
             "code": "// Pages Router: pages/posts/[id].tsx\nexport async function getServerSideProps({ params }) {\n  const post = await fetchPost(params.id)\n  return { props: { post } }\n}\n\n// App Router: app/posts/[id]/page.tsx\nexport default async function Post({ params }) {\n  const { id } = await params\n  const post = await fetchPost(id)\n  return <h1>{post.title}</h1>\n}"},
        ],
        "tags": ["routing", "architecture"],
        "gotchas": ["You can't use getServerSideProps/getStaticProps inside app/ — those APIs only work in pages/.", "Mixing both routers means a route conflict (same path in both) will throw a build error."],
        "follow_ups": ["How do you incrementally migrate from the Pages Router to the App Router?", "Why are params async (a Promise) in the App Router for Next 15?"],
    },
    {
        "slug": "next-server-vs-client-components",
        "question": "What is the difference between Server Components and Client Components in the App Router?",
        "difficulty": "EASY",
        "tldr": "Server Components render on the server (no JS shipped, can access backend resources directly), while Client Components run in the browser and can use state, effects, and event handlers.",
        "explanation": "In the App Router every component is a Server Component by default — it runs only on the server, ships zero JavaScript to the client, and can directly access databases, files, and secrets. To opt into interactivity (useState, useEffect, onClick, browser APIs) you add the 'use client' directive at the top of the file. A common pattern is to keep most of the tree as Server Components and push interactivity to small leaf Client Components.",
        "code_examples": [
            {"language": "tsx", "label": "Server vs Client component",
             "code": "// Server Component (default) — runs on server\nimport { db } from '@/lib/db'\nexport default async function Page() {\n  const users = await db.user.findMany()\n  return <UserList users={users} />\n}\n\n// Client Component — runs in browser\n'use client'\nimport { useState } from 'react'\nexport function Counter() {\n  const [n, setN] = useState(0)\n  return <button onClick={() => setN(n + 1)}>{n}</button>\n}"},
        ],
        "tags": ["rsc", "architecture"],
        "gotchas": ["Importing a server-only module (like a DB client) into a Client Component leaks it to the browser bundle or throws — use the 'server-only' package to guard.", "You cannot pass non-serializable props (functions, class instances) from a Server Component to a Client Component."],
        "follow_ups": ["How do you pass a Server Component as a child to a Client Component?", "What does the 'server-only' package do?"],
    },
    {
        "slug": "next-use-client-directive",
        "question": "What does the 'use client' directive do, and where does the client boundary apply?",
        "difficulty": "EASY",
        "tldr": "'use client' marks the boundary where the module graph switches to Client Components; every module imported from that file is also pulled into the client bundle.",
        "explanation": "Placing 'use client' at the top of a file declares that file — and everything it imports — as part of the client bundle. It defines a boundary: components above it in the tree stay on the server, but the marked component and its imported children become Client Components. You only need the directive once at the top of the boundary file, not in every nested client file.",
        "code_examples": [
            {"language": "tsx", "label": "Declaring a client boundary",
             "code": "'use client'\n\nimport { useState } from 'react'\nimport { Helper } from './helper' // Helper is now client too\n\nexport function Search() {\n  const [q, setQ] = useState('')\n  return <input value={q} onChange={(e) => setQ(e.target.value)} />\n}"},
        ],
        "tags": ["use-client", "rsc"],
        "gotchas": ["The directive must be the very first statement in the file, before any imports.", "Once inside a client boundary, you can't import a Server Component directly — you can only receive one via props/children."],
        "follow_ups": ["Does 'use client' mean the component only renders on the client?", "How can a Server Component be rendered inside a Client Component?"],
    },
    {
        "slug": "next-ssr-ssg-isr",
        "question": "Explain the difference between SSR, SSG, and ISR in Next.js.",
        "difficulty": "EASY",
        "tldr": "SSG builds HTML at build time, SSR renders per request, and ISR serves static pages that are revalidated (regenerated) in the background on a time or tag basis.",
        "explanation": "Static Site Generation (SSG) renders pages at build time and serves them as cached static HTML — fastest, but data is frozen at build. Server-Side Rendering (SSR) renders on every request, giving fresh data at the cost of latency. Incremental Static Regeneration (ISR) combines both: a static page is served instantly and re-generated in the background after a revalidate interval or on-demand via revalidatePath/revalidateTag.",
        "code_examples": [
            {"language": "tsx", "label": "Controlling rendering strategy via fetch",
             "code": "// SSG (default): fetch with no dynamic options is cached at build\nconst data = await fetch('https://api.example.com/posts')\n\n// SSR: opt out of caching for per-request rendering\nconst data = await fetch('https://api.example.com/posts', { cache: 'no-store' })\n\n// ISR: revalidate this page's data every 60 seconds\nconst data = await fetch('https://api.example.com/posts', { next: { revalidate: 60 } })"},
        ],
        "tags": ["rendering", "caching"],
        "gotchas": ["Using cookies(), headers(), or searchParams forces a route to be dynamically rendered (SSR), overriding static generation.", "ISR's revalidate is a minimum — the stale page is served until a background regeneration completes."],
        "follow_ups": ["How does on-demand ISR differ from time-based revalidation?", "What APIs cause a route to opt out of static rendering?"],
    },
    {
        "slug": "next-route-handlers",
        "question": "What are Route Handlers (route.ts) and how do they replace API routes?",
        "difficulty": "EASY",
        "tldr": "Route Handlers are functions exported per HTTP method (GET, POST, etc.) from a route.ts file in app/, using the Web Request/Response APIs to build API endpoints.",
        "explanation": "In the App Router, API endpoints are defined in route.ts (or route.js) files that export async functions named after HTTP methods. They use the standard Web Request and Response objects instead of the Pages Router's req/res. A folder can have either a page.tsx or a route.ts, not both, since both map to the same URL.",
        "code_examples": [
            {"language": "tsx", "label": "GET and POST route handlers",
             "code": "// app/api/users/route.ts\nimport { NextResponse } from 'next/server'\n\nexport async function GET(request: Request) {\n  const users = await db.user.findMany()\n  return NextResponse.json(users)\n}\n\nexport async function POST(request: Request) {\n  const body = await request.json()\n  const user = await db.user.create({ data: body })\n  return NextResponse.json(user, { status: 201 })\n}"},
        ],
        "tags": ["route-handlers", "api"],
        "gotchas": ["A GET route handler is statically cached by default in some versions unless it uses dynamic functions — opt out explicitly if you need fresh data.", "You can't have both page.tsx and route.ts in the same folder."],
        "follow_ups": ["How do you read query parameters in a route handler?", "How do you set the runtime (edge vs node) for a route handler?"],
    },
    {
        "slug": "next-dynamic-routes-params",
        "question": "How do dynamic routes and route params work in the App Router?",
        "difficulty": "EASY",
        "tldr": "Bracketed folder names like [id] create dynamic segments; the value is passed via the params prop, which in Next 15 is a Promise you must await.",
        "explanation": "A folder named [slug] creates a single dynamic segment, [...slug] a catch-all, and [[...slug]] an optional catch-all. The matched values are passed to page.tsx, layout.tsx, and route handlers through the params prop. In Next 15, params (and searchParams) are asynchronous and must be awaited before use.",
        "code_examples": [
            {"language": "tsx", "label": "Reading a dynamic param",
             "code": "// app/blog/[slug]/page.tsx\nexport default async function Page({\n  params,\n}: {\n  params: Promise<{ slug: string }>\n}) {\n  const { slug } = await params\n  return <h1>Post: {slug}</h1>\n}"},
        ],
        "tags": ["routing", "params"],
        "gotchas": ["In Next 15 params is a Promise — accessing it synchronously (without await) is deprecated and will break.", "Catch-all params are arrays, not strings, even for a single segment."],
        "follow_ups": ["What is the difference between [...slug] and [[...slug]]?", "How do you access searchParams in a page?"],
    },
    {
        "slug": "next-fetch-caching-revalidation",
        "question": "How does fetch caching and revalidation work in the App Router?",
        "difficulty": "MEDIUM",
        "tldr": "Next.js extends fetch with caching options: use cache: 'force-cache'/'no-store' and next: { revalidate, tags } to control whether results are cached, for how long, and how to invalidate them.",
        "explanation": "Next.js augments the native fetch with a Data Cache. The cache option controls storage ('force-cache' to cache, 'no-store' to always refetch), while next: { revalidate: N } sets a time-based stale window and next: { tags: [...] } associates results with cache tags for on-demand invalidation. In Next 15 fetch defaults to no-store unless you opt in, reversing the Next 14 default of force-cache.",
        "code_examples": [
            {"language": "tsx", "label": "fetch caching options",
             "code": "// Cache indefinitely until manually revalidated\nawait fetch(url, { cache: 'force-cache' })\n\n// Time-based revalidation: refetch at most every 3600s\nawait fetch(url, { next: { revalidate: 3600 } })\n\n// Tag-based: invalidate later with revalidateTag('posts')\nawait fetch(url, { next: { tags: ['posts'] } })"},
        ],
        "tags": ["caching", "data-fetching"],
        "gotchas": ["The default caching behavior changed between Next 14 (cached) and Next 15 (uncached) — don't assume the default.", "Only the extended fetch is auto-cached; calls via axios or DB clients need unstable_cache or 'use cache' to be cached."],
        "follow_ups": ["How do you cache a non-fetch data source like a database query?", "How does revalidateTag relate to fetch tags?"],
    },
    {
        "slug": "next-server-actions",
        "question": "What are Server Actions and how do you use them for mutations?",
        "difficulty": "MEDIUM",
        "tldr": "Server Actions are async functions marked with 'use server' that run on the server and can be invoked from forms or client components to perform mutations without writing a separate API route.",
        "explanation": "A Server Action is an async function annotated with 'use server' (either at the top of a file or inline). They can be passed directly to a form's action prop or called from event handlers in Client Components, letting you mutate data on the server with progressive enhancement and no manual fetch. After mutating, you typically call revalidatePath or revalidateTag to refresh cached UI.",
        "code_examples": [
            {"language": "tsx", "label": "Form-based Server Action",
             "code": "// app/actions.ts\n'use server'\nimport { revalidatePath } from 'next/cache'\n\nexport async function createTodo(formData: FormData) {\n  const title = formData.get('title') as string\n  await db.todo.create({ data: { title } })\n  revalidatePath('/todos')\n}"},
        ],
        "tags": ["server-actions", "mutations"],
        "gotchas": ["Server Actions are exposed as POST endpoints — always validate and authorize inputs, since they're callable by anyone.", "Inputs and return values must be serializable; you can't return a database connection or pass a function."],
        "follow_ups": ["How do you show pending/optimistic UI with useFormStatus and useOptimistic?", "How do you handle validation errors returned from a Server Action?"],
    },
    {
        "slug": "next-streaming-suspense",
        "question": "How do streaming and Suspense work for rendering in the App Router?",
        "difficulty": "MEDIUM",
        "tldr": "Wrapping slow Server Components in <Suspense> streams the rest of the page immediately and progressively flushes the suspended content with its fallback shown first.",
        "explanation": "The App Router uses React Suspense to stream HTML in chunks: the server sends ready UI immediately and streams in slower parts as their data resolves, displaying a fallback in the meantime. You can wrap any async Server Component in <Suspense fallback={...}> for granular streaming, and a loading.tsx file automatically wraps an entire route segment in Suspense.",
        "code_examples": [
            {"language": "tsx", "label": "Streaming a slow component with Suspense",
             "code": "import { Suspense } from 'react'\n\nasync function Reviews({ id }: { id: string }) {\n  const reviews = await getReviews(id) // slow\n  return <ul>{reviews.map((r) => <li key={r.id}>{r.text}</li>)}</ul>\n}\n\nexport default function Page({ params }: { params: { id: string } }) {\n  return (\n    <section>\n      <Suspense fallback={<p>Loading reviews…</p>}>\n        <Reviews id={params.id} />\n      </Suspense>\n    </section>\n  )\n}"},
        ],
        "tags": ["streaming", "suspense"],
        "gotchas": ["Calling a dynamic API like cookies() or headers() outside Suspense can opt the whole route into dynamic rendering and block streaming.", "Suspense only streams Server Components; data fetched in a Client useEffect won't benefit from server streaming."],
        "follow_ups": ["How does loading.tsx relate to manual Suspense boundaries?", "What is the relationship between streaming and Partial Prerendering?"],
    },
    {
        "slug": "next-generate-metadata",
        "question": "How do you generate dynamic page metadata with generateMetadata?",
        "difficulty": "MEDIUM",
        "tldr": "Export an async generateMetadata function from a layout or page to compute title, description, and Open Graph tags based on params or fetched data.",
        "explanation": "The Metadata API replaces manual <head> management. For static metadata you export a metadata object; for dynamic metadata that depends on route params or fetched data, you export an async generateMetadata function that returns a Metadata object. Next.js dedupes fetch calls, so requesting the same data in both generateMetadata and the page incurs only one network request.",
        "code_examples": [
            {"language": "tsx", "label": "Dynamic metadata generation",
             "code": "import type { Metadata } from 'next'\n\nexport async function generateMetadata({\n  params,\n}: {\n  params: Promise<{ id: string }>\n}): Promise<Metadata> {\n  const { id } = await params\n  const product = await getProduct(id)\n  return {\n    title: product.name,\n    description: product.summary,\n    openGraph: { images: [product.image] },\n  }\n}"},
        ],
        "tags": ["metadata", "seo"],
        "gotchas": ["You can't export both a static metadata object and generateMetadata from the same file.", "Metadata exports only work in Server Components — a file with 'use client' can't export them."],
        "follow_ups": ["How does Next dedupe fetches between generateMetadata and the page?", "How do you generate dynamic Open Graph images with opengraph-image.tsx?"],
    },
    {
        "slug": "next-middleware",
        "question": "What is Next.js Middleware and what are common use cases and limitations?",
        "difficulty": "MEDIUM",
        "tldr": "Middleware in middleware.ts runs before a request is completed, letting you rewrite, redirect, or modify headers/cookies for matched routes, traditionally on the Edge runtime.",
        "explanation": "Middleware executes before the cache and routing for matching requests, defined in a root-level middleware.ts exporting a middleware function and an optional config.matcher. It's ideal for authentication gating, redirects, A/B testing, geolocation, and rewriting URLs. It runs on the Edge runtime by default, so it can't use heavy Node-only APIs and should stay lightweight.",
        "code_examples": [
            {"language": "tsx", "label": "Auth-gating middleware with a matcher",
             "code": "// middleware.ts\nimport { NextRequest, NextResponse } from 'next/server'\n\nexport function middleware(request: NextRequest) {\n  const token = request.cookies.get('session')?.value\n  if (!token) {\n    return NextResponse.redirect(new URL('/login', request.url))\n  }\n  return NextResponse.next()\n}\n\nexport const config = {\n  matcher: ['/dashboard/:path*', '/account/:path*'],\n}"},
        ],
        "tags": ["middleware", "edge"],
        "gotchas": ["Middleware runs on every matched request including prefetches — keep it fast and avoid heavy work or DB calls.", "On the Edge runtime you can't use Node-specific APIs (fs, native crypto modules) unless you opt into the Node runtime."],
        "follow_ups": ["How do you configure which paths Middleware runs on?", "Why shouldn't you do full session validation (DB lookups) in Middleware?"],
    },
    {
        "slug": "next-generate-static-params",
        "question": "What does generateStaticParams do for dynamic routes?",
        "difficulty": "MEDIUM",
        "tldr": "generateStaticParams returns the list of param values to statically pre-render at build time for a dynamic route, the App Router equivalent of getStaticPaths.",
        "explanation": "For a dynamic segment like [slug], generateStaticParams runs at build time and returns an array of param objects telling Next which pages to statically generate. Combined with the route's dynamicParams setting, you control whether params not returned are rendered on demand or 404. It replaces the Pages Router's getStaticPaths.",
        "code_examples": [
            {"language": "tsx", "label": "Pre-rendering dynamic pages",
             "code": "// app/blog/[slug]/page.tsx\nexport async function generateStaticParams() {\n  const posts = await getPosts()\n  return posts.map((post) => ({ slug: post.slug }))\n}\n\nexport const dynamicParams = false // 404 for params not listed"},
        ],
        "tags": ["ssg", "routing"],
        "gotchas": ["Params not returned are still rendered on demand by default (dynamicParams = true); set it to false to 404 them instead.", "Returned param values must be strings, even for numeric IDs."],
        "follow_ups": ["What does setting dynamicParams to false change?", "How does generateStaticParams interact with ISR revalidation?"],
    },
    {
        "slug": "next-nested-layouts",
        "question": "How do layouts and nested layouts work in the App Router?",
        "difficulty": "MEDIUM",
        "tldr": "A layout.tsx wraps its segment and all child segments via the children prop, and nested layouts compose hierarchically while preserving state across navigation.",
        "explanation": "Each folder can define a layout.tsx that receives a children prop and wraps everything in that segment, including nested routes. Layouts nest automatically following the folder hierarchy, and crucially they do not re-render or lose state when navigating between sibling routes that share them. The root layout (app/layout.tsx) is required and must render the html and body tags.",
        "code_examples": [
            {"language": "tsx", "label": "Root and nested layouts",
             "code": "// app/layout.tsx (root, required)\nexport default function RootLayout({ children }: { children: React.ReactNode }) {\n  return (\n    <html lang=\"en\">\n      <body>{children}</body>\n    </html>\n  )\n}"},
        ],
        "tags": ["layouts", "routing"],
        "gotchas": ["Layouts persist and don't re-render on navigation between shared routes — don't rely on them to refetch per-page data.", "The root layout must include html and body; omitting them breaks the app."],
        "follow_ups": ["How does a template.tsx differ from a layout.tsx?", "How do you share data between a layout and its pages without prop drilling?"],
    },
    {
        "slug": "next-loading-error-files",
        "question": "What do the loading.tsx and error.tsx special files do?",
        "difficulty": "MEDIUM",
        "tldr": "loading.tsx provides an instant Suspense fallback for a route segment while it loads, and error.tsx is a Client Component error boundary that catches runtime errors in that segment.",
        "explanation": "loading.tsx automatically wraps a segment's page in a React Suspense boundary, showing its UI as a fallback during navigation or data fetching. error.tsx defines an error boundary for the segment — it must be a Client Component and receives the error plus a reset function to attempt recovery. There's also global-error.tsx for catching errors in the root layout.",
        "code_examples": [
            {"language": "tsx", "label": "loading and error special files",
             "code": "// app/dashboard/error.tsx\n'use client'\nexport default function Error({\n  error,\n  reset,\n}: {\n  error: Error & { digest?: string }\n  reset: () => void\n}) {\n  return (\n    <div>\n      <p>Something went wrong: {error.message}</p>\n      <button onClick={() => reset()}>Try again</button>\n    </div>\n  )\n}"},
        ],
        "tags": ["loading", "error-handling"],
        "gotchas": ["error.tsx must be a Client Component ('use client') — a Server Component error boundary won't work.", "error.tsx does not catch errors in the same segment's layout.tsx; use global-error.tsx or a parent boundary."],
        "follow_ups": ["What is global-error.tsx and when is it triggered?", "How do you handle 'not found' cases with not-found.tsx and notFound()?"],
    },
    {
        "slug": "next-revalidate-path-tag",
        "question": "How do revalidatePath and revalidateTag work for on-demand cache invalidation?",
        "difficulty": "MEDIUM",
        "tldr": "revalidatePath purges the cache for a specific route path and revalidateTag purges all cached fetches tagged with a given tag, both typically called from Server Actions or route handlers after a mutation.",
        "explanation": "On-demand revalidation lets you invalidate cached data immediately rather than waiting for a time-based interval. revalidatePath('/blog') clears the cached render and data for that route, while revalidateTag('posts') invalidates every fetch tagged with { next: { tags: ['posts'] } }. Both are called server-side, most commonly inside a Server Action after writing data.",
        "code_examples": [
            {"language": "tsx", "label": "On-demand revalidation in a Server Action",
             "code": "'use server'\nimport { revalidatePath, revalidateTag } from 'next/cache'\n\nexport async function publishPost(data: FormData) {\n  await db.post.create({ data: { title: data.get('title') } })\n  revalidatePath('/blog')\n  revalidateTag('posts')\n}"},
        ],
        "tags": ["caching", "revalidation"],
        "gotchas": ["revalidatePath invalidates the cache but doesn't refetch immediately — the next request triggers regeneration.", "revalidateTag only affects fetches that were explicitly tagged; untagged fetches are unaffected."],
        "follow_ups": ["How do you trigger revalidation from an external webhook?", "What's the difference between revalidatePath('/blog') and revalidatePath('/blog', 'layout')?"],
    },
    {
        "slug": "next-cookies-headers-server",
        "question": "How do you read cookies and headers in Server Components and what are the implications?",
        "difficulty": "MEDIUM",
        "tldr": "Use the cookies() and headers() functions from next/headers (awaited in Next 15) to read request data in Server Components, which forces the route into dynamic rendering.",
        "explanation": "next/headers exports cookies() and headers() for accessing the incoming request in Server Components and Server Actions. In Next 15 these are async and must be awaited. Reading them signals request-time data, so it opts the route out of static generation. You can set or delete cookies only in Server Actions or Route Handlers, not while rendering a Server Component.",
        "code_examples": [
            {"language": "tsx", "label": "Reading cookies and headers",
             "code": "import { cookies, headers } from 'next/headers'\n\nexport default async function Page() {\n  const cookieStore = await cookies()\n  const theme = cookieStore.get('theme')?.value\n\n  const headerList = await headers()\n  const ua = headerList.get('user-agent')\n\n  return <p>Theme: {theme} — UA: {ua}</p>\n}"},
        ],
        "tags": ["cookies", "server-components"],
        "gotchas": ["Calling cookies() or headers() makes the route dynamically rendered, disabling static optimization.", "You can't set cookies during render — mutating cookies is only allowed in Server Actions or Route Handlers."],
        "follow_ups": ["Why can't you set cookies while rendering a Server Component?", "How can you isolate dynamic data with Suspense to keep the rest of a page static?"],
    },
    {
        "slug": "next-data-fetching-patterns",
        "question": "What are the recommended data fetching patterns in the App Router (parallel vs sequential)?",
        "difficulty": "MEDIUM",
        "tldr": "Fetch directly in async Server Components, parallelize independent requests with Promise.all to avoid waterfalls, and rely on Next's request deduplication for repeated fetches.",
        "explanation": "The App Router encourages fetching data where it's used inside async Server Components. To avoid request waterfalls, kick off independent fetches in parallel (initiate the promises, then await with Promise.all) rather than awaiting them sequentially. Next.js automatically dedupes identical fetch requests within a single render pass.",
        "code_examples": [
            {"language": "tsx", "label": "Parallel vs sequential fetching",
             "code": "export default async function Page({ params }: { params: Promise<{ id: string }> }) {\n  const { id } = await params\n  const userPromise = getUser(id)\n  const statsPromise = getStats(id)\n  const [user, stats] = await Promise.all([userPromise, statsPromise])\n  return <Profile user={user} stats={stats} />\n}"},
        ],
        "tags": ["data-fetching", "performance"],
        "gotchas": ["Awaiting dependent fetches sequentially creates waterfalls — only chain when one request truly needs another's result.", "Deduplication applies to the extended fetch within one render; it doesn't cache across separate requests unless you also set caching options."],
        "follow_ups": ["How does React's cache() function help dedupe non-fetch data sources?", "How do you preload data to start a fetch earlier in the tree?"],
    },
    {
        "slug": "next-image-optimization",
        "question": "How does the next/image component optimize images?",
        "difficulty": "MEDIUM",
        "tldr": "next/image automatically resizes, optimizes, and serves images in modern formats with lazy loading, while preventing layout shift via required width/height or fill.",
        "explanation": "The Image component optimizes images on demand — resizing for the device, converting to modern formats like WebP/AVIF, and lazy-loading by default. You must supply width and height (or use fill with a positioned parent) so it can reserve space and avoid Cumulative Layout Shift. For above-the-fold images you set priority to disable lazy loading, and remote image hosts must be allowlisted in next.config.",
        "code_examples": [
            {"language": "tsx", "label": "Optimized image with remote host config",
             "code": "import Image from 'next/image'\n\nexport default function Hero() {\n  return (\n    <Image\n      src=\"https://cdn.example.com/hero.jpg\"\n      alt=\"Hero\"\n      width={1200}\n      height={600}\n      priority\n    />\n  )\n}"},
        ],
        "tags": ["image", "performance"],
        "gotchas": ["Remote image URLs must be allowlisted via images.remotePatterns or they throw at runtime.", "Using fill requires the parent element to have position: relative and a defined size, or the image collapses."],
        "follow_ups": ["When should you use priority versus lazy loading?", "How do placeholder='blur' and blurDataURL improve perceived loading?"],
    },
    {
        "slug": "next-public-env-vars",
        "question": "How do environment variables and the NEXT_PUBLIC_ prefix work in Next.js?",
        "difficulty": "EASY",
        "tldr": "Variables without the NEXT_PUBLIC_ prefix stay server-only; only variables prefixed with NEXT_PUBLIC_ are inlined into the client bundle and exposed to the browser.",
        "explanation": "Next.js reads env vars from .env files and process.env. By default they're available only on the server (Server Components, Route Handlers, Server Actions). To expose a value to the browser you must prefix it with NEXT_PUBLIC_, which inlines it into the client bundle at build time. Because NEXT_PUBLIC_ values are public, never put secrets behind that prefix.",
        "code_examples": [
            {"language": "tsx", "label": "Server-only vs public env vars",
             "code": "// .env\n// DATABASE_URL=postgres://...        (server-only)\n// NEXT_PUBLIC_ANALYTICS_ID=UA-123     (exposed to browser)\n\nconst db = connect(process.env.DATABASE_URL) // server\n\n'use client'\nfunction Analytics() {\n  init(process.env.NEXT_PUBLIC_ANALYTICS_ID) // works in browser\n  return null\n}"},
        ],
        "tags": ["env-vars", "configuration"],
        "gotchas": ["NEXT_PUBLIC_ values are inlined at build time, so changing them requires a rebuild, not just a restart.", "Reading a non-prefixed secret in a Client Component yields undefined and silently breaks logic."],
        "follow_ups": ["Why are NEXT_PUBLIC_ variables baked in at build time rather than read at runtime?", "How do you handle runtime configuration that can't be known at build time?"],
    },
    {
        "slug": "next-parallel-intercepting-routes",
        "question": "What are parallel routes and intercepting routes, and when would you use them?",
        "difficulty": "HARD",
        "tldr": "Parallel routes (@slot folders) render multiple pages in the same layout simultaneously, and intercepting routes ((.) conventions) load a route in the current context — like a modal — instead of a full navigation.",
        "explanation": "Parallel routes use named slots (folders prefixed with @) that a layout receives as separate props alongside children, enabling independently-rendered sections with their own loading/error states. Intercepting routes use conventions like (.), (..), or (...) to intercept a path and render it within the current layout — the canonical use case being a modal that shows a route's content on soft navigation but the full page on hard refresh.",
        "code_examples": [
            {"language": "tsx", "label": "Parallel slots in a layout",
             "code": "// app/layout.tsx with parallel slots\nexport default function Layout({\n  children,\n  team,\n  analytics,\n}: {\n  children: React.ReactNode\n  team: React.ReactNode\n  analytics: React.ReactNode\n}) {\n  return (\n    <>\n      {children}\n      <aside>{team}</aside>\n      <section>{analytics}</section>\n    </>\n  )\n}"},
        ],
        "tags": ["parallel-routes", "intercepting-routes"],
        "gotchas": ["Each parallel slot needs a default.tsx or it errors on hard navigation/refresh when a slot has no matching segment.", "Intercepting-route matchers ((.) vs (..)) are relative to the route segment level, not the file system."],
        "follow_ups": ["Why does an unmatched parallel slot require a default.tsx?", "How do you combine intercepting and parallel routes to build a shareable modal?"],
    },
    {
        "slug": "next-edge-vs-node-runtime",
        "question": "What is the difference between the Edge and Node.js runtimes in Next.js?",
        "difficulty": "HARD",
        "tldr": "The Node.js runtime offers the full Node API and runs in serverless/server environments, while the Edge runtime is a lightweight V8-based environment with Web APIs, faster cold starts, and global distribution but limited API support.",
        "explanation": "Next.js can run server code in two runtimes selected via the segment-level runtime export. The Node.js runtime (default for most app code) supports the full Node standard library and npm packages but has heavier cold starts. The Edge runtime runs on a minimal V8 isolate with only Web-standard APIs — no fs, limited Node built-ins — giving very low latency and global edge deployment, ideal for middleware and simple handlers.",
        "code_examples": [
            {"language": "tsx", "label": "Selecting the runtime per segment",
             "code": "// Opt a route handler or page into the Edge runtime\nexport const runtime = 'edge'\n\nexport async function GET() {\n  return Response.json({ ok: true })\n}\n\n// Default (Node.js) — can use fs, Buffer, full npm packages:\n// export const runtime = 'nodejs'"},
        ],
        "tags": ["edge", "runtime"],
        "gotchas": ["Many npm packages relying on Node built-ins (fs, net, native addons) won't work in the Edge runtime and fail at build/runtime.", "Edge functions have stricter limits on bundle size and execution time than Node serverless functions."],
        "follow_ups": ["Which runtime does Middleware use, and why?", "How do you decide between Edge and Node for a data-heavy API route?"],
    },
    {
        "slug": "next-partial-prerendering",
        "question": "What is Partial Prerendering (PPR) and how does it combine static and dynamic rendering?",
        "difficulty": "HARD",
        "tldr": "Partial Prerendering serves a static prerendered shell instantly from the edge while streaming in dynamic parts (wrapped in Suspense) within the same page on the same request.",
        "explanation": "PPR breaks the all-or-nothing choice between static and dynamic rendering at the route level. Next prerenders a static shell at build time and marks the dynamic holes — any subtree using dynamic APIs (cookies, headers, uncached fetch) wrapped in a Suspense boundary — to be streamed in at request time. The user gets an instant static response with dynamic content filling in. It's an experimental/incrementally-adopted feature enabled via config.",
        "code_examples": [
            {"language": "tsx", "label": "Enabling PPR with a dynamic hole",
             "code": "// next.config.js: experimental: { ppr: 'incremental' }\nimport { Suspense } from 'react'\nexport const experimental_ppr = true\n\nexport default function Page() {\n  return (\n    <main>\n      <StaticHeader /> {/* prerendered shell */}\n      <Suspense fallback={<Skeleton />}>\n        <DynamicCart /> {/* uses cookies(), streamed at request time */}\n      </Suspense>\n    </main>\n  )\n}"},
        ],
        "tags": ["ppr", "rendering"],
        "gotchas": ["Dynamic content must be wrapped in a Suspense boundary or PPR can't isolate the static shell from the dynamic hole.", "PPR is experimental and evolving — APIs and config flags differ across Next 14/15 versions."],
        "follow_ups": ["How does PPR relate to Next 16's Cache Components and the 'use cache' directive?", "What happens to the static shell if a dynamic component isn't wrapped in Suspense?"],
    },
    {
        "slug": "next-not-found-redirect",
        "question": "How do the notFound() and redirect() functions work in Server Components and Actions?",
        "difficulty": "HARD",
        "tldr": "notFound() throws a control-flow error that renders the nearest not-found.tsx, and redirect() throws to issue an HTTP redirect — both work by throwing, so code after them never runs.",
        "explanation": "next/navigation provides notFound() and redirect() (plus permanentRedirect) for server-side navigation control. They work by throwing a special error caught by Next's framework: notFound() renders the closest not-found.tsx boundary, while redirect() sends the user to another URL. Because they throw, any code placed after them is unreachable, and you should not wrap them in a try/catch that swallows the thrown control-flow error.",
        "code_examples": [
            {"language": "tsx", "label": "notFound and redirect control flow",
             "code": "import { notFound, redirect } from 'next/navigation'\n\nexport default async function Page({ params }: { params: Promise<{ id: string }> }) {\n  const { id } = await params\n  const post = await getPost(id)\n  if (!post) notFound() // renders not-found.tsx\n  if (post.draft) redirect('/drafts')\n  return <Article post={post} />\n}"},
        ],
        "tags": ["navigation", "error-handling"],
        "gotchas": ["Both functions work by throwing — a surrounding try/catch can accidentally swallow the redirect/notFound signal and break it.", "redirect() defaults to a temporary (307/303) redirect; use permanentRedirect() for a permanent (308) one."],
        "follow_ups": ["Why should redirect() not be called inside a try/catch block?", "What's the difference between redirect() and permanentRedirect()?"],
    },
    {
        "slug": "next-server-only-client-composition",
        "question": "How do you compose Server and Client Components, and how do you pass server data across the client boundary?",
        "difficulty": "HARD",
        "tldr": "Server Components can render Client Components and pass serializable props, and you can slot a Server Component into a Client Component via the children prop so it still renders on the server.",
        "explanation": "A Server Component can import and render a Client Component, passing serializable props. The inverse — importing a Server Component into a Client Component — isn't allowed, but you can pass a Server Component as children (or any prop) to a Client Component; the server renders it and the client just places the resulting tree in a slot. This lets you keep data fetching and secrets on the server while wrapping content in interactive client shells.",
        "code_examples": [
            {"language": "tsx", "label": "Slotting a Server Component into a Client Component",
             "code": "'use client'\nimport { useState } from 'react'\nexport function Tabs({ children }: { children: React.ReactNode }) {\n  const [open, setOpen] = useState(true)\n  return open ? <div>{children}</div> : <button onClick={() => setOpen(true)}>Show</button>\n}\n\n// Server Component composes them — ServerData stays on the server\n// <Tabs><ServerData /></Tabs>"},
        ],
        "tags": ["rsc", "composition"],
        "gotchas": ["You cannot import a Server Component into a 'use client' file — pass it as children/props instead.", "Props crossing the boundary must be serializable; passing a function (other than a Server Action) or class instance throws."],
        "follow_ups": ["Why does passing a Server Component as children keep it rendering on the server?", "How do Server Actions cross the boundary despite being functions?"],
    },
]
