QUESTIONS = [
    {
        "slug": "node-event-loop-phases",
        "question": "What are the phases of the Node.js event loop, and in what order do they execute?",
        "difficulty": "MEDIUM",
        "tldr": "libuv's event loop runs in ordered phases: timers, pending callbacks, idle/prepare, poll, check, and close callbacks. Each phase has a FIFO callback queue, and microtasks (process.nextTick + Promises) drain between every phase.",
        "explanation": "The event loop, implemented by libuv, cycles through fixed phases. The timers phase runs expired setTimeout/setInterval callbacks; the poll phase retrieves I/O events and executes their callbacks; the check phase runs setImmediate callbacks; and close callbacks handle things like socket 'close' events. Between each phase (and between each callback), Node drains the process.nextTick queue and then the microtask/Promise queue.",
        "code_examples": [
            {"language": "javascript", "label": "timer vs immediate ordering",
             "code": "const fs = require('fs');\n\nsetTimeout(() => console.log('timeout'), 0);\nsetImmediate(() => console.log('immediate'));\n\nfs.readFile(__filename, () => {\n  // Inside an I/O callback, 'immediate' runs before 'timeout'.\n  setTimeout(() => console.log('timeout inside IO'), 0);\n  setImmediate(() => console.log('immediate inside IO'));\n});"},
        ],
        "tags": ["event-loop", "libuv"],
        "gotchas": ["At the top level, setTimeout(fn,0) vs setImmediate ordering is non-deterministic; inside an I/O callback setImmediate always wins.", "A flood of process.nextTick callbacks can starve the loop and prevent I/O from ever progressing."],
        "follow_ups": ["Where do Promise callbacks run relative to process.nextTick?", "What is the poll phase's timeout calculated from?"],
    },
    {
        "slug": "node-nexttick-vs-setimmediate",
        "question": "What is the difference between process.nextTick() and setImmediate()?",
        "difficulty": "MEDIUM",
        "tldr": "process.nextTick() callbacks run immediately after the current operation completes, before the event loop continues (and before Promise microtasks). setImmediate() callbacks run in the event loop's 'check' phase, after the poll phase.",
        "explanation": "Despite the names, process.nextTick fires sooner than setImmediate. The nextTick queue is drained completely before the event loop is allowed to proceed to its next phase, making it a microtask-like mechanism that runs even before the Promise queue. setImmediate schedules a callback for the dedicated check phase of the next loop iteration, so it always yields to I/O.",
        "code_examples": [
            {"language": "javascript", "label": "ordering of nextTick, promise, immediate",
             "code": "setImmediate(() => console.log('immediate'));\nprocess.nextTick(() => console.log('nextTick'));\nPromise.resolve().then(() => console.log('promise'));\n\nconsole.log('sync');\n// Output: sync, nextTick, promise, immediate"},
        ],
        "tags": ["event-loop", "scheduling"],
        "gotchas": ["Recursively calling process.nextTick can starve the event loop and block I/O indefinitely.", "Naming is misleading: setImmediate is NOT immediate, and nextTick does NOT wait for the next loop tick."],
        "follow_ups": ["When would you deliberately prefer setImmediate over process.nextTick?", "How does the Promise microtask queue interleave with the nextTick queue?"],
    },
    {
        "slug": "node-stream-types",
        "question": "What are the four fundamental stream types in Node.js?",
        "difficulty": "EASY",
        "tldr": "Readable (source you read from), Writable (sink you write to), Duplex (both, with independent read/write sides like a TCP socket), and Transform (a Duplex whose output is computed from its input, like zlib.createGzip()).",
        "explanation": "All streams are instances of EventEmitter. Readable and Writable handle one direction of flow; Duplex combines both into independent channels; Transform is a special Duplex where the write and read sides are connected by a _transform function. Streams let you process data incrementally instead of buffering everything in memory.",
        "code_examples": [
            {"language": "javascript", "label": "a Transform stream",
             "code": "const { Transform } = require('stream');\n\nconst upper = new Transform({\n  transform(chunk, encoding, callback) {\n    this.push(chunk.toString().toUpperCase());\n    callback();\n  }\n});\n\nprocess.stdin.pipe(upper).pipe(process.stdout);"},
        ],
        "tags": ["streams"],
        "gotchas": ["Forgetting to call the transform callback stalls the stream because backpressure never releases.", "Object-mode streams pass arbitrary JS values instead of Buffers/strings; mixing modes causes errors."],
        "follow_ups": ["What is the difference between flowing and paused mode for Readable streams?", "How does a Transform stream differ from a plain Duplex?"],
    },
    {
        "slug": "node-backpressure",
        "question": "What is backpressure in Node.js streams and how do you handle it correctly?",
        "difficulty": "HARD",
        "tldr": "Backpressure occurs when a Writable can't consume data as fast as a Readable produces it. writable.write() returns false when its internal buffer exceeds highWaterMark; you must pause the source and wait for the 'drain' event. pipe() and pipeline() handle this for you.",
        "explanation": "If you ignore the false return value of write() and keep writing, data accumulates in memory unbounded, causing memory bloat and potential crashes. The correct manual pattern is to stop reading when write() returns false and resume on 'drain'. In practice you should prefer stream.pipeline() or pipe(), which manage backpressure and propagate errors automatically.",
        "code_examples": [
            {"language": "javascript", "label": "pipeline handles it automatically",
             "code": "const { pipeline } = require('stream');\nconst fs = require('fs');\nconst zlib = require('zlib');\n\npipeline(\n  fs.createReadStream('input.txt'),\n  zlib.createGzip(),\n  fs.createWriteStream('input.txt.gz'),\n  (err) => { if (err) console.error('Pipeline failed', err); }\n);"},
        ],
        "tags": ["streams", "backpressure"],
        "gotchas": ["Ignoring write()'s false return value silently grows the internal buffer and leaks memory.", "Plain pipe() does not propagate errors or destroy all streams on failure; pipeline() does."],
        "follow_ups": ["What does the highWaterMark option control?", "Why is stream.pipeline() preferred over chaining .pipe() calls?"],
    },
    {
        "slug": "node-buffer-basics",
        "question": "What is a Buffer in Node.js and why is Buffer.alloc preferred over Buffer.allocUnsafe?",
        "difficulty": "MEDIUM",
        "tldr": "A Buffer is a fixed-length chunk of raw binary memory outside the V8 heap, used for I/O. Buffer.alloc(n) zero-fills the memory; Buffer.allocUnsafe(n) skips zero-filling for speed but may contain old, sensitive data from reused memory.",
        "explanation": "Buffers represent binary data (file contents, network packets) that JavaScript strings can't safely model. Buffer.alloc is safe because it initializes every byte to zero. Buffer.allocUnsafe is faster because it pulls from a pre-allocated pool without clearing it, so the contents are unpredictable and could leak previously held data if exposed.",
        "code_examples": [
            {"language": "javascript", "label": "alloc vs allocUnsafe",
             "code": "const safe = Buffer.alloc(8);        // <Buffer 00 00 00 00 00 00 00 00>\nconst unsafe = Buffer.allocUnsafe(8); // uninitialized!\n\nconst fromStr = Buffer.from('hello', 'utf8');\nconsole.log(fromStr.toString('hex')); // 68656c6c6f\nconsole.log(fromStr.length);          // 5 (bytes, not chars)"},
        ],
        "tags": ["buffers", "binary"],
        "gotchas": ["allocUnsafe contents are not zeroed and may expose leftover memory; always overwrite fully before reading/sending.", "Buffer.length is the byte count, not the character count; multibyte UTF-8 chars span multiple bytes."],
        "follow_ups": ["Why are Buffers allocated outside the V8 heap?", "What happens if you slice a Buffer and mutate the slice?"],
    },
    {
        "slug": "node-event-emitter",
        "question": "How does the EventEmitter class work, and what is the 'error' event special case?",
        "difficulty": "EASY",
        "tldr": "EventEmitter implements the observer pattern: .on() registers listeners and .emit() invokes them synchronously in registration order. If an 'error' event is emitted with no listener attached, Node throws and typically crashes the process.",
        "explanation": "Most core Node objects (streams, servers, sockets) inherit from EventEmitter. Listeners run synchronously and in the order they were added. The 'error' event is special: emitting it without a registered handler causes an uncaught exception, so you should always listen for 'error' on emitters that can fail.",
        "code_examples": [
            {"language": "javascript", "label": "basic emitter usage",
             "code": "const EventEmitter = require('events');\n\nclass Job extends EventEmitter {}\nconst job = new Job();\n\njob.on('done', (result) => console.log('done:', result));\njob.on('error', (err) => console.error('handled:', err.message));\n\njob.emit('done', 42);\njob.emit('error', new Error('boom'));"},
        ],
        "tags": ["events", "eventemitter"],
        "gotchas": ["Emitting 'error' with no listener throws and crashes the process.", "Adding more than 10 listeners for one event triggers a MaxListenersExceededWarning, often signaling a leak."],
        "follow_ups": ["How would you raise or remove the max listeners limit?", "Are EventEmitter listeners invoked synchronously or asynchronously?"],
    },
    {
        "slug": "node-cluster-module",
        "question": "What does the cluster module do and how does it distribute incoming connections?",
        "difficulty": "MEDIUM",
        "tldr": "The cluster module forks multiple worker processes that share a single server port, letting a Node app use multiple CPU cores. The master process distributes incoming connections, by default using a round-robin scheduler on most platforms.",
        "explanation": "Because a single Node process runs JavaScript on one thread, the cluster module spawns child processes (workers) via child_process.fork to utilize all cores. Workers share the listening socket; the master accepts connections and hands them to workers round-robin on non-Windows systems. Workers do not share memory, so state must be kept in an external store.",
        "code_examples": [
            {"language": "javascript", "label": "round-robin HTTP cluster",
             "code": "const cluster = require('cluster');\nconst http = require('http');\nconst os = require('os');\n\nif (cluster.isPrimary) {\n  for (let i = 0; i < os.cpus().length; i++) cluster.fork();\n  cluster.on('exit', () => cluster.fork());\n} else {\n  http.createServer((req, res) => res.end(`Handled by ${process.pid}`))\n      .listen(3000);\n}"},
        ],
        "tags": ["cluster", "scaling"],
        "gotchas": ["Workers do NOT share memory; in-memory sessions/caches must move to Redis or similar.", "Sticky sessions are needed for WebSockets/stateful connections since round-robin can route a client to different workers."],
        "follow_ups": ["How does cluster differ from worker_threads?", "Why might you use a process manager like PM2 instead of writing cluster code by hand?"],
    },
    {
        "slug": "node-error-first-callbacks",
        "question": "What is the error-first callback convention in Node.js?",
        "difficulty": "EASY",
        "tldr": "The Node callback convention passes an error as the first argument and results afterward: callback(err, ...results). If err is null/undefined the operation succeeded; otherwise you handle the error and typically return early.",
        "explanation": "Before Promises were widespread, Node's async APIs adopted a uniform contract where the first callback parameter is reserved for an Error (or null on success). This consistency lets utilities like util.promisify automatically convert callback APIs to Promises. The convention forces callers to consider errors first.",
        "code_examples": [
            {"language": "javascript", "label": "error-first callback + promisify",
             "code": "const fs = require('fs');\n\nfs.readFile('/etc/hosts', 'utf8', (err, data) => {\n  if (err) {\n    console.error('Read failed:', err.message);\n    return; // always return early\n  }\n  console.log(data);\n});\n\nconst { promisify } = require('util');\nconst readFile = promisify(fs.readFile);"},
        ],
        "tags": ["callbacks", "errors"],
        "gotchas": ["Forgetting to return after handling err often runs the success path with undefined data.", "Throwing inside an async callback won't be caught by an outer try/catch surrounding the call."],
        "follow_ups": ["How does util.promisify rely on this convention?", "What goes wrong if you call the callback twice?"],
    },
    {
        "slug": "node-commonjs-vs-esm",
        "question": "What are the key differences between CommonJS and ES Modules in Node.js?",
        "difficulty": "MEDIUM",
        "tldr": "CommonJS uses require()/module.exports, loads synchronously, and resolves bindings at runtime. ESM uses import/export, is asynchronous, statically analyzable, supports top-level await, and provides live read-only bindings. File type is determined by extension (.cjs/.mjs) or package.json 'type'.",
        "explanation": "CommonJS is Node's original module system: require() is synchronous and returns a copy of module.exports at call time. ESM is the ECMAScript standard with static import/export, enabling tree-shaking and top-level await but requiring asynchronous resolution. In ESM, __dirname and require don't exist by default, and imported bindings are live references that reflect changes in the exporting module.",
        "code_examples": [
            {"language": "javascript", "label": "__dirname in ESM",
             "code": "// Recreating CommonJS globals in ESM:\nimport { fileURLToPath } from 'node:url';\nimport { dirname } from 'node:path';\n\nconst __filename = fileURLToPath(import.meta.url);\nconst __dirname = dirname(__filename);"},
        ],
        "tags": ["modules", "esm"],
        "gotchas": ["__dirname, __filename, and require are not defined in ESM; use import.meta.url instead.", "You can import() CommonJS from ESM, but importing ESM into CommonJS requires dynamic import() since require() of ESM throws (in older versions)."],
        "follow_ups": ["What does the 'type' field in package.json control?", "Why can't you use a synchronous require() to load an ES module?"],
    },
    {
        "slug": "node-worker-threads",
        "question": "When should you use worker_threads, and how do they differ from child processes?",
        "difficulty": "HARD",
        "tldr": "worker_threads run JavaScript in parallel threads within the same process, ideal for CPU-bound work. Unlike child_process, they can share memory via SharedArrayBuffer and have lower overhead, but they share the same process and aren't meant for isolation.",
        "explanation": "Node's main thread is single-threaded, so CPU-heavy tasks (hashing, parsing, image processing) block the event loop. worker_threads offload such work to separate V8 instances running in threads, communicating via message passing or shared memory. They start faster and use less memory than forking full child processes, but offer no process-level isolation.",
        "code_examples": [
            {"language": "javascript", "label": "offloading CPU work",
             "code": "const { Worker, isMainThread, parentPort, workerData } = require('worker_threads');\n\nif (isMainThread) {\n  const worker = new Worker(__filename, { workerData: 40 });\n  worker.on('message', (result) => console.log('fib =', result));\n} else {\n  const fib = (n) => (n < 2 ? n : fib(n - 1) + fib(n - 2));\n  parentPort.postMessage(fib(workerData));\n}"},
        ],
        "tags": ["worker-threads", "concurrency"],
        "gotchas": ["Worker threads are NOT a fix for I/O-bound work; Node's async I/O already handles that without threads.", "Objects are copied via structured clone when posted unless you use SharedArrayBuffer or transfer the buffer."],
        "follow_ups": ["What is the difference between transferring and cloning a value passed to a worker?", "When would child_process.fork be a better choice than a worker thread?"],
    },
    {
        "slug": "node-child-process-methods",
        "question": "What are the differences between spawn, exec, execFile, and fork in child_process?",
        "difficulty": "MEDIUM",
        "tldr": "spawn streams output and is best for large/long-running output; exec buffers the whole output and runs in a shell (so it can be injected); execFile runs a file without a shell; fork is a specialized spawn for Node scripts with a built-in IPC channel.",
        "explanation": "spawn launches a process and exposes stdio as streams, suitable for streaming large outputs. exec runs a command through a shell and buffers stdout/stderr into memory (capped by maxBuffer), convenient but risky with untrusted input. execFile skips the shell, avoiding shell-injection. fork is spawn specialized for forking Node modules and sets up a message-passing IPC channel.",
        "code_examples": [
            {"language": "javascript", "label": "the four APIs",
             "code": "const { spawn, exec, fork } = require('child_process');\n\nconst ls = spawn('ls', ['-lh', '/usr']); // streamed\nexec('cat *.js | wc -l', (err, stdout) => console.log(stdout)); // buffered, shell\nconst child = fork('./worker.js'); // Node child + IPC\nchild.send({ task: 'start' });\nchild.on('message', (msg) => console.log('from child:', msg));"},
        ],
        "tags": ["child-process", "ipc"],
        "gotchas": ["exec runs through a shell, so interpolating user input enables command injection; prefer spawn/execFile with an args array.", "exec buffers output in memory; large output exceeding maxBuffer (default ~1MB) throws and kills the child."],
        "follow_ups": ["Why is execFile safer than exec for untrusted arguments?", "How does the IPC channel created by fork work under the hood?"],
    },
    {
        "slug": "node-require-cache",
        "question": "How does the require cache work, and what are the implications of caching modules?",
        "difficulty": "MEDIUM",
        "tldr": "After a module is first required, Node caches its module.exports in require.cache keyed by resolved absolute path. Subsequent require() calls return the same cached object, so module top-level code runs only once and exports act like singletons.",
        "explanation": "The require cache ensures each module is evaluated a single time per resolved path, making modules effectively singletons and avoiding redundant work or circular-load loops. You can inspect or delete entries via require.cache, though deleting to force a reload is fragile and discouraged in production. Because exports are shared by reference, mutating a required object affects every consumer.",
        "code_examples": [
            {"language": "javascript", "label": "modules are cached singletons",
             "code": "// counter.js\nlet count = 0;\nmodule.exports = { inc: () => ++count, get: () => count };\n\n// app.js\nconst a = require('./counter');\nconst b = require('./counter');\na.inc();\nconsole.log(b.get()); // 1 -> a and b are the SAME cached object"},
        ],
        "tags": ["modules", "require"],
        "gotchas": ["Mutating a module's exported object leaks state to every other consumer because they share one reference.", "Deleting from require.cache doesn't reload transitively-required modules and can produce duplicate instances of classes (breaking instanceof)."],
        "follow_ups": ["How does the cache help resolve circular dependencies?", "What key does the require cache use, and why does it matter for symlinks?"],
    },
    {
        "slug": "node-global-objects",
        "question": "What are the key Node.js global objects like process and __dirname?",
        "difficulty": "EASY",
        "tldr": "process provides info about and control over the current process (argv, env, cwd, exit, stdout). __dirname and __filename are the directory and full path of the current module. Other globals include global, Buffer, and the timer functions.",
        "explanation": "Unlike browser JS, Node has no window; the top-level global object is global (or globalThis). The process object exposes environment variables, command-line arguments, the event-emitter-based stdio streams, and lifecycle methods. __dirname and __filename are technically injected per-module by the module wrapper rather than being true globals, and they don't exist in ESM.",
        "code_examples": [
            {"language": "javascript", "label": "common globals",
             "code": "console.log(__dirname);          // absolute dir of this module\nconsole.log(process.argv);       // ['node', '/path/script.js', ...args]\nconsole.log(process.cwd());      // current working directory\nconsole.log(process.platform);   // 'darwin' | 'linux' | 'win32'\n\nprocess.on('exit', (code) => console.log('exiting with', code));"},
        ],
        "tags": ["globals", "process"],
        "gotchas": ["__dirname (module directory) is not the same as process.cwd() (where node was launched).", "__dirname and __filename are undefined in ES modules."],
        "follow_ups": ["Why is __dirname not a true global but rather module-scoped?", "What is the difference between process.cwd() and __dirname?"],
    },
    {
        "slug": "node-async-hooks-basics",
        "question": "What is the async_hooks module and what problem does AsyncLocalStorage solve?",
        "difficulty": "HARD",
        "tldr": "async_hooks tracks the lifecycle of asynchronous resources, enabling context propagation across async boundaries. AsyncLocalStorage, built on it, stores per-request context (like a trace/request ID) accessible anywhere in an async call chain without passing it explicitly.",
        "explanation": "In async code, there's no thread-local storage, so correlating logs to a single request is hard. async_hooks exposes callbacks for each async resource's lifecycle, and AsyncLocalStorage uses this to maintain a 'store' that follows execution through callbacks, Promises, and timers. This is how request-scoped context is implemented in many APM and logging tools.",
        "code_examples": [
            {"language": "javascript", "label": "request-scoped context",
             "code": "const { AsyncLocalStorage } = require('async_hooks');\nconst als = new AsyncLocalStorage();\n\nfunction log(msg) {\n  const store = als.getStore();\n  console.log(`[req ${store?.reqId}] ${msg}`);\n}\n\nals.run({ reqId: 'abc' }, async () => {\n  log('start');\n  await new Promise(r => setTimeout(r, 10));\n  log('after await'); // still logs req abc\n});"},
        ],
        "tags": ["async-hooks", "asynclocalstorage"],
        "gotchas": ["Enabling async_hooks (especially the before/after hooks) adds measurable performance overhead.", "Context can be lost across certain queues or third-party libraries that detach from the async resource chain."],
        "follow_ups": ["How does AsyncLocalStorage compare to thread-local storage in other languages?", "What are the four lifecycle callbacks exposed by createHook?"],
    },
    {
        "slug": "node-uncaught-exceptions-rejections",
        "question": "How should you handle uncaughtException and unhandledRejection in Node.js?",
        "difficulty": "HARD",
        "tldr": "Listen via process.on('uncaughtException') and process.on('unhandledRejection') for logging/cleanup only, then exit the process. The state is considered corrupt after an uncaught exception, so you should not resume normal operation; let a supervisor restart the process.",
        "explanation": "An uncaughtException means an error escaped all try/catch and callbacks, leaving the app in an undefined state. The recommended practice is to log, perform synchronous cleanup, and exit so a process manager restarts cleanly, rather than swallowing the error and continuing. unhandledRejection fires for Promises rejected without a .catch; in recent Node versions the default behavior is to terminate the process.",
        "code_examples": [
            {"language": "javascript", "label": "handlers as last resort",
             "code": "process.on('uncaughtException', (err, origin) => {\n  console.error('Uncaught:', err, 'origin:', origin);\n  process.exit(1); // do NOT resume\n});\n\nprocess.on('unhandledRejection', (reason) => {\n  console.error('Unhandled rejection:', reason);\n  throw reason;\n});"},
        ],
        "tags": ["errors", "process"],
        "gotchas": ["Using uncaughtException to keep the process alive is dangerous: the app may be in a corrupt state with leaked resources.", "In modern Node, an unhandled promise rejection terminates the process by default."],
        "follow_ups": ["Why is it unsafe to continue running after an uncaughtException?", "What is the difference between unhandledRejection and rejectionHandled events?"],
    },
    {
        "slug": "node-pipe-stream-composition",
        "question": "How do you compose streams with pipe() and pipeline(), and why is pipeline() safer?",
        "difficulty": "MEDIUM",
        "tldr": "pipe() connects a Readable to a Writable, forwarding data and managing backpressure, and can be chained. But pipe() doesn't forward errors or clean up the whole chain on failure, so stream.pipeline() is preferred for proper error propagation and resource cleanup.",
        "explanation": "src.pipe(dest) handles flow control automatically and returns the destination for chaining transforms. Its weakness is error handling: if a stream in a .pipe() chain errors, the other streams aren't destroyed, leaking file descriptors. stream.pipeline() pipes a series of streams together, destroys all of them on error, and calls a single callback (or resolves a promise) when done.",
        "code_examples": [
            {"language": "javascript", "label": "pipe vs pipeline",
             "code": "const fs = require('fs');\nconst zlib = require('zlib');\nconst { pipeline } = require('stream/promises');\n\n// Robust: cleans up every stream on error.\nawait pipeline(\n  fs.createReadStream('a.txt'),\n  zlib.createGzip(),\n  fs.createWriteStream('a.gz')\n);"},
        ],
        "tags": ["streams", "pipeline"],
        "gotchas": ["A .pipe() chain leaks file descriptors if a middle stream errors because only the immediate destination is handled.", "pipe() does not automatically end the destination if { end: false } is set; mismatched options can leave streams open."],
        "follow_ups": ["What does pipeline() do to each stream when one of them errors?", "How does pipe() decide when to pause the source?"],
    },
    {
        "slug": "node-blocking-vs-nonblocking-io",
        "question": "What is the difference between blocking and non-blocking I/O in Node.js?",
        "difficulty": "EASY",
        "tldr": "Blocking I/O (the *Sync methods) halts the single JS thread until the operation finishes, freezing all other work. Non-blocking I/O offloads the operation (often to libuv's thread pool) and continues, invoking a callback/Promise on completion, keeping the event loop responsive.",
        "explanation": "Node runs your JavaScript on one thread, so a synchronous call like fs.readFileSync blocks the event loop and prevents any other request from being processed until it returns. Non-blocking variants (fs.readFile, fs.promises) return control immediately and notify you later. In servers, blocking calls in the request path are a major scalability killer.",
        "code_examples": [
            {"language": "javascript", "label": "sync vs async file read",
             "code": "const fs = require('fs');\n\n// Blocking: nothing else runs until the file is fully read.\nconst data = fs.readFileSync('big.log', 'utf8');\n\n// Non-blocking: event loop stays free; callback fires later.\nfs.readFile('big.log', 'utf8', (err, data) => {\n  if (err) throw err;\n  console.log('after async read');\n});\nconsole.log('this logs before the async read finishes');"},
        ],
        "tags": ["io", "event-loop"],
        "gotchas": ["A single blocking call in a request handler stalls every concurrent request on that process.", "Sync methods are acceptable at startup (loading config) but rarely inside request handling."],
        "follow_ups": ["Which kinds of operations use libuv's thread pool versus the OS async APIs?", "How can a CPU-bound loop block the event loop even without I/O?"],
    },
    {
        "slug": "node-middleware-pattern",
        "question": "How does the Express-style middleware pattern work?",
        "difficulty": "MEDIUM",
        "tldr": "Middleware are functions (req, res, next) executed in order for a matching route. Each middleware can inspect/modify req/res, then call next() to pass control onward, or end the response. Calling next(err) jumps to error-handling middleware (which has four arguments).",
        "explanation": "Express maintains an ordered stack of middleware. When a request arrives, it runs them sequentially; each must either send a response or call next() to continue the chain. This pattern enables composable cross-cutting concerns like logging, auth, and body parsing. Error-handling middleware is distinguished by its four-parameter signature (err, req, res, next) and is invoked when next(err) is called.",
        "code_examples": [
            {"language": "javascript", "label": "middleware chain",
             "code": "const express = require('express');\nconst app = express();\n\napp.use((req, res, next) => {\n  console.log(`${req.method} ${req.url}`);\n  next();\n});\n\napp.get('/', (req, res) => res.send('hello'));\n\napp.use((err, req, res, next) => {\n  console.error(err.stack);\n  res.status(500).send('Something broke');\n});"},
        ],
        "tags": ["express", "middleware"],
        "gotchas": ["Forgetting to call next() (without responding) hangs the request indefinitely.", "Error-handling middleware MUST declare all four parameters or Express treats it as ordinary middleware."],
        "follow_ups": ["How do you forward an error from an async middleware to the error handler?", "Why does middleware order matter for body parsing and auth?"],
    },
    {
        "slug": "node-process-env",
        "question": "How does process.env work and what are best practices for environment variables?",
        "difficulty": "EASY",
        "tldr": "process.env is an object of the process's environment variables; all values are strings (or undefined). Use it for configuration and secrets, never commit them, provide sensible defaults, and validate required variables at startup.",
        "explanation": "process.env exposes the OS environment to your Node app, the standard way to inject config and secrets per environment without hardcoding. Every value is a string, so 'false', '0', and numbers need explicit parsing/coercion. Best practice is to load them (e.g. via a .env file with dotenv), validate presence at boot, and fail fast if required values are missing.",
        "code_examples": [
            {"language": "javascript", "label": "reading and validating env vars",
             "code": "const port = parseInt(process.env.PORT, 10) || 3000;\nconst debug = process.env.DEBUG === 'true'; // 'false' is truthy as a string\n\nconst required = ['DATABASE_URL', 'JWT_SECRET'];\nfor (const key of required) {\n  if (!process.env[key]) throw new Error(`Missing env var: ${key}`);\n}"},
        ],
        "tags": ["env", "config"],
        "gotchas": ["Every env value is a string: process.env.FLAG === 'false' is the string 'false', which is truthy.", "Assigning to process.env coerces values to strings and only affects the current process and its children."],
        "follow_ups": ["Why should secrets not be committed in a .env file?", "How would you validate and type-coerce env config at startup?"],
    },
    {
        "slug": "node-memory-leaks",
        "question": "What are common causes of memory leaks in Node.js and how do you detect them?",
        "difficulty": "HARD",
        "tldr": "Common causes: unbounded caches/arrays, forgotten timers, dangling event listeners, and closures retaining large scopes. Detect them by watching for steadily rising heap usage and comparing V8 heap snapshots in Chrome DevTools or with --inspect.",
        "explanation": "A leak is memory that's reachable but never released, so the GC can't reclaim it; the process heap grows until it crashes (often with an out-of-memory error). Typical culprits are global Maps that only grow, listeners added per-request without removal, and unreferenced timers. You diagnose by taking heap snapshots over time and looking for object counts that keep increasing.",
        "code_examples": [
            {"language": "javascript", "label": "leak patterns",
             "code": "// LEAK: cache grows forever, entries are never evicted.\nconst cache = new Map();\napp.get('/user/:id', (req, res) => {\n  cache.set(req.params.id, buildHeavyObject());\n  res.json(cache.get(req.params.id));\n});\n\nconsole.log(process.memoryUsage().heapUsed);"},
        ],
        "tags": ["memory", "performance"],
        "gotchas": ["Per-request event listeners that are never removed accumulate and leak; use once() or removeListener.", "A closure can keep a large object alive just by referencing one small variable from the same scope."],
        "follow_ups": ["How do you read a heap snapshot diff to find the leaking object type?", "Why might a WeakMap be a better cache choice than a Map?"],
    },
    {
        "slug": "node-module-wrapper",
        "question": "What is the module wrapper function in Node.js (CommonJS)?",
        "difficulty": "MEDIUM",
        "tldr": "Before executing a CommonJS module, Node wraps its code in a function with the parameters (exports, require, module, __filename, __dirname). This gives each module its own scope and is why those identifiers are available without being true globals.",
        "explanation": "Node doesn't run your module code in the global scope; it compiles it as the body of a wrapper function so top-level variables stay private to the module. The wrapper's parameters inject the module's exports object, its require function, the module object itself, and the path variables. This is the mechanism behind module-scoped __dirname/__filename and explains why this at module top level equals module.exports.",
        "code_examples": [
            {"language": "javascript", "label": "the wrapper function",
             "code": "// Node effectively wraps every CommonJS module like this:\n(function (exports, require, module, __filename, __dirname) {\n  const x = 1;            // private to this module\n  module.exports = { x }; // what other modules receive\n});"},
        ],
        "tags": ["modules", "commonjs"],
        "gotchas": ["At module top level this === module.exports, not the global object.", "Reassigning the exports parameter (exports = {...}) breaks the link to module.exports; assign to module.exports instead."],
        "follow_ups": ["Why does assigning to exports directly fail to export anything?", "Does the module wrapper exist for ES modules?"],
    },
    {
        "slug": "node-package-exports-main",
        "question": "What is the difference between the 'main' and 'exports' fields in package.json?",
        "difficulty": "MEDIUM",
        "tldr": "'main' declares the single legacy entry point for a package. 'exports' is the modern field that defines an encapsulated public API: it can map multiple subpaths, provide conditional exports (import vs require, node vs browser), and blocks access to files not explicitly exported.",
        "explanation": "'main' simply tells Node which file require('pkg') resolves to. 'exports' supersedes it by letting you expose multiple entry points and serve different files based on conditions (ESM import vs CommonJS require, environment). Crucially, once 'exports' is defined, deep imports into unlisted internal files are forbidden, giving real encapsulation. 'exports' takes precedence over 'main'.",
        "code_examples": [
            {"language": "javascript", "label": "conditional and subpath exports",
             "code": "{\n  \"name\": \"my-lib\",\n  \"main\": \"./dist/index.cjs\",\n  \"exports\": {\n    \".\": {\n      \"import\": \"./dist/index.mjs\",\n      \"require\": \"./dist/index.cjs\"\n    },\n    \"./utils\": \"./dist/utils.mjs\"\n  }\n}"},
        ],
        "tags": ["package-json", "modules"],
        "gotchas": ["Defining 'exports' blocks all deep imports not explicitly listed, which can break consumers relying on internal paths.", "Order matters in the conditions object; the first matching condition wins, so place 'node'/'default' fallbacks last."],
        "follow_ups": ["How do conditional exports let one package serve both ESM and CommonJS?", "What is the 'default' condition used for in an exports map?"],
    },
]
