QUESTIONS = [
    {
        "slug": "react-rules-of-hooks",
        "question": "What are the Rules of Hooks, and why does React enforce them?",
        "difficulty": "EASY",
        "tldr": "Only call hooks at the top level of a React function component or custom hook, and never conditionally. React relies on a stable call order across renders to associate each hook with its state.",
        "explanation": "React stores hook state in an ordered list keyed by call index, not by name. If you call hooks inside conditions, loops, or nested functions, the order can change between renders and React will mismatch state to the wrong hook. The two rules: call hooks only at the top level, and only from React functions (components or custom hooks).",
        "code_examples": [
            {"language": "tsx", "label": "Conditional hook vs. top-level hook",
             "code": "// Bad: Conditional hook breaks call order\nfunction Profile({ userId }: { userId?: string }) {\n  if (userId) {\n    const [name, setName] = useState(\"\"); // sometimes called\n  }\n  return null;\n}\n\n// Good: Hook at top level, condition inside\nfunction ProfileFixed({ userId }: { userId?: string }) {\n  const [name, setName] = useState(\"\");\n  if (!userId) return null;\n  return <span>{name}</span>;\n}"},
        ],
        "tags": ["hooks", "fundamentals"],
        "gotchas": ["Early return statements before a hook are just as dangerous as if wrappers — the hook below may be skipped.", "Calling a hook inside a callback, event handler, or .map() violates the rules even though it looks like 'top level' code."],
        "follow_ups": ["How does the ESLint plugin eslint-plugin-react-hooks catch these violations at build time?", "How would you conditionally use logic that depends on a hook without breaking the rules?"],
    },
    {
        "slug": "react-useeffect-dependency-array",
        "question": "How does the useEffect dependency array work, and what happens with the three forms ([], [deps], and omitted)?",
        "difficulty": "EASY",
        "tldr": "The dependency array tells React when to re-run an effect. [] runs once on mount, [a, b] re-runs when a or b change by Object.is comparison, and omitting it re-runs after every render.",
        "explanation": "After commit, React compares each dependency against the previous render's value using Object.is. If any changed, it runs the cleanup (if present) and then the effect again. An empty array means no dependencies ever change, so it runs only on mount and cleans up on unmount.",
        "code_examples": [
            {"language": "tsx", "label": "Three dependency forms",
             "code": "function Search({ query }: { query: string }) {\n  useEffect(() => {\n    const id = setTimeout(() => fetch(`/api?q=${query}`), 300);\n    return () => clearTimeout(id); // cleanup before next effect\n  }, [query]); // re-runs only when query changes\n\n  useEffect(() => {\n    console.log(\"mounted\");\n  }, []); // runs once\n\n  return null;\n}"},
        ],
        "tags": ["hooks", "useeffect"],
        "gotchas": ["Object and array literals create a new reference every render, so passing them as deps re-runs the effect every time.", "Lying about dependencies (omitting a used value) causes stale data — let the linter add them all."],
        "follow_ups": ["When would you intentionally use an empty dependency array but still reference props inside the effect?", "How do you handle a dependency that is an object you don't control the identity of?"],
    },
    {
        "slug": "react-usememo-vs-usecallback",
        "question": "What is the difference between useMemo and useCallback, and when should you use each?",
        "difficulty": "MEDIUM",
        "tldr": "useMemo memoizes a computed value; useCallback memoizes a function reference. useCallback(fn, deps) is equivalent to useMemo(() => fn, deps).",
        "explanation": "Both cache something across renders keyed by a dependency array. useMemo returns the result of calling the factory and is for expensive computations or stable object/array references. useCallback returns the function itself unchanged, which matters when passing callbacks to memoized children or as effect dependencies.",
        "code_examples": [
            {"language": "tsx", "label": "useMemo for values, useCallback for functions",
             "code": "function List({ items }: { items: number[] }) {\n  const total = useMemo(() => items.reduce((a, b) => a + b, 0), [items]);\n  const handleClick = useCallback((id: number) => {\n    console.log(id);\n  }, []);\n  return <Child total={total} onClick={handleClick} />;\n}"},
        ],
        "tags": ["hooks", "performance"],
        "gotchas": ["Memoizing everything adds overhead and memory cost; it only helps when paired with React.memo children or expensive computations.", "If the dependency array is wrong, both hooks return stale values or functions with stale closures."],
        "follow_ups": ["Why does useCallback alone not prevent a child re-render unless the child is wrapped in React.memo?", "How does the React Compiler change the need for manual useMemo/useCallback?"],
    },
    {
        "slug": "react-reconciliation-and-keys",
        "question": "How does React's reconciliation algorithm work, and what role do keys play?",
        "difficulty": "MEDIUM",
        "tldr": "Reconciliation diffs the new element tree against the previous one to compute minimal DOM updates. Keys give list items a stable identity so React can match elements across renders instead of recreating them.",
        "explanation": "React assumes elements of different types produce different trees and tears them down. For lists, it uses the key to match old and new children by identity rather than position, preserving state and avoiding unnecessary remounts. Without stable keys, React falls back to index matching, which misbehaves on reorder or insertion.",
        "code_examples": [
            {"language": "tsx", "label": "Keying a list by stable id",
             "code": "function TodoList({ todos }: { todos: { id: string; text: string }[] }) {\n  return (\n    <ul>\n      {todos.map((t) => (\n        <li key={t.id}>{t.text}</li>\n      ))}\n    </ul>\n  );\n}"},
        ],
        "tags": ["reconciliation", "keys"],
        "gotchas": ["Changing an element's type (e.g. div to span) unmounts the subtree and resets all its state.", "Using array index as a key breaks when items are inserted, removed, or reordered."],
        "follow_ups": ["How can you deliberately use a key change to force a component to remount and reset its state?", "Why don't keys need to be globally unique, only unique among siblings?"],
    },
    {
        "slug": "react-controlled-vs-uncontrolled",
        "question": "What is the difference between controlled and uncontrolled components?",
        "difficulty": "EASY",
        "tldr": "A controlled component's value is driven by React state via value + onChange. An uncontrolled component holds its own state in the DOM, which you read with a ref.",
        "explanation": "Controlled inputs make React the single source of truth, enabling validation, formatting, and conditional disabling on every keystroke. Uncontrolled inputs let the DOM manage the value and you grab it on demand (e.g. on submit) via a ref or defaultValue. Controlled is preferred for interactive forms; uncontrolled is simpler for one-shot reads.",
        "code_examples": [
            {"language": "tsx", "label": "Controlled vs uncontrolled input",
             "code": "function Controlled() {\n  const [value, setValue] = useState(\"\");\n  return <input value={value} onChange={(e) => setValue(e.target.value)} />;\n}\n\nfunction Uncontrolled() {\n  const ref = useRef<HTMLInputElement>(null);\n  return <input defaultValue=\"hi\" ref={ref} />;\n}"},
        ],
        "tags": ["forms", "fundamentals"],
        "gotchas": ["Passing value without onChange makes the input read-only and logs a warning; use defaultValue for uncontrolled.", "Switching an input from controlled to uncontrolled (value going from a string to undefined) throws a React warning."],
        "follow_ups": ["Why are uncontrolled components often faster for very large forms?", "How do libraries like React Hook Form leverage uncontrolled inputs for performance?"],
    },
    {
        "slug": "react-usecontext",
        "question": "How does useContext work, and what are its re-render implications?",
        "difficulty": "MEDIUM",
        "tldr": "useContext subscribes a component to a context value; whenever the Provider's value changes by Object.is, every consumer re-renders. It avoids prop drilling but does not offer selective subscriptions.",
        "explanation": "A Provider broadcasts a value down the tree, and any descendant calling useContext reads the nearest Provider's value. When that value changes identity, all consumers re-render regardless of whether they use the changed part. This makes context great for low-frequency global data (theme, auth) but a performance risk for frequently changing values.",
        "code_examples": [
            {"language": "tsx", "label": "Provider and consumer",
             "code": "const ThemeContext = createContext<\"light\" | \"dark\">(\"light\");\n\nfunction App() {\n  const [theme] = useState<\"light\" | \"dark\">(\"dark\");\n  return (\n    <ThemeContext.Provider value={theme}>\n      <Toolbar />\n    </ThemeContext.Provider>\n  );\n}\n\nfunction Toolbar() {\n  const theme = useContext(ThemeContext);\n  return <div className={theme}>Toolbar</div>;\n}"},
        ],
        "tags": ["context", "performance"],
        "gotchas": ["Passing an inline object literal as value re-renders every consumer on each parent render — memoize it.", "Context has no built-in selector; reading one field still re-renders when any field changes."],
        "follow_ups": ["How would you split one large context into multiple to reduce re-renders?", "When is an external store like Zustand or useSyncExternalStore a better fit than context?"],
    },
    {
        "slug": "react-useref",
        "question": "What is useRef used for, and how does it differ from useState?",
        "difficulty": "EASY",
        "tldr": "useRef returns a mutable { current } object that persists across renders without causing re-renders when mutated. It's used for DOM access and storing mutable values like timers or previous props.",
        "explanation": "Unlike useState, mutating ref.current does not trigger a re-render, and the change is visible synchronously. Refs are ideal for imperative DOM handles, interval/timeout IDs, or any instance-like value you want to survive renders but not render from. Using a ref's value during render is discouraged because reads are not reactive.",
        "code_examples": [
            {"language": "tsx", "label": "Storing a timer id in a ref",
             "code": "function Stopwatch() {\n  const intervalRef = useRef<number | null>(null);\n  const [seconds, setSeconds] = useState(0);\n\n  function start() {\n    if (intervalRef.current) return;\n    intervalRef.current = window.setInterval(() => setSeconds((s) => s + 1), 1000);\n  }\n  function stop() {\n    if (intervalRef.current) window.clearInterval(intervalRef.current);\n    intervalRef.current = null;\n  }\n  return <button onClick={start} onDoubleClick={stop}>{seconds}s</button>;\n}"},
        ],
        "tags": ["hooks", "useref"],
        "gotchas": ["Mutating a ref does not re-render, so don't use it for values the UI must reflect.", "Reading or writing ref.current during render is unsafe; do it in effects or event handlers."],
        "follow_ups": ["How do you forward a ref to a child component with forwardRef or the React 19 ref prop?", "What is the difference between a callback ref and an object ref?"],
    },
    {
        "slug": "react-state-update-batching",
        "question": "How does React batch state updates, and what changed with automatic batching in React 18?",
        "difficulty": "MEDIUM",
        "tldr": "React groups multiple setState calls into a single re-render. React 18's automatic batching extends this to promises, timeouts, and native event handlers, not just React event handlers.",
        "explanation": "Before React 18, batching only happened inside React event handlers; updates in setTimeout, fetch callbacks, or native events each triggered a separate render. React 18 batches all of these by default. You can opt out for a synchronous DOM read with flushSync.",
        "code_examples": [
            {"language": "tsx", "label": "Automatic batching across an await",
             "code": "function Counter() {\n  const [count, setCount] = useState(0);\n  const [flag, setFlag] = useState(false);\n\n  async function handleClick() {\n    await fetch(\"/api\");\n    // React 18: these are batched into ONE render even after await\n    setCount((c) => c + 1);\n    setFlag((f) => !f);\n  }\n  return <button onClick={handleClick}>{count}</button>;\n}"},
        ],
        "tags": ["state", "performance"],
        "gotchas": ["Reading state right after setState returns the old value because the update is queued, not applied synchronously.", "Multiple setCount(count + 1) calls collapse to one increment; use the updater form setCount(c => c + 1) to accumulate."],
        "follow_ups": ["When would you reach for flushSync, and what is its cost?", "How does batching interact with useState updater functions versus direct values?"],
    },
    {
        "slug": "react-usereducer",
        "question": "When should you use useReducer instead of useState?",
        "difficulty": "MEDIUM",
        "tldr": "Reach for useReducer when state is complex, has many related sub-values, or the next state depends on intricate logic. It centralizes transitions in a pure reducer function for predictability and testability.",
        "explanation": "useReducer takes a reducer (state, action) => newState and an initial state, returning the current state and a dispatch function. It shines when multiple values change together or transitions follow rules better expressed as actions. The reducer is pure and easy to unit test in isolation from the component.",
        "code_examples": [
            {"language": "tsx", "label": "Reducer with typed actions",
             "code": "type State = { count: number; step: number };\ntype Action = { type: \"inc\" } | { type: \"setStep\"; step: number };\n\nfunction reducer(state: State, action: Action): State {\n  switch (action.type) {\n    case \"inc\":\n      return { ...state, count: state.count + state.step };\n    case \"setStep\":\n      return { ...state, step: action.step };\n  }\n}\n\nfunction Counter() {\n  const [state, dispatch] = useReducer(reducer, { count: 0, step: 1 });\n  return <button onClick={() => dispatch({ type: \"inc\" })}>{state.count}</button>;\n}"},
        ],
        "tags": ["hooks", "state"],
        "gotchas": ["Reducers must be pure — no side effects, mutations, or async work inside them.", "Returning the same state object reference (mutating in place) skips the re-render."],
        "follow_ups": ["How do you combine useReducer with useContext to build a lightweight global store?", "What is the lazy initialization third argument to useReducer for?"],
    },
    {
        "slug": "react-memo-memoization",
        "question": "What does React.memo do, and when does it actually prevent re-renders?",
        "difficulty": "MEDIUM",
        "tldr": "React.memo wraps a component so it skips re-rendering when its props are shallowly equal to the previous render. It only helps if the parent re-renders frequently and the props are stable references.",
        "explanation": "By default a child re-renders whenever its parent does, regardless of props. React.memo adds a shallow prop comparison gate. It's defeated by new object, array, or function props created inline each render, which is why it's usually paired with useMemo/useCallback to stabilize those references.",
        "code_examples": [
            {"language": "tsx", "label": "Memoized child skipping parent re-renders",
             "code": "const Row = React.memo(function Row({ label }: { label: string }) {\n  console.log(\"render\", label);\n  return <div>{label}</div>;\n});\n\nfunction Parent() {\n  const [, setTick] = useState(0);\n  return (\n    <>\n      <button onClick={() => setTick((t) => t + 1)}>tick</button>\n      <Row label=\"stable\" />\n    </>\n  );\n}"},
        ],
        "tags": ["performance", "memoization"],
        "gotchas": ["Passing an inline function or object prop breaks memoization since the reference changes each render.", "A custom areEqual comparator that's too loose can cause stale UI by skipping needed renders."],
        "follow_ups": ["How does children as a prop interact with React.memo?", "Why might wrapping every component in React.memo hurt rather than help performance?"],
    },
    {
        "slug": "react-suspense-and-lazy",
        "question": "How do Suspense and React.lazy work together for code splitting?",
        "difficulty": "MEDIUM",
        "tldr": "React.lazy defers loading a component's code until it renders, returning a promise that Suspense catches to show a fallback. Together they enable route- and component-level code splitting with a declarative loading UI.",
        "explanation": "React.lazy takes a function returning a dynamic import() and produces a component that suspends while its chunk loads. A Suspense boundary above it renders the fallback until the promise resolves. Beyond lazy loading, Suspense also coordinates data fetching in frameworks and transitions.",
        "code_examples": [
            {"language": "tsx", "label": "Lazy-loaded component with a Suspense fallback",
             "code": "import { Suspense, lazy } from \"react\";\n\nconst Settings = lazy(() => import(\"./Settings\"));\n\nfunction App() {\n  return (\n    <Suspense fallback={<div>Loading…</div>}>\n      <Settings />\n    </Suspense>\n  );\n}"},
        ],
        "tags": ["suspense", "performance"],
        "gotchas": ["A lazy component must be a default export, or you need to map a named export inside the import.", "Without a Suspense boundary anywhere above a lazy component, React throws at render time."],
        "follow_ups": ["How does Suspense for data fetching differ from using it only for code splitting?", "How do nested Suspense boundaries let you stage a progressive loading experience?"],
    },
    {
        "slug": "react-render-vs-commit-phase",
        "question": "What is the difference between the render phase and the commit phase in React?",
        "difficulty": "HARD",
        "tldr": "The render phase computes what the UI should look like by calling components and diffing; it must be pure and can be interrupted. The commit phase applies the resulting changes to the DOM and runs layout effects synchronously.",
        "explanation": "During render, React calls your component functions to build a new tree and reconcile it — no DOM mutations happen yet, and with concurrent features this work can be paused, restarted, or discarded. In commit, React mutates the DOM, then runs useLayoutEffect synchronously and useEffect asynchronously after paint. Side effects belong in commit-phase hooks, never in the render body.",
        "code_examples": [
            {"language": "tsx", "label": "Where each phase's work belongs",
             "code": "function Box() {\n  const [w, setW] = useState(0);\n\n  // COMMIT PHASE (sync, before paint): safe to read layout\n  useLayoutEffect(() => {\n    setW(document.getElementById(\"box\")!.offsetWidth);\n  }, []);\n\n  // COMMIT PHASE (async, after paint): network, logging\n  useEffect(() => {\n    console.log(\"painted\");\n  }, []);\n\n  return <div id=\"box\">{w}</div>;\n}"},
        ],
        "tags": ["internals", "rendering"],
        "gotchas": ["In Strict Mode, render-phase code runs twice in development to surface impure side effects.", "Mutating the DOM or external state during render breaks concurrent rendering's ability to discard work."],
        "follow_ups": ["Why can the render phase run multiple times for a single commit under concurrent rendering?", "How does this split enable features like time slicing and useTransition?"],
    },
    {
        "slug": "react-custom-hooks",
        "question": "What are custom hooks, and what rules and conventions govern them?",
        "difficulty": "MEDIUM",
        "tldr": "A custom hook is a function whose name starts with use and that calls other hooks to encapsulate reusable stateful logic. It shares logic, not state — each call gets its own isolated state.",
        "explanation": "Custom hooks let you extract and reuse logic that involves hooks (state, effects, refs) across components. They follow the Rules of Hooks themselves and must be called at the top level of components or other hooks. Crucially, two components using the same custom hook do not share state — they each instantiate fresh state.",
        "code_examples": [
            {"language": "tsx", "label": "A reusable useToggle hook",
             "code": "function useToggle(initial = false) {\n  const [on, setOn] = useState(initial);\n  const toggle = useCallback(() => setOn((v) => !v), []);\n  return [on, toggle] as const;\n}\n\nfunction Panel() {\n  const [open, toggleOpen] = useToggle();\n  return <button onClick={toggleOpen}>{open ? \"Hide\" : \"Show\"}</button>;\n}"},
        ],
        "tags": ["hooks", "patterns"],
        "gotchas": ["Naming a hook without the use prefix disables lint enforcement of the Rules of Hooks.", "Returning new object/array references each call can destabilize consumers' effect dependencies."],
        "follow_ups": ["How do you decide what a custom hook should return — tuple vs object?", "How would you test a custom hook in isolation?"],
    },
    {
        "slug": "react-prop-drilling-vs-context",
        "question": "What is prop drilling, and what are the tradeoffs of solving it with context?",
        "difficulty": "MEDIUM",
        "tldr": "Prop drilling is passing props through many intermediate components that don't use them, just to reach a deep consumer. Context removes the threading but couples components to a provider and can trigger broad re-renders.",
        "explanation": "Prop drilling is explicit and easy to trace but becomes noisy and brittle as the tree deepens. Context eliminates the manual passing by broadcasting a value, at the cost of implicit coupling and the fact that all consumers re-render when the value changes. The right answer depends on update frequency, how many levels the prop traverses, and how many components actually need it.",
        "code_examples": [
            {"language": "tsx", "label": "Drilling a prop through an uninterested middle layer",
             "code": "function App({ user }: { user: string }) {\n  return <Layout user={user} />;\n}\nfunction Layout({ user }: { user: string }) {\n  return <Header user={user} />; // just forwarding\n}\nfunction Header({ user }: { user: string }) {\n  return <span>{user}</span>;\n}"},
        ],
        "tags": ["context", "patterns"],
        "gotchas": ["Reaching for context too early adds indirection that makes components harder to reuse and test.", "Composition (passing JSX as children) often eliminates drilling without any context at all."],
        "follow_ups": ["How does component composition / children slots reduce drilling without context?", "When is a dedicated state library a better choice than context for shared state?"],
    },
    {
        "slug": "react-key-prop-pitfalls",
        "question": "Why is using an array index as a key problematic, and when is it acceptable?",
        "difficulty": "MEDIUM",
        "tldr": "Index keys tie identity to position, so inserting, removing, or reordering items makes React reuse the wrong elements — causing wrong state and DOM in stateful list items. Index keys are only safe for static, append-only lists.",
        "explanation": "When you reorder a list keyed by index, React matches by position and 'moves' the data but keeps the old component instance and its internal state at that slot. This leads to bugs like input values or checkbox states attaching to the wrong row. Use a stable unique id from your data instead; index is acceptable only when the list never reorders, filters, or has per-item state.",
        "code_examples": [
            {"language": "tsx", "label": "Index key vs stable id in a stateful list",
             "code": "// Bad: removing the first row keeps stale input state in remaining rows\n{rows.map((row, i) => <input key={i} defaultValue={row.value} />)}\n\n// Good: state follows the correct row across reorders\n{rows.map((row) => <input key={row.id} defaultValue={row.value} />)}"},
        ],
        "tags": ["keys", "reconciliation"],
        "gotchas": ["The bug is invisible for read-only lists but surfaces the moment items carry local state.", "Generating a fresh key (e.g. Math.random()) on each render remounts every item every time — equally bad."],
        "follow_ups": ["What's a good strategy when your data genuinely has no stable id?", "How does an index key interact with React's controlled vs uncontrolled inputs?"],
    },
    {
        "slug": "react-stale-closures-in-effects",
        "question": "What is a stale closure in a React effect, and how do you avoid it?",
        "difficulty": "HARD",
        "tldr": "A stale closure happens when an effect or callback captures props/state from an old render and keeps using those frozen values. Fix it by adding the values to dependencies, using the functional updater, or storing the latest value in a ref.",
        "explanation": "Each render creates new function instances that close over that render's variables. If an effect runs once (empty deps) but references state, it keeps seeing the initial value forever. Solutions: list the captured values as dependencies so the effect re-subscribes, use setState(prev => ...) to avoid capturing state, or keep a ref pointing at the latest value for long-lived callbacks.",
        "code_examples": [
            {"language": "tsx", "label": "Avoiding stale state with a functional updater",
             "code": "function Counter() {\n  const [count, setCount] = useState(0);\n\n  useEffect(() => {\n    const id = setInterval(() => {\n      // functional updater avoids capturing stale state\n      setCount((c) => c + 1);\n    }, 1000);\n    return () => clearInterval(id);\n  }, []); // runs once, but updater stays correct\n\n  return <span>{count}</span>;\n}"},
        ],
        "tags": ["hooks", "closures"],
        "gotchas": ["Disabling the exhaustive-deps lint rule to silence a warning usually hides a stale closure bug.", "A ref fixes staleness for reads but won't re-run the effect when the value changes."],
        "follow_ups": ["How does the useEffectEvent (Effect Event) API address this without re-subscribing?", "When is a ref the right tool versus adding the value to the dependency array?"],
    },
    {
        "slug": "react-uselayouteffect-vs-useeffect",
        "question": "What is the difference between useLayoutEffect and useEffect, and when must you use useLayoutEffect?",
        "difficulty": "HARD",
        "tldr": "useEffect runs asynchronously after the browser paints; useLayoutEffect runs synchronously after DOM mutations but before paint. Use useLayoutEffect when you must measure or mutate the DOM before the user sees it to prevent visual flicker.",
        "explanation": "Both fire in the commit phase, but useEffect is deferred until after paint so it won't block visual updates, while useLayoutEffect runs synchronously before the browser paints. That timing makes useLayoutEffect right for reading layout (measuring size/position) and adjusting it before paint. Overusing it can hurt performance because it blocks painting.",
        "code_examples": [
            {"language": "tsx", "label": "Measuring before paint to avoid flicker",
             "code": "function Tooltip({ targetRect }: { targetRect: DOMRect }) {\n  const ref = useRef<HTMLDivElement>(null);\n  const [top, setTop] = useState(0);\n\n  useLayoutEffect(() => {\n    const h = ref.current!.offsetHeight;\n    setTop(targetRect.top - h);\n  }, [targetRect]);\n\n  return <div ref={ref} style={{ position: \"absolute\", top }}>tip</div>;\n}"},
        ],
        "tags": ["hooks", "rendering"],
        "gotchas": ["useLayoutEffect blocks painting, so heavy work there freezes the UI; default to useEffect unless you see flicker.", "useLayoutEffect warns during SSR because there's no DOM to measure on the server."],
        "follow_ups": ["How do you handle the SSR warning for useLayoutEffect (e.g. useIsomorphicLayoutEffect)?", "Why does useLayoutEffect cause an extra synchronous render-and-commit cycle?"],
    },
    {
        "slug": "react-derived-state",
        "question": "What is derived state, and why should you usually compute it during render instead of storing it?",
        "difficulty": "MEDIUM",
        "tldr": "Derived state is data computable from existing props or state. Storing it in its own useState risks it going out of sync; instead calculate it during render and memoize only if expensive.",
        "explanation": "Duplicating derivable data into separate state means you must manually keep it synchronized via effects, which is error-prone and adds extra renders. The React-idiomatic approach is to compute the value inline during render from the source of truth. Wrap the computation in useMemo only when it's genuinely expensive.",
        "code_examples": [
            {"language": "tsx", "label": "Deriving instead of storing",
             "code": "// Bad: redundant state that can drift out of sync\nfunction Bad({ items }: { items: string[] }) {\n  const [count, setCount] = useState(items.length);\n  useEffect(() => setCount(items.length), [items]); // extra render\n  return <span>{count}</span>;\n}\n\n// Good: derive during render — always correct\nfunction Good({ items }: { items: string[] }) {\n  const count = items.length;\n  return <span>{count}</span>;\n}"},
        ],
        "tags": ["state", "patterns"],
        "gotchas": ["Syncing derived state with an effect causes an extra render and a brief inconsistent frame.", "Premature useMemo on cheap derivations adds overhead without benefit."],
        "follow_ups": ["How would you reset a piece of state when a prop changes without an effect (e.g. the key trick)?", "When is getDerivedStateFromProps or the adjust-state-during-render pattern actually justified?"],
    },
    {
        "slug": "react-lifting-state-up",
        "question": "What does 'lifting state up' mean, and when should you do it?",
        "difficulty": "EASY",
        "tldr": "Lifting state up means moving shared state to the closest common ancestor of the components that need it, then passing it down via props. It keeps siblings in sync from a single source of truth.",
        "explanation": "When two or more components must reflect or update the same data, owning that state separately leads to divergence. You move the state up to their nearest common parent and pass the value down plus a setter callback up. This makes the parent the single source of truth and keeps the children controlled.",
        "code_examples": [
            {"language": "tsx", "label": "Shared state owned by the common parent",
             "code": "function Parent() {\n  const [value, setValue] = useState(\"\");\n  return (\n    <>\n      <Input value={value} onChange={setValue} />\n      <Preview value={value} />\n    </>\n  );\n}\n\nfunction Input({ value, onChange }: { value: string; onChange: (v: string) => void }) {\n  return <input value={value} onChange={(e) => onChange(e.target.value)} />;\n}\nfunction Preview({ value }: { value: string }) {\n  return <p>{value}</p>;\n}"},
        ],
        "tags": ["state", "patterns"],
        "gotchas": ["Lifting state too high re-renders large subtrees on every change; lift only as far as necessary.", "Forgetting to pass the setter down leaves children unable to update the shared value."],
        "follow_ups": ["At what point does repeated lifting signal you should reach for context or a store?", "How does lifting state relate to making a component controlled?"],
    },
    {
        "slug": "react-error-boundaries",
        "question": "What are error boundaries, what do they catch, and what don't they catch?",
        "difficulty": "MEDIUM",
        "tldr": "Error boundaries are components that catch render-phase errors in their child tree and render a fallback UI. They do NOT catch errors in event handlers, async code, SSR, or the boundary itself.",
        "explanation": "An error boundary is a class component implementing getDerivedStateFromError (to render a fallback) and/or componentDidCatch (to log). It catches errors thrown during rendering, in lifecycle methods, and in constructors of the components below it. It deliberately ignores errors in event handlers, async callbacks, server rendering, and errors thrown inside the boundary component itself.",
        "code_examples": [
            {"language": "tsx", "label": "A class-based error boundary",
             "code": "class ErrorBoundary extends React.Component<{ children: React.ReactNode }, { hasError: boolean }> {\n  state = { hasError: false };\n  static getDerivedStateFromError() {\n    return { hasError: true };\n  }\n  componentDidCatch(error: Error) {\n    console.error(error);\n  }\n  render() {\n    return this.state.hasError ? <h1>Something went wrong</h1> : this.props.children;\n  }\n}"},
        ],
        "tags": ["error-handling", "patterns"],
        "gotchas": ["Event handler errors aren't caught — wrap that logic in try/catch and set state manually.", "There is still no hook-based error boundary; you must use a class or a library like react-error-boundary."],
        "follow_ups": ["How do you catch errors from async code or event handlers and surface them to a boundary?", "How does placement granularity of boundaries affect the user experience on failure?"],
    },
    {
        "slug": "react-usetransition-concurrent",
        "question": "What problem does useTransition solve in concurrent React, and how does it work?",
        "difficulty": "HARD",
        "tldr": "useTransition marks state updates as non-urgent transitions so React can keep the UI responsive to urgent input while rendering the heavy update in the background and interrupting it if needed.",
        "explanation": "Concurrent rendering lets React interrupt and prioritize work. Wrapping an expensive state update in startTransition tells React it's low priority, so urgent updates like typing stay snappy and the transition can be paused or thrown away. useTransition also gives an isPending flag to show a subtle loading state without blocking the input.",
        "code_examples": [
            {"language": "tsx", "label": "Keeping input responsive with a transition",
             "code": "function SearchResults() {\n  const [query, setQuery] = useState(\"\");\n  const [list, setList] = useState<string[]>([]);\n  const [isPending, startTransition] = useTransition();\n\n  function onChange(e: React.ChangeEvent<HTMLInputElement>) {\n    setQuery(e.target.value); // urgent\n    startTransition(() => {\n      setList(computeExpensiveResults(e.target.value)); // non-urgent\n    });\n  }\n  return <input value={query} onChange={onChange} aria-busy={isPending} />;\n}"},
        ],
        "tags": ["concurrent", "performance"],
        "gotchas": ["Transitions are for state updates you control, not for arbitrary code — only setState calls inside startTransition are deprioritized.", "Don't put controlled-input value updates inside a transition or the field will lag behind keystrokes."],
        "follow_ups": ["How does useDeferredValue differ from useTransition for the same kind of problem?", "How do transitions interact with Suspense boundaries to avoid jarring fallbacks?"],
    },
    {
        "slug": "react-immutability-state",
        "question": "Why does React require immutable updates to state, and what breaks if you mutate?",
        "difficulty": "HARD",
        "tldr": "React decides whether to re-render by comparing state references with Object.is. Mutating an object or array in place keeps the same reference, so React sees no change and skips the update.",
        "explanation": "State updates must produce a new reference for objects and arrays because React (and React.memo, useMemo, dependency arrays) rely on shallow reference equality to detect changes. Mutating in place (e.g. arr.push) leaves the reference identical, so bail-out logic concludes nothing changed and the UI goes stale. Always create a new object/array with spread, map, or filter — or use Immer for ergonomic immutable updates.",
        "code_examples": [
            {"language": "tsx", "label": "Mutation vs immutable update",
             "code": "function TodoApp() {\n  const [todos, setTodos] = useState<string[]>([]);\n\n  function addBad(text: string) {\n    todos.push(text); // same array reference — no re-render\n    setTodos(todos);\n  }\n  function addGood(text: string) {\n    setTodos((prev) => [...prev, text]); // new array — re-renders\n  }\n  return <button onClick={() => addGood(\"new\")}>Add</button>;\n}"},
        ],
        "tags": ["state", "immutability"],
        "gotchas": ["Nested mutation (state.a.b = x) is just as broken even if you spread the top level — copy every level you change.", "Mutating then setting the same reference can sometimes 'work' by accident on an unrelated re-render, masking the bug."],
        "follow_ups": ["How does Immer let you write mutating syntax while producing immutable updates?", "Why does shallow comparison make deep nested updates verbose, and how do you manage that?"],
    },
]
