QUESTIONS = [
    {
        "slug": "sql-inner-vs-outer-joins",
        "question": "What is the difference between INNER JOIN, LEFT JOIN, RIGHT JOIN, and FULL OUTER JOIN?",
        "difficulty": "EASY",
        "tldr": "INNER returns only matching rows; LEFT/RIGHT keep all rows from one side (NULLs for non-matches); FULL keeps all rows from both sides.",
        "explanation": "An INNER JOIN returns only rows where the join predicate matches in both tables. A LEFT JOIN returns every row from the left table plus matched right rows (NULLs where no match), and RIGHT JOIN does the mirror image. A FULL OUTER JOIN returns all rows from both tables, filling NULLs wherever a side has no match.",
        "code_examples": [
            {"language": "sql", "label": "LEFT vs INNER",
             "code": "-- All customers, with their orders if any (NULL columns when none)\nSELECT c.id, c.name, o.total\nFROM customers c\nLEFT JOIN orders o ON o.customer_id = c.id;\n\n-- Only customers who actually placed an order\nSELECT c.id, c.name, o.total\nFROM customers c\nINNER JOIN orders o ON o.customer_id = c.id;"},
        ],
        "tags": ["joins", "basics"],
        "gotchas": ["Putting a condition on the right table in WHERE (e.g. o.status='X') silently turns a LEFT JOIN back into an INNER JOIN because NULLs fail the predicate; put such conditions in the ON clause.", "MySQL has no native FULL OUTER JOIN; emulate it with LEFT JOIN UNION RIGHT JOIN."],
        "follow_ups": ["How would you find customers who have NO orders using a LEFT JOIN?", "What is a CROSS JOIN and when is it useful?"],
    },
    {
        "slug": "sql-primary-unique-foreign-keys",
        "question": "What is the difference between a PRIMARY KEY, a UNIQUE constraint, and a FOREIGN KEY?",
        "difficulty": "EASY",
        "tldr": "PRIMARY KEY is one unique, non-NULL row identifier per table; UNIQUE enforces distinct values (NULLs allowed); FOREIGN KEY references a key in another table.",
        "explanation": "A PRIMARY KEY uniquely identifies each row, cannot be NULL, and a table has at most one. A UNIQUE constraint also forbids duplicates but a table can have many and (in most engines) permits NULLs. A FOREIGN KEY enforces referential integrity by requiring values to exist as a key in a referenced table.",
        "code_examples": [
            {"language": "sql", "label": "All three constraints",
             "code": "CREATE TABLE users (\n  id    BIGINT PRIMARY KEY,\n  email VARCHAR(255) UNIQUE NOT NULL\n);\n\nCREATE TABLE orders (\n  id      BIGINT PRIMARY KEY,\n  user_id BIGINT NOT NULL,\n  FOREIGN KEY (user_id) REFERENCES users(id)\n);"},
        ],
        "tags": ["keys", "constraints"],
        "gotchas": ["Most databases allow multiple NULLs in a UNIQUE column because NULL != NULL, so UNIQUE does not guarantee 'at most one missing value'.", "A foreign key column is not automatically indexed in some engines, which can make ON DELETE checks and joins slow."],
        "follow_ups": ["What happens to child rows on ON DELETE CASCADE vs ON DELETE RESTRICT?", "Can a foreign key reference a UNIQUE column instead of a primary key?"],
    },
    {
        "slug": "sql-where-vs-having",
        "question": "What is the difference between WHERE and HAVING?",
        "difficulty": "EASY",
        "tldr": "WHERE filters individual rows before grouping; HAVING filters groups after aggregation and can reference aggregate functions.",
        "explanation": "WHERE is applied before rows are grouped, so it cannot reference aggregate results. HAVING is applied after GROUP BY and aggregation, so it can filter on aggregates like COUNT or SUM. Using WHERE to pre-filter rows is also usually faster because it shrinks the set before grouping.",
        "code_examples": [
            {"language": "sql", "label": "WHERE then HAVING",
             "code": "SELECT customer_id, COUNT(*) AS order_count\nFROM orders\nWHERE status = 'completed'        -- filter rows first\nGROUP BY customer_id\nHAVING COUNT(*) > 5;              -- filter groups after"},
        ],
        "tags": ["aggregation", "filtering"],
        "gotchas": ["You cannot reference a SELECT alias in WHERE/HAVING in most engines because aliases are resolved after these clauses logically run.", "Putting a non-aggregate condition in HAVING that belongs in WHERE works but wastes effort by grouping rows you will discard."],
        "follow_ups": ["What is the logical order of evaluation of SQL clauses?", "Can HAVING be used without GROUP BY?"],
    },
    {
        "slug": "sql-aggregate-functions",
        "question": "What are aggregate functions and how do COUNT(*) and COUNT(column) differ?",
        "difficulty": "EASY",
        "tldr": "Aggregates collapse many rows into one value; COUNT(*) counts all rows while COUNT(col) counts only non-NULL values in that column.",
        "explanation": "Aggregate functions like COUNT, SUM, AVG, MIN, and MAX reduce a set of rows to a single value, typically per group when combined with GROUP BY. COUNT(*) counts every row including those with NULLs, whereas COUNT(column) ignores rows where that column is NULL. COUNT(DISTINCT column) counts unique non-NULL values.",
        "code_examples": [
            {"language": "sql", "label": "COUNT variants",
             "code": "SELECT\n  COUNT(*)              AS all_rows,\n  COUNT(phone)          AS rows_with_phone,\n  COUNT(DISTINCT city)  AS distinct_cities,\n  AVG(age)              AS avg_age\nFROM users;"},
        ],
        "tags": ["aggregation", "null"],
        "gotchas": ["AVG and SUM silently ignore NULLs, so AVG over a column with NULLs is total/non_null_count, not total/row_count.", "SUM of an empty set returns NULL, not 0, which can break downstream arithmetic."],
        "follow_ups": ["How would you compute an average that treats NULLs as zero?", "What does GROUP BY with no aggregate in SELECT return?"],
    },
    {
        "slug": "sql-group-by-basics",
        "question": "How does GROUP BY work and what can appear in the SELECT list with it?",
        "difficulty": "EASY",
        "tldr": "GROUP BY collapses rows sharing the grouped values into one row per group; non-aggregated SELECT columns must appear in GROUP BY.",
        "explanation": "GROUP BY partitions rows into groups that share the same values for the listed columns, producing one output row per group. Any column in the SELECT list that is not wrapped in an aggregate function must appear in the GROUP BY clause (standard SQL and PostgreSQL enforce this). MySQL historically allowed selecting non-grouped columns, returning an arbitrary value, which is a common source of bugs.",
        "code_examples": [
            {"language": "sql", "label": "Per-group aggregation",
             "code": "SELECT department, COUNT(*) AS headcount, AVG(salary) AS avg_salary\nFROM employees\nGROUP BY department\nORDER BY avg_salary DESC;"},
        ],
        "tags": ["aggregation", "basics"],
        "gotchas": ["Selecting a non-aggregated, non-grouped column errors in PostgreSQL but silently returns an arbitrary row's value in MySQL unless ONLY_FULL_GROUP_BY is enabled.", "GROUP BY treats all NULLs as a single group, unlike most equality comparisons."],
        "follow_ups": ["What is the difference between GROUP BY and DISTINCT?", "How do GROUPING SETS, ROLLUP, and CUBE extend GROUP BY?"],
    },
    {
        "slug": "sql-union-vs-union-all",
        "question": "What is the difference between UNION and UNION ALL?",
        "difficulty": "EASY",
        "tldr": "UNION removes duplicate rows (requiring a sort/hash dedup); UNION ALL concatenates results keeping duplicates and is faster.",
        "explanation": "Both combine the result sets of two queries that have compatible column counts and types. UNION eliminates duplicate rows across the combined set, which forces an expensive sort or hash step. UNION ALL simply concatenates the rows without deduplication, so it is faster and preferred when you know there are no duplicates or duplicates are acceptable.",
        "code_examples": [
            {"language": "sql", "label": "UNION vs UNION ALL",
             "code": "-- Deduplicated set of all emails (slower)\nSELECT email FROM customers\nUNION\nSELECT email FROM leads;\n\n-- Keep every row, no dedup work (faster)\nSELECT email FROM customers\nUNION ALL\nSELECT email FROM leads;"},
        ],
        "tags": ["set-operations"],
        "gotchas": ["UNION's implicit deduplication can mask data problems and adds a hidden sort cost on large sets — default to UNION ALL unless dedup is truly needed.", "Only the last query in a UNION chain may have ORDER BY, and it applies to the whole combined result."],
        "follow_ups": ["How do INTERSECT and EXCEPT/MINUS relate to UNION?", "Why must the columns have compatible types across UNION branches?"],
    },
    {
        "slug": "sql-indexes-and-btrees",
        "question": "How does a B-tree index speed up queries, and what operations can it accelerate?",
        "difficulty": "MEDIUM",
        "tldr": "A B-tree keeps keys sorted in a balanced tree, giving O(log n) lookups and supporting equality, range, prefix, and ORDER BY without a full scan.",
        "explanation": "Most relational indexes are balanced B-trees (technically B+ trees) where leaf nodes hold sorted key values pointing to rows. This logarithmic structure lets the engine seek directly to a value or range instead of scanning every row. Because leaves are ordered, a B-tree also serves range scans (BETWEEN, <, >), prefix LIKE 'abc%', and can satisfy ORDER BY in index order.",
        "code_examples": [
            {"language": "sql", "label": "Range scan on a B-tree index",
             "code": "CREATE INDEX idx_orders_created ON orders (created_at);\n\n-- Uses the index for a range seek instead of a full scan\nSELECT * FROM orders\nWHERE created_at >= '2026-01-01'\nORDER BY created_at;"},
        ],
        "tags": ["indexes", "performance"],
        "gotchas": ["Wrapping the indexed column in a function (WHERE DATE(created_at)='...') prevents the engine from using the index unless you create a matching expression/functional index.", "Leading wildcard LIKE '%abc' cannot use a B-tree index because the prefix is unknown."],
        "follow_ups": ["When would a hash index or GIN/GiST index beat a B-tree?", "Why is a B+ tree preferred over a plain B-tree for databases?"],
    },
    {
        "slug": "sql-when-indexes-hurt",
        "question": "When do indexes hurt rather than help performance?",
        "difficulty": "MEDIUM",
        "tldr": "Indexes slow down writes and consume space; on low-selectivity columns or small tables they add overhead while the planner may still prefer a full scan.",
        "explanation": "Every index must be updated on INSERT, UPDATE, and DELETE, so over-indexing degrades write throughput and increases storage. Indexes on low-cardinality columns (like a boolean flag) are rarely useful because the planner often chooses a sequential scan when a query returns a large fraction of rows. Redundant or overlapping indexes also waste space and confuse the optimizer.",
        "code_examples": [
            {"language": "sql", "label": "Low-selectivity vs partial index",
             "code": "-- Low selectivity: is_active is true for ~95% of rows; planner ignores it.\nCREATE INDEX idx_users_active ON users (is_active);\n\n-- A partial index is far more useful for the rare case:\nCREATE INDEX idx_users_inactive ON users (id) WHERE is_active = false;"},
        ],
        "tags": ["indexes", "performance"],
        "gotchas": ["Adding indexes to a write-heavy table can cripple throughput; benchmark write impact, not just read speedups.", "Two indexes (a) and (a,b) are partially redundant — the single-column one is usually covered by the composite's leading column."],
        "follow_ups": ["How do you detect unused indexes in production?", "What is index bloat and how do you reclaim it?"],
    },
    {
        "slug": "sql-explain-execution-plans",
        "question": "What is a query execution plan and how do you read EXPLAIN / EXPLAIN ANALYZE output?",
        "difficulty": "MEDIUM",
        "tldr": "EXPLAIN shows the planner's chosen operators (scans, joins) with cost estimates; EXPLAIN ANALYZE actually runs the query and reports real timings and row counts.",
        "explanation": "A query execution plan is the tree of physical operators the optimizer chooses — sequential scans, index scans, nested-loop/hash/merge joins, sorts, and aggregations. EXPLAIN prints estimated costs and row counts without running the query, while EXPLAIN ANALYZE executes it and shows actual time and rows so you can spot bad estimates. The key signals are large gaps between estimated and actual rows, unexpected sequential scans on big tables, and expensive sorts or nested loops.",
        "code_examples": [
            {"language": "sql", "label": "EXPLAIN ANALYZE in PostgreSQL",
             "code": "EXPLAIN ANALYZE\nSELECT o.id, c.name\nFROM orders o\nJOIN customers c ON c.id = o.customer_id\nWHERE o.created_at >= '2026-01-01';\n\n-- Look for: Seq Scan vs Index Scan, estimated vs actual rows, join method."},
        ],
        "tags": ["explain", "performance"],
        "gotchas": ["EXPLAIN ANALYZE actually executes the statement, so running it on an INSERT/UPDATE/DELETE mutates data — wrap it in a rolled-back transaction.", "A large divergence between estimated and actual rows usually means stale statistics; run ANALYZE/refresh stats."],
        "follow_ups": ["How do nested-loop, hash, and merge joins differ in cost characteristics?", "What does a 'Rows Removed by Filter' line tell you about index opportunities?"],
    },
    {
        "slug": "sql-normalization-normal-forms",
        "question": "What is normalization, and what do 1NF, 2NF, and 3NF require?",
        "difficulty": "MEDIUM",
        "tldr": "Normalization removes redundancy via dependency rules: 1NF atomic columns, 2NF no partial key dependencies, 3NF no transitive dependencies on non-key columns.",
        "explanation": "Normalization organizes columns and tables to minimize redundancy and update anomalies. 1NF requires atomic (indivisible) column values and no repeating groups. 2NF (on a composite key) removes attributes that depend on only part of the key, and 3NF removes transitive dependencies where a non-key column depends on another non-key column.",
        "code_examples": [
            {"language": "sql", "label": "Removing a transitive dependency",
             "code": "-- Violates 3NF: zip determines city (transitive dependency).\n-- 3NF: factor the zip->city dependency into its own table.\nCREATE TABLE zip_codes (zip CHAR(5) PRIMARY KEY, city VARCHAR(100));\nCREATE TABLE orders (\n  order_id    BIGINT PRIMARY KEY,\n  customer_id BIGINT,\n  zip         CHAR(5) REFERENCES zip_codes(zip)\n);"},
        ],
        "tags": ["normalization", "schema-design"],
        "gotchas": ["Storing comma-separated lists in a single column violates 1NF and makes filtering/joining painful — use a child table.", "Over-normalizing forces many joins for common reads; sometimes 3NF must be relaxed deliberately for performance."],
        "follow_ups": ["How does BCNF differ from 3NF?", "What update, insert, and delete anomalies does normalization prevent?"],
    },
    {
        "slug": "sql-transactions-acid",
        "question": "What does ACID mean and what guarantees does each property give?",
        "difficulty": "MEDIUM",
        "tldr": "Atomicity = all-or-nothing; Consistency = constraints preserved; Isolation = concurrent txns don't corrupt each other; Durability = committed data survives crashes.",
        "explanation": "A transaction is a unit of work bounded by BEGIN and COMMIT/ROLLBACK. Atomicity guarantees all statements succeed or none do; Consistency ensures the database moves from one valid state to another respecting constraints; Isolation prevents concurrent transactions from seeing each other's incomplete work (to a degree set by the isolation level); Durability guarantees a committed transaction persists even after a crash.",
        "code_examples": [
            {"language": "sql", "label": "Atomic money transfer",
             "code": "BEGIN;\n  UPDATE accounts SET balance = balance - 100 WHERE id = 1;\n  UPDATE accounts SET balance = balance + 100 WHERE id = 2;\n-- If either statement fails, ROLLBACK leaves balances untouched.\nCOMMIT;"},
        ],
        "tags": ["transactions", "acid"],
        "gotchas": ["Durability depends on disk flush settings — async commit or disabled fsync trades durability for speed and can lose committed data on power loss.", "Many engines auto-commit each statement unless you explicitly open a transaction, so forgetting BEGIN means no atomicity across statements."],
        "follow_ups": ["How does a write-ahead log (WAL) provide both atomicity and durability?", "Does ACID hold across multiple nodes in a distributed database?"],
    },
    {
        "slug": "sql-isolation-levels-anomalies",
        "question": "What are the SQL isolation levels and which read anomalies does each prevent?",
        "difficulty": "HARD",
        "tldr": "READ UNCOMMITTED allows dirty reads; READ COMMITTED blocks them; REPEATABLE READ blocks non-repeatable reads; SERIALIZABLE blocks phantoms and gives full serial equivalence.",
        "explanation": "The SQL standard defines four isolation levels trading consistency for concurrency. Dirty reads (seeing uncommitted data), non-repeatable reads (a row changes between two reads), and phantom reads (new rows appear matching a predicate) are progressively eliminated as you raise the level. SERIALIZABLE behaves as if transactions ran one at a time, but implementations differ — Postgres uses snapshot-based SSI while others use locking.",
        "code_examples": [
            {"language": "sql", "label": "Isolation level matrix",
             "code": "-- Level            | Dirty | Non-repeatable | Phantom\n-- READ UNCOMMITTED |  yes  |      yes       |  yes\n-- READ COMMITTED   |  no   |      yes       |  yes\n-- REPEATABLE READ  |  no   |      no        |  yes*\n-- SERIALIZABLE     |  no   |      no        |  no\n\nSET TRANSACTION ISOLATION LEVEL SERIALIZABLE;"},
        ],
        "tags": ["isolation", "concurrency"],
        "gotchas": ["PostgreSQL's REPEATABLE READ (snapshot isolation) already prevents phantom reads, unlike the SQL standard's minimum — vendor behavior varies.", "SERIALIZABLE can abort transactions with serialization failures; your app must catch the error and retry."],
        "follow_ups": ["What is write skew and why does snapshot isolation permit it?", "How does MVCC implement READ COMMITTED without read locks?"],
    },
    {
        "slug": "sql-window-functions",
        "question": "What are window functions, and how do ROW_NUMBER, RANK, and DENSE_RANK differ?",
        "difficulty": "MEDIUM",
        "tldr": "Window functions compute across a set of rows related to the current row without collapsing them; ROW_NUMBER is always unique, RANK skips after ties, DENSE_RANK does not.",
        "explanation": "Unlike aggregates with GROUP BY, window functions (OVER (...)) produce a value per row while retaining all rows, optionally partitioned and ordered. ROW_NUMBER assigns a strictly increasing unique number within each partition. RANK gives tied rows the same rank then skips numbers (1,1,3), while DENSE_RANK gives ties the same rank with no gaps (1,1,2).",
        "code_examples": [
            {"language": "sql", "label": "ROW_NUMBER vs RANK vs DENSE_RANK",
             "code": "SELECT\n  name, department, salary,\n  ROW_NUMBER() OVER (PARTITION BY department ORDER BY salary DESC) AS rn,\n  RANK()       OVER (PARTITION BY department ORDER BY salary DESC) AS rnk,\n  DENSE_RANK() OVER (PARTITION BY department ORDER BY salary DESC) AS dense\nFROM employees;"},
        ],
        "tags": ["window-functions", "analytics"],
        "gotchas": ["Window functions run after WHERE/GROUP BY/HAVING, so you cannot filter on a window result in WHERE — wrap the query in a CTE/subquery first.", "ROW_NUMBER over a non-deterministic ORDER BY (ties with no tiebreaker) can return different numbering across runs."],
        "follow_ups": ["How would you fetch the top 3 earners per department using a window function?", "What does the frame clause (ROWS BETWEEN ...) control?"],
    },
    {
        "slug": "sql-n-plus-one-query-problem",
        "question": "What is the N+1 query problem and how do you fix it?",
        "difficulty": "MEDIUM",
        "tldr": "N+1 is issuing one query to fetch a list then one extra query per item; fix it with a JOIN, an IN-batch, or eager loading.",
        "explanation": "The N+1 problem occurs when code fetches N parent rows with one query, then loops issuing a separate query per parent to load related rows — N additional round trips. The total of N+1 queries multiplies network and parsing overhead and scales terribly. The fix is to load the related data in a single set-based query via a JOIN or a batched WHERE IN, or to enable an ORM's eager/prefetch loading.",
        "code_examples": [
            {"language": "sql", "label": "Collapsing N+1 into one join",
             "code": "-- N+1: 1 query for posts, then one per post for its author.\n-- Fix: a single join (or WHERE id IN (...) batch)\nSELECT p.*, u.name AS author\nFROM posts p\nJOIN users u ON u.id = p.author_id;"},
        ],
        "tags": ["orm", "performance"],
        "gotchas": ["ORM lazy loading hides N+1 behind innocent-looking property access in a loop; enable query logging to spot the burst of identical queries.", "Eager-loading everything can swing to the opposite extreme, pulling huge JOIN result sets you don't need."],
        "follow_ups": ["How does a DataLoader-style batch-and-cache approach solve N+1 in GraphQL?", "When is N+1 with a small N actually fine compared to a giant join?"],
    },
    {
        "slug": "sql-subqueries-vs-ctes",
        "question": "What is the difference between subqueries and CTEs, and when should you use each?",
        "difficulty": "MEDIUM",
        "tldr": "CTEs (WITH) name a result for readability and reuse and enable recursion; subqueries are inline. Modern planners often treat both similarly, but CTEs aid clarity.",
        "explanation": "A subquery is a query nested inside another (in SELECT, FROM, or WHERE), while a Common Table Expression uses WITH to define a named, reusable result set at the top of the statement. CTEs improve readability, can be referenced multiple times, and support recursion for hierarchical data. Performance is usually comparable, though older PostgreSQL versions materialized CTEs as an optimization fence.",
        "code_examples": [
            {"language": "sql", "label": "CTE for clarity",
             "code": "WITH ranked AS (\n  SELECT id, customer_id, total,\n         ROW_NUMBER() OVER (PARTITION BY customer_id ORDER BY total DESC) AS rn\n  FROM orders\n)\nSELECT * FROM ranked WHERE rn = 1;  -- each customer's largest order"},
        ],
        "tags": ["cte", "subqueries"],
        "gotchas": ["PostgreSQL before v12 always materialized CTEs (an optimization fence), so an inline subquery could be faster; v12+ inlines non-recursive CTEs unless you say MATERIALIZED.", "A correlated subquery re-runs per outer row and can be far slower than an equivalent JOIN."],
        "follow_ups": ["How do you write a recursive CTE to walk an org-chart hierarchy?", "What is the difference between a correlated and an uncorrelated subquery?"],
    },
    {
        "slug": "sql-composite-index-column-order",
        "question": "Why does column order matter in a composite (multi-column) index?",
        "difficulty": "HARD",
        "tldr": "A composite index is sorted left-to-right; it serves predicates that use a leftmost prefix, so the leading column's selectivity and usage drive the order.",
        "explanation": "A composite index on (a, b, c) physically sorts rows by a, then b, then c. The optimizer can use it for queries filtering on a, on (a,b), or (a,b,c) — the leftmost-prefix rule — but generally not for a query that filters only on b or c. Therefore the most selective and most frequently filtered column usually belongs first, with range columns placed last so equality columns can still seek.",
        "code_examples": [
            {"language": "sql", "label": "Leftmost-prefix rule",
             "code": "CREATE INDEX idx_events ON events (tenant_id, created_at);\n\n-- Uses the index (leftmost prefix on tenant_id, range on created_at)\nSELECT * FROM events\nWHERE tenant_id = 7 AND created_at >= '2026-01-01';\n\n-- Cannot use it efficiently: skips the leading column\nSELECT * FROM events WHERE created_at >= '2026-01-01';"},
        ],
        "tags": ["indexes", "composite"],
        "gotchas": ["Placing a range/inequality column before an equality column in the index kills the ability to seek on the columns after the range.", "An index on (a,b) does not help a query filtering only on b."],
        "follow_ups": ["How does the optimizer use an index skip scan when the leading column is absent?", "Where should an ORDER BY column go in a composite index?"],
    },
    {
        "slug": "sql-covering-indexes",
        "question": "What is a covering index and how does it avoid table lookups?",
        "difficulty": "HARD",
        "tldr": "A covering index contains every column a query needs, so the engine answers entirely from the index without visiting the table (an index-only scan).",
        "explanation": "Normally an index scan finds matching keys then fetches full rows from the heap/table for any columns not in the index. A covering index includes all columns referenced by the query — in the key or via INCLUDE — so the engine performs an index-only scan and skips the costly heap fetches. This dramatically speeds up read-heavy queries at the cost of a larger index and slower writes.",
        "code_examples": [
            {"language": "sql", "label": "Covering index with INCLUDE",
             "code": "-- Index covers the WHERE column and the SELECTed column\nCREATE INDEX idx_orders_cover\n  ON orders (customer_id) INCLUDE (total);\n\n-- Index-only scan: total comes from the index, no heap fetch\nSELECT total FROM orders WHERE customer_id = 99;"},
        ],
        "tags": ["indexes", "covering"],
        "gotchas": ["In PostgreSQL an index-only scan still consults the visibility map; on a recently updated table it may fall back to heap fetches until VACUUM runs.", "Adding many INCLUDE columns bloats the index and slows writes — only cover columns for hot queries."],
        "follow_ups": ["What is the difference between INCLUDE columns and adding them as key columns?", "How do clustered indexes change covering behavior in SQL Server / InnoDB?"],
    },
    {
        "slug": "sql-offset-vs-keyset-pagination",
        "question": "Why is OFFSET pagination slow on deep pages, and how does keyset (seek) pagination fix it?",
        "difficulty": "HARD",
        "tldr": "OFFSET must scan and discard all skipped rows, so deep pages get slower linearly; keyset pagination uses a WHERE on the last seen value to seek directly via an index.",
        "explanation": "LIMIT/OFFSET forces the database to compute and throw away every row before the offset, so page 10,000 reads through 200,000 rows even to return 20. Keyset (cursor/seek) pagination instead remembers the sort key of the last row and filters WHERE key > last_value, letting an index jump straight to the next page in roughly constant time. The tradeoff is you cannot jump to an arbitrary page number, only forward/back relative to a cursor.",
        "code_examples": [
            {"language": "sql", "label": "OFFSET vs keyset",
             "code": "-- Slow on deep pages: scans and discards 100000 rows\nSELECT * FROM posts ORDER BY id LIMIT 20 OFFSET 100000;\n\n-- Keyset: seeks via index using the last id from the previous page\nSELECT * FROM posts\nWHERE id > 100000\nORDER BY id\nLIMIT 20;"},
        ],
        "tags": ["pagination", "performance"],
        "gotchas": ["Keyset pagination needs a unique, stable, indexed sort key; sorting by a non-unique column requires a composite tiebreaker (e.g. (created_at, id)) or pages can skip/duplicate rows.", "OFFSET pagination can also skip or duplicate rows when underlying data changes between page loads."],
        "follow_ups": ["How do you implement keyset pagination when sorting by a non-unique column?", "How would you support 'jump to page N' UX without OFFSET?"],
    },
    {
        "slug": "sql-deadlocks",
        "question": "What causes a database deadlock and how do you prevent and handle it?",
        "difficulty": "HARD",
        "tldr": "A deadlock is a cycle where two transactions each hold a lock the other needs; the engine kills one as a victim. Prevent it with consistent lock ordering and short transactions.",
        "explanation": "A deadlock arises when transaction A holds lock X and waits for lock Y while transaction B holds Y and waits for X, forming a wait-for cycle. The database's deadlock detector breaks the cycle by aborting one transaction with a deadlock error, which the application must catch and retry. The most effective prevention is acquiring locks in a consistent order across all code paths and keeping transactions short.",
        "code_examples": [
            {"language": "sql", "label": "Consistent lock ordering",
             "code": "-- Tx1 locks row 1 then 2; Tx2 locks row 2 then 1 -> deadlock.\n-- Fix: always lock rows in ascending id order in BOTH transactions.\nBEGIN;\n  UPDATE accounts SET balance = balance - 50\n  WHERE id IN (1, 2) ORDER BY id;\nCOMMIT;"},
        ],
        "tags": ["concurrency", "locking"],
        "gotchas": ["Even SELECT ... FOR UPDATE on rows acquired in inconsistent order across requests can deadlock, not just UPDATEs.", "Retrying on deadlock is mandatory, but blind retry loops without backoff or idempotency can amplify the problem."],
        "follow_ups": ["How does lock escalation contribute to deadlocks?", "How can you read a deadlock graph from the database logs?"],
    },
    {
        "slug": "sql-null-three-valued-logic",
        "question": "How does NULL behave in SQL's three-valued logic, and what surprises does it cause?",
        "difficulty": "MEDIUM",
        "tldr": "NULL means 'unknown'; comparisons with NULL yield UNKNOWN (not true/false), so use IS NULL, and NOT IN with NULLs can return no rows.",
        "explanation": "SQL uses three-valued logic: TRUE, FALSE, and UNKNOWN. Any comparison involving NULL (like x = NULL or x <> 5 when x is NULL) evaluates to UNKNOWN, and WHERE only keeps rows where the predicate is TRUE. This is why you must test with IS NULL / IS NOT NULL, and why NOT IN against a subquery that contains a NULL surprisingly returns zero rows.",
        "code_examples": [
            {"language": "sql", "label": "NULL comparison pitfalls",
             "code": "-- WRONG: never matches, because = NULL is UNKNOWN\nSELECT * FROM users WHERE manager_id = NULL;\n\n-- RIGHT:\nSELECT * FROM users WHERE manager_id IS NULL;\n\n-- Trap: if the subquery returns any NULL, this yields NO rows\nSELECT * FROM users\nWHERE id NOT IN (SELECT manager_id FROM users);"},
        ],
        "tags": ["null", "logic"],
        "gotchas": ["NOT IN (subquery) returns an empty result if the subquery yields even one NULL; prefer NOT EXISTS to avoid this.", "UNIQUE constraints, GROUP BY, and DISTINCT treat NULLs as equal, but the = operator does not — inconsistent semantics catch people out."],
        "follow_ups": ["Why does NOT EXISTS handle NULLs correctly where NOT IN fails?", "How does COALESCE differ from NULLIF, and when use each?"],
    },
    {
        "slug": "sql-denormalization-tradeoffs",
        "question": "What is denormalization and what are its tradeoffs?",
        "difficulty": "MEDIUM",
        "tldr": "Denormalization deliberately duplicates or precomputes data to speed reads, trading write complexity and risk of inconsistency for fewer joins.",
        "explanation": "Denormalization intentionally introduces redundancy — copying columns, storing precomputed aggregates, or flattening relationships — to avoid expensive joins and accelerate read-heavy workloads. The cost is that the same fact now lives in multiple places, so every write must update all copies or risk drift. It is a deliberate, measured tradeoff applied after profiling, not a default design.",
        "code_examples": [
            {"language": "sql", "label": "Denormalized counter cache",
             "code": "-- Maintain a precomputed counter instead of COUNT(*) on every read\nALTER TABLE posts ADD COLUMN comment_count INT NOT NULL DEFAULT 0;\n\n-- Writers must keep it in sync (trigger or app logic):\nUPDATE posts SET comment_count = comment_count + 1\nWHERE id = :post_id;"},
        ],
        "tags": ["denormalization", "schema-design"],
        "gotchas": ["Duplicated data drifts out of sync if any write path forgets to update a copy — use triggers, transactions, or scheduled reconciliation.", "Denormalizing prematurely adds write overhead and bugs before you have evidence joins are actually the bottleneck."],
        "follow_ups": ["How do materialized views compare to manual denormalization?", "How do you keep denormalized aggregates eventually consistent at scale?"],
    },
    {
        "slug": "sql-optimistic-vs-pessimistic-locking",
        "question": "What is the difference between optimistic and pessimistic locking?",
        "difficulty": "HARD",
        "tldr": "Pessimistic locking grabs a lock up front (SELECT ... FOR UPDATE); optimistic locking takes no lock and detects conflicts at write time via a version/timestamp check.",
        "explanation": "Pessimistic locking assumes conflicts are likely and locks the row when reading so no one else can modify it until you commit — safe but it serializes access and can cause blocking or deadlocks. Optimistic locking assumes conflicts are rare: it reads a version number, and on update checks the version is unchanged, failing the write if someone else modified the row. Optimistic suits low-contention, read-heavy workloads; pessimistic suits high-contention hotspots.",
        "code_examples": [
            {"language": "sql", "label": "Pessimistic vs optimistic",
             "code": "-- Pessimistic: lock the row for the duration of the transaction\nBEGIN;\n  SELECT balance FROM accounts WHERE id = 1 FOR UPDATE;\n  UPDATE accounts SET balance = balance - 100 WHERE id = 1;\nCOMMIT;\n\n-- Optimistic: update only if version matches; 0 rows => conflict, retry\nUPDATE accounts\nSET balance = 900, version = version + 1\nWHERE id = 1 AND version = 7;"},
        ],
        "tags": ["concurrency", "locking"],
        "gotchas": ["Optimistic locking requires the app to check the affected-row count and retry on zero — silently ignoring it loses the lost-update protection.", "Pessimistic FOR UPDATE held across a long transaction or user think-time blocks other writers and invites deadlocks."],
        "follow_ups": ["How does a version column compare to using a last_updated timestamp for optimistic locking?", "When would you combine SELECT ... FOR UPDATE SKIP LOCKED for a job queue?"],
    },
    {
        "slug": "sql-cache-aside-read-strategy",
        "question": "How does query result caching with a cache-aside strategy work alongside a relational database?",
        "difficulty": "MEDIUM",
        "tldr": "The app checks a cache (e.g. Redis) first, falls back to the database on a miss, stores the result, and invalidates the cache key on writes to keep it fresh.",
        "explanation": "Cache-aside (lazy loading) puts the application in control: on read it looks up the cache, and on a miss it queries the database and populates the cache with a TTL. On write, the app updates the database and then invalidates or updates the affected cache keys. This offloads expensive or hot read queries from the database, but you must handle invalidation carefully to avoid serving stale data.",
        "code_examples": [
            {"language": "sql", "label": "Read query backed by cache-aside",
             "code": "-- App pseudocode around this query:\n-- val = cache.get('user:42')\n-- if miss: val = run query; cache.set('user:42', val, ttl=300)\nSELECT id, name, email FROM users WHERE id = 42;\n\n-- On update, invalidate the key:\nUPDATE users SET name = 'New' WHERE id = 42;\n-- then cache.delete('user:42')"},
        ],
        "tags": ["caching", "performance"],
        "gotchas": ["Forgetting to invalidate the cache key on writes serves stale data until the TTL expires.", "A cache miss storm on a hot key can stampede the database; use locking or request coalescing."],
        "follow_ups": ["How does write-through caching differ from cache-aside?", "How do you prevent a cache stampede on a popular key?"],
    },
]
