QUESTIONS = [
    {
        "slug": "sysdesign-vertical-vs-horizontal-scaling",
        "question": "What is the difference between vertical and horizontal scaling, and when would you choose each?",
        "difficulty": "EASY",
        "tldr": "Vertical scaling adds more power to one machine; horizontal scaling adds more machines. Vertical is simpler but capped by hardware; horizontal is harder but nearly unbounded.",
        "explanation": "Vertical scaling (scaling up) means upgrading a single server's CPU, RAM, or disk. It's simple and avoids distributed-systems complexity, but hits a hard ceiling and creates a single point of failure. Horizontal scaling (scaling out) adds more nodes behind a load balancer, offering near-linear capacity and redundancy, but requires stateless services, data partitioning, and coordination.",
        "code_examples": [
            {"language": "text", "label": "Scaling models compared",
             "code": "VERTICAL (scale up)         HORIZONTAL (scale out)\n  +-----------+               [Node][Node][Node]\n  | 16 CPU    |     --->            \\  |  /\n  | 128 GB    |                  [Load Balancer]\n  +-----------+\nUp:  easy, no code change, hard ceiling, SPOF\nOut: complex, needs stateless app, ~unlimited, redundant"},
        ],
        "tags": ["scaling", "fundamentals"],
        "gotchas": ["Vertical scaling requires downtime/reboot on many platforms and leaves a single point of failure.", "Horizontal scaling only works if your app is stateless or externalizes session/state."],
        "follow_ups": ["How do you make a stateful web app horizontally scalable?", "What is the practical upper limit of vertical scaling in cloud providers today?"],
    },
    {
        "slug": "sysdesign-caching-strategies",
        "question": "Explain the main caching write strategies: cache-aside, write-through, and write-back.",
        "difficulty": "MEDIUM",
        "tldr": "Cache-aside loads on miss and the app manages the cache; write-through writes cache and DB synchronously; write-back writes cache first and flushes to DB asynchronously.",
        "explanation": "Cache-aside (lazy loading) has the application check the cache, fall back to the DB on a miss, and populate the cache itself — simple but risks stale data without invalidation. Write-through keeps the cache and DB consistent by writing both on every write, at the cost of higher write latency. Write-back (write-behind) acknowledges writes from the cache immediately and persists to the DB asynchronously, maximizing write speed but risking data loss if the cache fails before flushing.",
        "code_examples": [
            {"language": "text", "label": "Three caching patterns",
             "code": "CACHE-ASIDE (read)        WRITE-THROUGH (write)     WRITE-BACK (write)\n  val = cache.get(k)        cache.set(k, v)           cache.set(k, v)\n  if miss:                  db.set(k, v)  (both       queue_async_flush(k,v)\n    val = db.get(k)         synchronously)            return OK (DB later)\n    cache.set(k, val)       return OK\n  return val"},
        ],
        "tags": ["caching", "consistency"],
        "gotchas": ["Cache-aside can serve stale data if writes don't invalidate the cached key.", "Write-back can lose recently acknowledged writes if the cache crashes before flushing to the database."],
        "follow_ups": ["How would you handle cache invalidation across multiple regions?", "Which strategy fits a write-heavy analytics ingest pipeline?"],
    },
    {
        "slug": "sysdesign-cache-eviction-and-ttl",
        "question": "Why do caches need eviction policies and TTLs, and how do LRU and LFU differ?",
        "difficulty": "EASY",
        "tldr": "Cache memory is finite, so eviction policies decide what to drop. LRU evicts the least recently used item; LFU evicts the least frequently used. TTLs bound staleness.",
        "explanation": "Because cache capacity is limited, an eviction policy chooses which entries to remove when full. LRU (Least Recently Used) discards the item untouched for the longest time and adapts well to temporal locality, while LFU (Least Frequently Used) discards the item with the fewest accesses, favoring long-term popular keys. A TTL (time-to-live) independently expires entries so data doesn't stay stale indefinitely regardless of access patterns.",
        "code_examples": [
            {"language": "text", "label": "LRU walkthrough with TTL note",
             "code": "Capacity = 3, access order: A B C  A  D\nLRU state (most-recent on right):\n  A B C       -> [A B C]\n  A (hit)     -> [B C A]\n  D (miss)    -> evict B -> [C A D]\n\nTTL: each entry stamped expires_at; read after expiry == miss."},
        ],
        "tags": ["caching", "fundamentals"],
        "gotchas": ["Pure LFU can cache forever items that were popular once but are now cold (cache pollution).", "A TTL that's too short defeats the cache; too long risks serving stale data."],
        "follow_ups": ["How does LRU-K or a segmented LRU improve on plain LRU?", "When would you prefer random eviction over LRU?"],
    },
    {
        "slug": "sysdesign-cdn-fundamentals",
        "question": "What is a CDN and how does it improve performance and availability?",
        "difficulty": "EASY",
        "tldr": "A CDN is a globally distributed network of edge caches that serve content from a location near the user, cutting latency, offloading the origin, and absorbing traffic spikes.",
        "explanation": "A Content Delivery Network places edge servers (PoPs) around the world that cache static and increasingly dynamic content close to users. Requests are routed to the nearest edge via DNS or anycast, reducing round-trip latency and offloading bandwidth from the origin. CDNs also improve availability by absorbing DDoS traffic and serving cached content even if the origin is temporarily down.",
        "code_examples": [
            {"language": "text", "label": "CDN edge caching flow",
             "code": "User (Tokyo) ---> Edge PoP (Tokyo)  [cache HIT -> instant]\n                       |\n                       | cache MISS\n                       v\n                  Origin (Virginia)  <-- one slow trip, then cached"},
        ],
        "tags": ["cdn", "performance"],
        "gotchas": ["Cache invalidation/purge propagation across edges is not instant — stale assets can linger.", "CDNs shine for static/cacheable content; uncacheable per-user dynamic responses still hit the origin."],
        "follow_ups": ["How do cache-control headers and ETags control CDN behavior?", "How would you serve personalized content while still using a CDN?"],
    },
    {
        "slug": "sysdesign-load-balancing-algorithms",
        "question": "Compare common load balancing algorithms: round robin, least connections, and consistent hashing.",
        "difficulty": "MEDIUM",
        "tldr": "Round robin distributes requests cyclically, least connections sends to the least busy server, and hash-based routing pins a key to a specific server for stickiness.",
        "explanation": "Round robin (and weighted round robin) cycles through servers evenly and is simple but ignores actual load. Least connections routes to the backend with the fewest active connections, which handles uneven request durations better. Hash-based or consistent-hash routing maps a request attribute (like user ID) to a fixed backend, providing session affinity and cache locality at the cost of uneven distribution if keys are skewed.",
        "code_examples": [
            {"language": "text", "label": "Algorithm selection examples",
             "code": "ROUND ROBIN      LEAST CONNECTIONS      IP/KEY HASH\nreq1 -> S1       S1: 5 conns            hash(uid)%N\nreq2 -> S2       S2: 2 conns <- pick    -> always S2\nreq3 -> S3       S3: 8 conns            (sticky)\nreq4 -> S1"},
        ],
        "tags": ["load-balancing", "scaling"],
        "gotchas": ["Round robin can overload a slow server because it ignores in-flight load.", "Plain modulo hashing reshuffles almost every key when the server count changes — use consistent hashing instead."],
        "follow_ups": ["What is the difference between L4 and L7 load balancing?", "How do health checks interact with the load balancing algorithm?"],
    },
    {
        "slug": "sysdesign-database-replication-leader-follower",
        "question": "How does leader-follower (primary-replica) database replication work, and what are its tradeoffs?",
        "difficulty": "MEDIUM",
        "tldr": "One leader accepts writes and streams its changelog to read-only followers. It scales reads and adds redundancy but introduces replication lag and write-path bottlenecks.",
        "explanation": "In leader-follower replication, all writes go to a single leader, which records changes to a replication log that followers apply to stay in sync. Read traffic can be spread across followers to scale read throughput, and a follower can be promoted if the leader fails. The main tradeoffs are replication lag (followers may serve stale reads) and the fact that the single leader remains the write bottleneck and a potential point of failure until failover completes.",
        "code_examples": [
            {"language": "text", "label": "Replication topology and sync modes",
             "code": "          writes\n   client ------> [ LEADER ] --replication log-->\n                     | reads             \\\n                     v                    v\n               [ Follower 2 ]      [ Follower 1 ] reads\n\nAsync: leader acks before followers apply -> fast, lag possible\nSync:  leader waits for follower ack       -> durable, slower"},
        ],
        "tags": ["replication", "databases"],
        "gotchas": ["Read-after-write can return stale data if the read hits a lagging follower right after a write.", "Asynchronous replication can lose the last committed writes if the leader dies before they replicate."],
        "follow_ups": ["How do you guarantee read-your-own-writes with replicas?", "What changes with multi-leader or leaderless (quorum) replication?"],
    },
    {
        "slug": "sysdesign-database-sharding-partitioning",
        "question": "What is database sharding, and what are common partitioning strategies and their pitfalls?",
        "difficulty": "HARD",
        "tldr": "Sharding splits one dataset across multiple databases by a partition key. Range, hash, and directory-based schemes trade off range-query support, even distribution, and flexibility.",
        "explanation": "Sharding horizontally partitions data so each shard holds a subset, letting you scale writes and storage beyond one machine. Range partitioning keeps ordered keys together (great for range scans but prone to hotspots), hash partitioning spreads load evenly (but breaks range queries), and directory/lookup-based partitioning uses a mapping service for flexibility at the cost of an extra lookup. The hard parts are choosing a key that avoids hotspots, handling cross-shard queries and transactions, and rebalancing as data grows.",
        "code_examples": [
            {"language": "text", "label": "Partitioning strategies",
             "code": "RANGE             HASH                   DIRECTORY\nA-H  -> shard1    hash(id)%3 == 0 -> s1   lookup[id] -> shardN\nI-P  -> shard2    hash(id)%3 == 1 -> s2   (mapping service)\nQ-Z  -> shard3    hash(id)%3 == 2 -> s3\n\nHotspot risk: range on time/sequential id -> newest shard hot\nCross-shard:  JOIN across shards == scatter-gather + merge"},
        ],
        "tags": ["sharding", "databases"],
        "gotchas": ["A poor shard key creates hotspots that defeat the whole point of sharding.", "Cross-shard joins and distributed transactions are expensive and often require app-level fan-out."],
        "follow_ups": ["How would you re-shard a hot shard with zero downtime?", "How do you generate globally unique IDs across shards?"],
    },
    {
        "slug": "sysdesign-cap-theorem",
        "question": "Explain the CAP theorem and what it really forces you to choose during a network partition.",
        "difficulty": "MEDIUM",
        "tldr": "CAP says that during a network partition a distributed store must choose between consistency and availability. When the network is healthy you can have both.",
        "explanation": "The CAP theorem states that a distributed data store can provide at most two of Consistency, Availability, and Partition tolerance simultaneously. Since network partitions are unavoidable in practice, P is mandatory, so the real decision is CP versus AP when a partition occurs: a CP system rejects requests to preserve consistency, while an AP system keeps serving but may return stale or conflicting data. When there is no partition, a well-built system can offer both, which the PACELC extension makes explicit.",
        "code_examples": [
            {"language": "text", "label": "CP vs AP under partition",
             "code": "Partition splits cluster into {A} | {B}\n\nCP choice:  minority side -> refuse reads/writes\n            (stay consistent, sacrifice availability)\nAP choice:  both sides keep serving local copies\n            (stay available, risk divergence -> reconcile later)\n\nPACELC: if Partition -> A or C; Else -> Latency or Consistency"},
        ],
        "tags": ["cap-theorem", "distributed-systems"],
        "gotchas": ["CAP is only about behavior during a partition, not a permanent 'pick 2' of all three.", "Calling a system simply 'CA' is misleading — any networked system must tolerate partitions."],
        "follow_ups": ["How does PACELC refine CAP for the no-partition case?", "Classify Cassandra, etcd, and DynamoDB as CP or AP."],
    },
    {
        "slug": "sysdesign-strong-vs-eventual-consistency",
        "question": "What is the difference between strong and eventual consistency, and when is each appropriate?",
        "difficulty": "MEDIUM",
        "tldr": "Strong consistency guarantees every read sees the latest write; eventual consistency allows temporary staleness that converges over time. Strong is simpler to reason about; eventual is more available and faster.",
        "explanation": "Under strong consistency, once a write is acknowledged, all subsequent reads return that value, which simplifies application logic but requires coordination that raises latency and reduces availability. Eventual consistency permits replicas to temporarily disagree and converge later, enabling lower latency and high availability — ideal for things like view counts, feeds, or DNS. The right choice depends on the cost of stale data: money transfers demand strong consistency, while a 'likes' counter tolerates eventual.",
        "code_examples": [
            {"language": "text", "label": "Read behavior under each model",
             "code": "STRONG\n  write x=5 (ack) ; read x -> 5 always (everywhere)\n\nEVENTUAL\n  write x=5 to replica A\n  read from replica B -> may see old 4 briefly\n  ... replicas sync ... -> 5 (converged)\n\nSpectrum: strong > read-your-writes > monotonic > eventual"},
        ],
        "tags": ["consistency", "distributed-systems"],
        "gotchas": ["Eventual consistency can surface conflicting writes that need resolution (last-write-wins or CRDTs).", "Strong consistency across regions can add tens to hundreds of milliseconds per write due to coordination."],
        "follow_ups": ["Where do causal and monotonic-read consistency fit on the spectrum?", "How do CRDTs achieve conflict-free convergence?"],
    },
    {
        "slug": "sysdesign-message-queues-async-processing",
        "question": "Why use a message queue, and how does async processing improve a system's resilience and scalability?",
        "difficulty": "MEDIUM",
        "tldr": "A message queue decouples producers from consumers, buffers spikes, and lets slow work run asynchronously. This smooths load, isolates failures, and enables independent scaling.",
        "explanation": "A message queue sits between producers and consumers, so a producer can hand off work and return immediately instead of blocking on slow downstream processing. This decoupling buffers traffic spikes (the queue absorbs bursts), isolates failures (a down consumer doesn't break the producer), and lets you scale consumers independently to drain backlogs. The cost is added complexity: you must handle ordering, retries, duplicate delivery, and dead-letter handling.",
        "code_examples": [
            {"language": "text", "label": "Synchronous vs queue-based processing",
             "code": "SYNC (coupled):\n  API --> resize image (3s) --> respond   [user waits 3s]\n\nASYNC (queue):\n  API --> enqueue job --> respond 202     [instant]\n                |\n                v\n            [ QUEUE ] --> worker pool --> resize --> store"},
        ],
        "tags": ["message-queues", "async"],
        "gotchas": ["Most queues guarantee at-least-once delivery, so consumers must be idempotent.", "An unbounded queue can hide a failing consumer until the backlog explodes — monitor queue depth and age."],
        "follow_ups": ["How do you handle poison messages and dead-letter queues?", "When would you choose a log (Kafka) over a traditional task queue?"],
    },
    {
        "slug": "sysdesign-rate-limiting-token-leaky-bucket",
        "question": "Compare the token bucket and leaky bucket algorithms for rate limiting.",
        "difficulty": "MEDIUM",
        "tldr": "Token bucket refills tokens at a steady rate and allows bursts up to bucket size; leaky bucket processes requests at a fixed outflow rate, smoothing bursts into a constant stream.",
        "explanation": "The token bucket holds up to N tokens, refilled at a fixed rate; each request consumes a token, and requests are rejected (or queued) when the bucket is empty — this permits short bursts up to the bucket capacity. The leaky bucket models a fixed-capacity queue drained at a constant rate, so output is perfectly smooth and bursts are buffered or dropped on overflow. Token bucket favors burst-tolerant APIs; leaky bucket favors strict, steady downstream rates.",
        "code_examples": [
            {"language": "text", "label": "Both algorithms as pseudocode",
             "code": "TOKEN BUCKET (allow bursts)\n  every tick: tokens = min(cap, tokens + refill)\n  on request: if tokens >= 1: tokens -= 1; ALLOW else REJECT\n\nLEAKY BUCKET (smooth output)\n  on request: if queue not full: enqueue else DROP\n  every tick: dequeue one -> process   # constant drain"},
        ],
        "tags": ["rate-limiting", "reliability"],
        "gotchas": ["In a distributed fleet, per-node limits multiply — you usually need a shared store (e.g. Redis) for a global limit.", "Fixed-window counters allow 2x burst at window edges; sliding window or token bucket avoids this."],
        "follow_ups": ["How would you implement a global rate limiter with Redis?", "What HTTP status and headers should a rate-limited response return?"],
    },
    {
        "slug": "sysdesign-idempotency",
        "question": "What is idempotency, and how do you design idempotent APIs for safe retries?",
        "difficulty": "MEDIUM",
        "tldr": "An idempotent operation produces the same result no matter how many times it's applied. Idempotency keys let clients retry requests (e.g. payments) without causing duplicate side effects.",
        "explanation": "An operation is idempotent if performing it multiple times has the same effect as performing it once — GET, PUT, and DELETE are naturally idempotent, while POST usually is not. To make unsafe operations safe under retries (common with at-least-once networks and queues), the client sends a unique idempotency key; the server records the key and its result, returning the stored result on duplicates instead of re-executing. This prevents double charges, duplicate orders, and repeated side effects when timeouts trigger client retries.",
        "code_examples": [
            {"language": "text", "label": "Idempotency-key handling",
             "code": "POST /charges   Idempotency-Key: abc-123\n\nserver:\n  row = store.get(key)\n  if row exists: return row.saved_response   # no re-charge\n  result = charge_card(...)                   # do it once\n  store.put(key, result)                      # atomically\n  return result"},
        ],
        "tags": ["idempotency", "api-design"],
        "gotchas": ["The check-and-store must be atomic, or two concurrent retries can both execute (race condition).", "Idempotency records need a TTL and must scope the key to a single logical request payload."],
        "follow_ups": ["How long should idempotency keys be retained?", "How do you make a queue consumer idempotent without a key from the client?"],
    },
    {
        "slug": "sysdesign-rest-vs-grpc",
        "question": "When would you choose REST over gRPC for an API, and vice versa?",
        "difficulty": "MEDIUM",
        "tldr": "REST over HTTP/JSON is universal, human-readable, and great for public/browser APIs; gRPC over HTTP/2 with protobuf is faster, strongly typed, and ideal for internal service-to-service calls.",
        "explanation": "REST uses HTTP verbs and typically JSON, making it easy to consume from browsers, debug by hand, and cache via standard HTTP semantics — the default for public APIs. gRPC uses Protocol Buffers over HTTP/2, giving compact binary payloads, code-generated typed stubs, bidirectional streaming, and lower latency, which suits high-throughput internal microservice communication. The tradeoff: gRPC is less browser-friendly (needs a proxy like gRPC-Web), harder to inspect, and adds schema/tooling overhead.",
        "code_examples": [
            {"language": "text", "label": "REST vs gRPC at a glance",
             "code": "REST                          gRPC\nGET /users/42                 service Users {\nAccept: application/json        rpc Get(GetReq) returns (User);\n-> { \"id\":42, ... }           }\ntext, cacheable, ubiquitous   binary protobuf, HTTP/2 streams\n\nPick REST: public API, browser, simple CRUD\nPick gRPC: internal RPC, low latency, streaming, polyglot typed"},
        ],
        "tags": ["api-design", "microservices"],
        "gotchas": ["gRPC isn't natively callable from browsers without gRPC-Web or a gateway proxy.", "Protobuf schema evolution requires careful field-number/compatibility discipline."],
        "follow_ups": ["How does GraphQL compare for client-driven data fetching?", "How do you version a gRPC service without breaking clients?"],
    },
    {
        "slug": "sysdesign-database-indexing-at-scale",
        "question": "How do database indexes speed up reads, and what are their costs at scale?",
        "difficulty": "MEDIUM",
        "tldr": "Indexes (usually B-trees) turn full table scans into logarithmic lookups, but each index slows writes, consumes storage, and must be chosen to match query patterns.",
        "explanation": "An index is a sorted auxiliary structure (commonly a B-tree, or a hash/LSM tree) that lets the engine find rows in O(log n) instead of scanning every row. The tradeoff is that every insert, update, and delete must also maintain each index, increasing write amplification and storage, so over-indexing hurts write-heavy workloads. Effective indexing means matching indexes to actual query predicates, using composite indexes in the right column order, and leveraging covering indexes.",
        "code_examples": [
            {"language": "text", "label": "Index lookup and column-order rules",
             "code": "No index:  WHERE email=? -> scan all N rows  O(N)\nB-tree:    walk tree to leaf                 O(log N)\n\nComposite (a,b): serves WHERE a=? and WHERE a=? AND b=?\n                 does NOT serve WHERE b=?  (leading col rule)\n\nCost: writes update every index; more idx = slower writes"},
        ],
        "tags": ["databases", "indexing"],
        "gotchas": ["A composite index on (a, b) cannot efficiently serve a query filtering only on b (leftmost-prefix rule).", "Indexing low-cardinality columns (e.g. boolean) rarely helps and still costs write overhead."],
        "follow_ups": ["When does the planner ignore an index and choose a full scan anyway?", "How do LSM-tree indexes (used in Cassandra/RocksDB) differ from B-trees?"],
    },
    {
        "slug": "sysdesign-read-vs-write-optimization",
        "question": "How do you optimize a system differently for read-heavy versus write-heavy workloads?",
        "difficulty": "MEDIUM",
        "tldr": "Read-heavy systems lean on caching, replicas, denormalization, and indexes; write-heavy systems favor sharding, write-optimized stores (LSM), batching, and async/queued ingestion.",
        "explanation": "For read-heavy workloads you add caching layers, read replicas, denormalized/precomputed views, and rich indexes to serve reads fast, accepting more write cost and some staleness. For write-heavy workloads you minimize per-write overhead: shard to spread write load, use LSM-tree storage that turns random writes into sequential ones, batch and buffer writes, and push work to async pipelines. Many real systems split the two via CQRS.",
        "code_examples": [
            {"language": "text", "label": "Optimization levers per workload",
             "code": "READ-HEAVY                  WRITE-HEAVY\n+ CDN / app cache           + shard by key (spread writes)\n+ read replicas             + LSM store (seq writes)\n+ denormalize / precompute  + batch + buffer writes\n+ more indexes              + fewer indexes, async index\n- writes get costlier       + queue ingestion (smooth bursts)"},
        ],
        "tags": ["scaling", "databases"],
        "gotchas": ["Adding indexes and replicas for reads directly increases write latency and lag — they trade off.", "Denormalized read views can drift from the source of truth and need a rebuild/repair path."],
        "follow_ups": ["What is CQRS and when is the added complexity worth it?", "How does write amplification differ between B-tree and LSM storage?"],
    },
    {
        "slug": "sysdesign-consistent-hashing",
        "question": "What problem does consistent hashing solve, and how do virtual nodes improve it?",
        "difficulty": "HARD",
        "tldr": "Consistent hashing maps keys and nodes onto a ring so adding/removing a node remaps only ~1/N of keys instead of nearly all. Virtual nodes smooth out uneven key distribution.",
        "explanation": "With plain hash-modulo-N routing, changing the number of nodes remaps almost every key, causing massive cache misses or data movement. Consistent hashing places both nodes and keys on a hash ring; each key is owned by the next node clockwise, so adding or removing a node only reassigns the keys in that node's arc — roughly 1/N of them. Because a few physical nodes can leave the ring lopsided, each node is assigned many virtual nodes spread around the ring, evening out load and making rebalancing smoother.",
        "code_examples": [
            {"language": "text", "label": "Hash ring with virtual nodes",
             "code": "Ring (0..2^32): positions of nodes A,B,C\n   0 ----- A ----- B ----- C ----- (wrap)\nkey k -> hash(k) lands here, owned by next node CW\n\nRemove B: only B's arc moves to C; rest untouched.\nVirtual nodes: A->A1..A100 scattered -> uniform load"},
        ],
        "tags": ["consistent-hashing", "distributed-systems"],
        "gotchas": ["Without virtual nodes, a small cluster can have very uneven load across the ring.", "Removing a node still concentrates its full load onto its single clockwise successor unless vnodes spread it."],
        "follow_ups": ["How do Dynamo-style systems use the ring for replication (N successors)?", "How many virtual nodes per physical node is a reasonable default?"],
    },
    {
        "slug": "sysdesign-microservices-vs-monolith",
        "question": "What are the tradeoffs between a monolith and a microservices architecture?",
        "difficulty": "MEDIUM",
        "tldr": "Monoliths are simpler to build, deploy, and debug but couple teams and scaling; microservices enable independent deploys and scaling at the cost of distributed-systems complexity and operational overhead.",
        "explanation": "A monolith ships as one deployable unit, giving simple local calls, easy transactions, and straightforward debugging — ideal early on, but it can become a coordination and scaling bottleneck as the team and codebase grow. Microservices split the system into independently deployable, independently scalable services owned by separate teams, at the price of network latency, distributed transactions, service discovery, observability, and deployment complexity. The pragmatic path is often a well-modularized monolith first, extracting services only when clear scaling or team-autonomy pressures justify it.",
        "code_examples": [
            {"language": "text", "label": "Monolith vs microservices structure",
             "code": "MONOLITH                  MICROSERVICES\n+--------------+          [auth][orders][billing][search]\n| auth orders  |             \\    |     |    /\n| billing      |          (network calls, own DBs)\n+--------------+\none deploy, in-proc       many deploys, indep scale\nACID transactions easy    distributed txn / sagas"},
        ],
        "tags": ["microservices", "architecture"],
        "gotchas": ["Premature microservices add network and operational complexity before you have the scale to need it.", "Splitting a shared database per service breaks easy joins and ACID transactions across services."],
        "follow_ups": ["How do you handle a transaction that spans multiple services (sagas)?", "What signals tell you it's time to extract a service from the monolith?"],
    },
    {
        "slug": "sysdesign-thundering-herd-cache-stampede",
        "question": "What is a cache stampede (thundering herd), and how do you prevent it?",
        "difficulty": "HARD",
        "tldr": "When a hot cached key expires, many concurrent requests miss simultaneously and all hammer the database to recompute it. Locking, early recompute, and request coalescing prevent the overload.",
        "explanation": "A cache stampede occurs when a popular key expires and a flood of simultaneous requests all miss the cache and stampede the origin/database to regenerate the same value, potentially overwhelming it. Mitigations include a mutex/lock so only one request recomputes while others wait or serve stale, probabilistic early expiration that refreshes the value slightly before TTL, and request coalescing (single-flight) that dedupes concurrent identical fetches. Serving stale-while-revalidate also keeps latency low during recompute.",
        "code_examples": [
            {"language": "text", "label": "Stampede problem and fixes",
             "code": "PROBLEM: key expires at T\n  1000 reqs at T -> all miss -> 1000 DB queries (origin melts)\n\nFIX 1 single-flight lock: only one recomputes; others wait/stale\nFIX 2 early refresh: refresh before TTL with jitter\nFIX 3 stale-while-revalidate: serve old, refresh in background"},
        ],
        "tags": ["caching", "reliability"],
        "gotchas": ["Setting the same TTL on many keys makes them all expire together, synchronizing the herd — jitter the TTLs.", "A naive global lock can serialize all requests and create its own bottleneck; keep locks per-key."],
        "follow_ups": ["How does stale-while-revalidate trade freshness for availability?", "How would you pre-warm caches before a known traffic spike?"],
    },
    {
        "slug": "sysdesign-back-of-envelope-estimation",
        "question": "How do you do back-of-the-envelope capacity estimation in a system design interview?",
        "difficulty": "EASY",
        "tldr": "Estimate scale from users and behavior: derive QPS, storage, and bandwidth using round numbers and powers of ten, then size servers, caches, and databases from those figures.",
        "explanation": "Back-of-envelope estimation turns vague requirements into concrete numbers that drive design decisions. Start from daily active users and actions per user to get reads/writes per second (convert per-day to per-second by dividing by ~86,400 which is roughly 10^5), apply a peak multiplier, then compute storage (records x size x retention) and bandwidth (QPS x payload). Memorize a few latency and capacity numbers and round aggressively — the goal is the right order of magnitude, not precision.",
        "code_examples": [
            {"language": "text", "label": "Worked estimation example",
             "code": "Given: 100M DAU, 10 writes/day, 100 reads/day each\nWrites/day = 1e9  -> /1e5 s ~= 10k writes/s avg, ~30k peak\nReads/day  = 1e10 -> ~100k reads/s avg\n\nStorage: 1e9 events/day * 1KB = 1 TB/day -> 365 TB/yr\nHandy: 1 day ~ 1e5 s ; KB->MB->GB->TB = x1000 each"},
        ],
        "tags": ["estimation", "fundamentals"],
        "gotchas": ["Forgetting a peak-to-average multiplier underestimates capacity — real traffic is bursty.", "Mixing up bits and bytes, or 10^3 vs 2^10, throws estimates off by meaningful factors."],
        "follow_ups": ["What latency numbers (memory, SSD, network) should every engineer know?", "How would replication factor change your storage estimate?"],
    },
    {
        "slug": "sysdesign-single-point-of-failure-redundancy",
        "question": "How do you identify and eliminate single points of failure in a system?",
        "difficulty": "MEDIUM",
        "tldr": "A single point of failure is any component whose failure takes down the system. Eliminate it with redundancy, failover, and removing shared chokepoints across every tier.",
        "explanation": "A single point of failure (SPOF) is any node, link, or service with no backup, so its outage causes a full or partial system outage. You find SPOFs by tracing every request path and asking 'what dies if this one thing fails?' — common culprits are a lone database leader, one load balancer, a single AZ, or a shared config service. You eliminate them with redundancy (N+1 replicas, multi-AZ/region), automatic failover (leader election, health-checked routing), and avoiding hidden shared dependencies.",
        "code_examples": [
            {"language": "text", "label": "Removing SPOFs tier by tier",
             "code": "SPOF                  REDUNDANT\n[ 1 LB ]              [ LB ] [ LB ]  (active/active + VIP)\n   |                     \\   /\n[ app ]                  [app][app][app]\n   |                        |\n[ 1 DB ]              [leader]+[replica] (auto-failover)\nsingle AZ            multi-AZ / multi-region"},
        ],
        "tags": ["reliability", "redundancy"],
        "gotchas": ["Redundant components sharing one power/network/AZ are still a hidden single point of failure.", "Failover that's never tested often fails when actually needed — exercise it (chaos testing)."],
        "follow_ups": ["What is the difference between active-active and active-passive redundancy?", "How do you avoid a split-brain during failover?"],
    },
    {
        "slug": "sysdesign-heartbeats-health-checks",
        "question": "How do heartbeats and health checks enable failure detection, and what are the design pitfalls?",
        "difficulty": "MEDIUM",
        "tldr": "Heartbeats are periodic 'I'm alive' signals and health checks probe whether a node can serve. Together they let load balancers and orchestrators route away from unhealthy nodes — but tuning timeouts and check depth is tricky.",
        "explanation": "A heartbeat is a periodic signal a node emits (or that a monitor polls) to prove liveness; missing several in a row marks the node down. Health checks go further by verifying the node can actually do useful work — shallow checks test the process is up, while deep checks verify dependencies like the database. Load balancers and orchestrators use these to stop routing traffic to failed instances and to trigger restarts or failover, but overly aggressive timeouts cause false positives and overly deep checks can cascade failures.",
        "code_examples": [
            {"language": "text", "label": "Health checks and heartbeat timeouts",
             "code": "LB --GET /healthz--> instance\n   200 OK  -> in rotation\n   fail x3 -> mark down, stop routing, alert\n\nShallow /healthz: process up?       (liveness)\nDeep   /readyz : DB + deps reachable? (readiness)\n                <- shared dep down = ALL fail (careful)"},
        ],
        "tags": ["reliability", "health-checks"],
        "gotchas": ["Too-short timeouts cause false-positive failures and flapping during brief GC pauses or network blips.", "Deep health checks on a shared dependency can mark an entire fleet unhealthy at once, amplifying an outage."],
        "follow_ups": ["Why separate liveness from readiness probes?", "How do gossip-based failure detectors (e.g. phi accrual) improve on fixed timeouts?"],
    },
    {
        "slug": "sysdesign-design-url-shortener",
        "question": "Design a URL shortener like TinyURL: how do you generate short codes, store mappings, and scale reads?",
        "difficulty": "HARD",
        "tldr": "Map a short code to a long URL in a key-value store, generate codes via base62 of a unique ID or a hash, and scale the read-heavy redirect path with caching, replicas, and a CDN.",
        "explanation": "The core is a mapping from a short code to the original URL, stored in a key-value or sharded SQL store keyed by code. Codes are typically generated by base62-encoding a globally unique ID (e.g. from a counter or Snowflake-style generator) for guaranteed uniqueness, or by hashing the URL and handling collisions; ~7 base62 characters yield 62^7 (about 3.5 trillion) codes. The workload is overwhelmingly reads (redirects), so you front it with a cache and CDN, use read replicas, and return a 301/302 redirect.",
        "code_examples": [
            {"language": "text", "label": "Create and redirect paths",
             "code": "CREATE\n  id = next_unique_id()        # counter / snowflake\n  code = base62(id)            # e.g. 9aZ4kQ  (~7 chars)\n  store.put(code, long_url)\n\nREDIRECT (hot path, read-heavy)\n  url = cache.get(code) or store.get(code)\n  return 302 Location: url\n\n62^7 ~= 3.5e12 codes ; reads >> writes -> cache + CDN + replicas"},
        ],
        "tags": ["url-shortener", "scaling"],
        "gotchas": ["Hashing the URL for codes invites collisions — you must detect and resolve them or use unique IDs instead.", "Use 302 (or short-TTL) if you need click analytics; a cached 301 lets browsers skip your server entirely."],
        "follow_ups": ["How would you support custom aliases and expiring links?", "How do you collect click analytics without slowing the redirect?"],
    },
    {
        "slug": "sysdesign-write-skew-snapshot-isolation",
        "question": "What is write skew, and why can snapshot isolation permit it?",
        "difficulty": "HARD",
        "tldr": "Write skew is an anomaly where two transactions read an overlapping set, then each writes a disjoint part based on a now-stale view, together violating an invariant. Snapshot isolation allows it because each transaction reads from its own consistent snapshot and they don't write the same rows.",
        "explanation": "Under snapshot isolation, each transaction sees a frozen snapshot and only conflicts on write-write to the same row. Write skew occurs when two transactions read the same data, make decisions assuming the other won't change anything, and write to different rows — so there's no write-write conflict to detect, yet a global invariant (like 'at least one doctor on call') is broken. SERIALIZABLE isolation (e.g. PostgreSQL SSI) or explicit locking prevents it.",
        "code_examples": [
            {"language": "text", "label": "Classic on-call write skew",
             "code": "Invariant: at least 1 doctor on call.\nBoth Alice and Bob are on call.\n\nTx1 (Alice): reads count=2, ok to leave -> set alice off\nTx2 (Bob):   reads count=2, ok to leave -> set bob off\n\nBoth commit (different rows!) -> 0 on call. Invariant broken.\nFix: SERIALIZABLE, or SELECT ... FOR UPDATE on the read set."},
        ],
        "tags": ["consistency", "transactions"],
        "gotchas": ["Snapshot isolation only detects write-write conflicts on the SAME row, so disjoint writes slip through.", "Adding a SELECT ... FOR UPDATE materializes the read into a lock, turning the silent conflict into a detectable one."],
        "follow_ups": ["How does PostgreSQL Serializable Snapshot Isolation (SSI) detect write skew?", "How would materializing the conflict into a row lock prevent it?"],
    },
]
