QUESTIONS = [
    {
        "slug": "ts-structural-typing",
        "question": "What is structural typing in TypeScript, and how does it differ from nominal typing?",
        "difficulty": "EASY",
        "tldr": "TypeScript compares types by shape, not by name. If two types have compatible members, they are considered assignable regardless of their declared name.",
        "explanation": "TypeScript uses a structural type system: type compatibility is determined by the members a type has, not by an explicit declaration that one type implements another. This contrasts with nominal typing (used by Java/C#) where types must be explicitly related. An object literal or class instance is assignable to a type as long as it has at least the required properties with compatible types.",
        "code_examples": [
            {"language": "typescript", "label": "Shape-based compatibility",
             "code": "interface Point {\n  x: number;\n  y: number;\n}\n\nfunction printPoint(p: Point) {\n  console.log(p.x, p.y);\n}\n\nconst coord = { x: 1, y: 2, z: 3 };\nprintPoint(coord); // OK: extra `z` is allowed for an existing object"},
        ],
        "tags": ["structural-typing", "type-system"],
        "gotchas": ["Excess property checks apply to fresh object literals passed directly, so `printPoint({ x: 1, y: 2, z: 3 })` errors even though assigning via a variable does not.", "Two unrelated classes can be mutually assignable if their shapes match, including private-member edge cases that break structural compatibility."],
        "follow_ups": ["How do `private`/`protected` members affect structural compatibility between classes?", "When would you simulate nominal typing using branded/tagged types?"],
    },
    {
        "slug": "ts-interface-vs-type-alias",
        "question": "What are the differences between an interface and a type alias in TypeScript?",
        "difficulty": "EASY",
        "tldr": "Interfaces are extendable and support declaration merging; type aliases can represent unions, intersections, primitives, and tuples but cannot be reopened.",
        "explanation": "Both can describe object shapes and are often interchangeable. Interfaces support declaration merging (multiple declarations combine) and are idiomatic for public object/class contracts. Type aliases are more flexible: they can alias unions, intersections, tuples, mapped types, and primitives, but cannot be merged after declaration.",
        "code_examples": [
            {"language": "typescript", "label": "Merging vs unions",
             "code": "interface Animal {\n  name: string;\n}\ninterface Animal {\n  legs: number; // merged into the same interface\n}\n\ntype ID = string | number; // unions only possible with type aliases\ntype Pair = [number, number];\n\nconst a: Animal = { name: \"cat\", legs: 4 };\nconst id: ID = \"abc\";"},
        ],
        "tags": ["interface", "type-alias"],
        "gotchas": ["Accidental declaration merging can silently widen an interface if two unrelated interfaces share a name in the same scope.", "`type` cannot be `implements`-ed if it resolves to a union, while interfaces always can be."],
        "follow_ups": ["When does the team-style guide matter more than technical capability in choosing one?", "Which produces better error messages and editor performance for large object types?"],
    },
    {
        "slug": "ts-enums-vs-union-types",
        "question": "What are the tradeoffs between TypeScript enums and string literal union types?",
        "difficulty": "EASY",
        "tldr": "Union types are erased at compile time and stay lightweight; enums generate runtime objects (except `const enum`) and offer reverse mappings for numeric variants.",
        "explanation": "String literal unions are pure type-level constructs with zero runtime footprint and integrate naturally with narrowing. Enums emit a runtime object, enabling iteration and (for numeric enums) reverse lookups, but add bundle weight and have subtle assignability rules. Many teams prefer unions or `as const` objects for tree-shakeable, predictable code.",
        "code_examples": [
            {"language": "typescript", "label": "Enum vs union vs const object",
             "code": "// Union: no runtime output\ntype Direction = \"up\" | \"down\";\n\n// Enum: emits a runtime object\nenum Color {\n  Red,\n  Green,\n}\nconsole.log(Color.Red); // 0\nconsole.log(Color[0]); // \"Red\" (reverse mapping)\n\n// const-object alternative\nconst Status = { Active: \"active\", Idle: \"idle\" } as const;\ntype Status = (typeof Status)[keyof typeof Status];"},
        ],
        "tags": ["enums", "union-types"],
        "gotchas": ["Numeric enums accept any number assignment in some positions, weakening type safety.", "`const enum` is inlined and can break under isolatedModules or certain bundlers."],
        "follow_ups": ["Why might `const enum` be disallowed in a project using isolatedModules?", "How does the `as const` object pattern reproduce enum ergonomics with less overhead?"],
    },
    {
        "slug": "ts-readonly-const-assertions",
        "question": "How do the `readonly` modifier and `as const` assertions differ in TypeScript?",
        "difficulty": "EASY",
        "tldr": "`readonly` prevents reassignment of a single property/array at the type level; `as const` deeply freezes literal types, narrowing values and making everything readonly.",
        "explanation": "The `readonly` modifier marks individual properties or `ReadonlyArray` elements as non-reassignable in the type system (not at runtime). An `as const` assertion converts an entire literal into its most specific, deeply-readonly form: string/number literals stay narrow and arrays become readonly tuples. They serve different scopes—one member-level, one whole-value.",
        "code_examples": [
            {"language": "typescript", "label": "readonly property vs as const",
             "code": "interface User {\n  readonly id: number;\n  name: string;\n}\nconst u: User = { id: 1, name: \"A\" };\n// u.id = 2; // Error\n\nconst config = { mode: \"dark\", retries: 3 } as const;\ntype Mode = typeof config.mode; // \"dark\""},
        ],
        "tags": ["readonly", "const-assertion"],
        "gotchas": ["`readonly` is compile-time only; the object can still be mutated through an aliased non-readonly type or at runtime.", "`as const` makes arrays into readonly tuples, which can break code expecting a mutable array (e.g. `.push`)."],
        "follow_ups": ["How does `as const` interact with deriving a union type via `[keyof typeof obj]`?", "When is `Object.freeze` needed in addition to `readonly`?"],
    },
    {
        "slug": "ts-type-narrowing-guards",
        "question": "What is type narrowing in TypeScript, and what mechanisms trigger it?",
        "difficulty": "EASY",
        "tldr": "Narrowing refines a broader type to a more specific one within a code branch using checks like `typeof`, `instanceof`, `in`, truthiness, and equality.",
        "explanation": "Within control-flow branches, TypeScript narrows a variable's type based on guards it understands. Common narrowing mechanisms include `typeof` for primitives, `instanceof` for classes, the `in` operator for property existence, truthiness checks, and equality comparisons against literals. The compiler uses control-flow analysis to track the narrowed type per branch.",
        "code_examples": [
            {"language": "typescript", "label": "typeof and nullish narrowing",
             "code": "function format(x: string | number | null) {\n  if (x == null) return \"none\";       // narrows out null/undefined\n  if (typeof x === \"string\") {\n    return x.toUpperCase();             // x: string\n  }\n  return x.toFixed(2);                  // x: number\n}"},
        ],
        "tags": ["narrowing", "type-guards"],
        "gotchas": ["`typeof null === 'object'`, so `typeof x === 'object'` does not exclude null.", "Narrowing can be lost after an `await` or a callback boundary because the compiler cannot guarantee the value is unchanged."],
        "follow_ups": ["How do user-defined type guards (`x is T`) extend narrowing?", "Why can reassigning a narrowed variable reset its type?"],
    },
    {
        "slug": "ts-keyof-typeof-operators",
        "question": "What do the `keyof` and `typeof` operators do in TypeScript's type space?",
        "difficulty": "EASY",
        "tldr": "`keyof T` produces a union of T's property keys; `typeof value` (in type position) extracts the static type of a runtime value.",
        "explanation": "`keyof` is a type operator that yields the union of an object type's known public keys. `typeof`, when used in a type position, captures the inferred type of a value, letting you derive types from existing runtime constants. They are frequently combined—`keyof typeof obj`—to get the key union of a concrete object.",
        "code_examples": [
            {"language": "typescript", "label": "keyof typeof combination",
             "code": "const settings = { theme: \"dark\", volume: 5 };\n\ntype Settings = typeof settings;        // { theme: string; volume: number }\ntype SettingKey = keyof typeof settings; // \"theme\" | \"volume\"\n\nfunction get<K extends keyof Settings>(k: K): Settings[K] {\n  return settings[k];\n}"},
        ],
        "tags": ["keyof", "typeof"],
        "gotchas": ["`keyof` on a type with an index signature yields `string | number` (or `string`), not specific keys.", "`typeof` in value position is the JavaScript runtime operator and is unrelated to its type-position meaning."],
        "follow_ups": ["How does `keyof` behave on types with both an index signature and explicit keys?", "Why does `as const` change the result of `typeof obj`?"],
    },
    {
        "slug": "ts-unknown-any-never",
        "question": "Compare `unknown`, `any`, and `never` in TypeScript. When should each be used?",
        "difficulty": "MEDIUM",
        "tldr": "`any` disables type checking; `unknown` is a safe top type requiring narrowing before use; `never` is the bottom type representing values that cannot occur.",
        "explanation": "`any` opts out of type checking entirely and is assignable to/from anything, sacrificing safety. `unknown` is the type-safe counterpart: anything is assignable to it, but you must narrow before operating on it. `never` is the empty type—no value inhabits it—used for exhaustive checks, functions that never return, and impossible branches.",
        "code_examples": [
            {"language": "typescript", "label": "unknown safety and never returns",
             "code": "function parse(json: string): unknown {\n  return JSON.parse(json);\n}\n\nconst data = parse(\"{}\");\n// data.foo; // Error: must narrow first\nif (typeof data === \"object\" && data) {\n  /* safe */\n}\n\nfunction fail(msg: string): never {\n  throw new Error(msg);\n}"},
        ],
        "tags": ["unknown", "any", "never"],
        "gotchas": ["`any` silently propagates: an `any` value flowing into typed code disables checks downstream without warning.", "`never` is the element type of an empty array literal and absorbs into unions (`T | never` is `T`)."],
        "follow_ups": ["How does `never` enable compile-time exhaustiveness checking in a `switch`?", "Why is `unknown` preferred over `any` for the return type of `JSON.parse` wrappers?"],
    },
    {
        "slug": "ts-discriminated-unions",
        "question": "What is a discriminated (tagged) union, and how does it enable exhaustive type-safe handling?",
        "difficulty": "MEDIUM",
        "tldr": "A discriminated union is a union of object types sharing a common literal 'tag' property, letting the compiler narrow to a single member based on the tag's value.",
        "explanation": "Each member of a discriminated union carries a shared discriminant property typed as a distinct literal. Switching or branching on that property narrows the union to the matching member, exposing only that member's fields. Pairing the `default` branch with a `never`-typed assignment gives compile-time exhaustiveness checks when a new variant is added.",
        "code_examples": [
            {"language": "typescript", "label": "Tagged union with exhaustiveness",
             "code": "type Shape =\n  | { kind: \"circle\"; radius: number }\n  | { kind: \"square\"; side: number };\n\nfunction area(s: Shape): number {\n  switch (s.kind) {\n    case \"circle\":\n      return Math.PI * s.radius ** 2;\n    case \"square\":\n      return s.side ** 2;\n    default:\n      const _exhaustive: never = s; // errors if a case is missing\n      return _exhaustive;\n  }\n}"},
        ],
        "tags": ["discriminated-union", "narrowing"],
        "gotchas": ["If the discriminant is not a literal type (e.g. widened to `string`), narrowing fails entirely.", "Forgetting the `never` exhaustiveness check means new variants compile silently without handling."],
        "follow_ups": ["How would you discriminate on multiple properties at once?", "What happens to narrowing if two members share the same discriminant value?"],
    },
    {
        "slug": "ts-utility-types-partial-pick-omit",
        "question": "Explain the built-in utility types Partial, Required, Pick, Omit, and Record.",
        "difficulty": "MEDIUM",
        "tldr": "These transform existing types: Partial makes props optional, Required makes them mandatory, Pick selects keys, Omit removes keys, and Record builds a map type.",
        "explanation": "TypeScript ships mapped-type helpers for common transformations. `Partial<T>` and `Required<T>` toggle optionality of all members. `Pick<T, K>` keeps only the listed keys while `Omit<T, K>` drops them. `Record<K, V>` constructs an object type with keys `K` and uniform value type `V`. They compose well to derive new shapes without duplication.",
        "code_examples": [
            {"language": "typescript", "label": "Composing utility types",
             "code": "interface User {\n  id: number;\n  name: string;\n  email: string;\n}\n\ntype Draft = Partial<User>;                 // all optional\ntype Identity = Pick<User, \"id\" | \"name\">;  // { id; name }\ntype NoEmail = Omit<User, \"email\">;         // { id; name }\ntype ById = Record<number, User>;           // { [k: number]: User }"},
        ],
        "tags": ["utility-types", "mapped-types"],
        "gotchas": ["`Omit` does not validate that the keys exist on `T`, so a typo in a key silently has no effect (unlike `Pick`).", "`Partial` only goes one level deep; nested objects remain required—use a recursive `DeepPartial` for deep optionality."],
        "follow_ups": ["How is `Omit` implemented in terms of `Pick` and `Exclude`?", "How would you write a recursive `DeepPartial<T>`?"],
    },
    {
        "slug": "ts-conditional-types",
        "question": "What are conditional types in TypeScript, and how does distribution over unions work?",
        "difficulty": "MEDIUM",
        "tldr": "Conditional types take the form `T extends U ? X : Y` and, when the checked type is a naked type parameter, distribute over each member of a union.",
        "explanation": "A conditional type selects between two branches based on an assignability check. When the type being checked is a bare (naked) generic parameter and is a union, the conditional distributes: it applies to each union member individually and recombines the results. Wrapping the parameter in a tuple (`[T] extends [U]`) disables distribution for whole-union comparisons.",
        "code_examples": [
            {"language": "typescript", "label": "Distributive vs non-distributive",
             "code": "type ToArray<T> = T extends any ? T[] : never;\ntype A = ToArray<string | number>; // string[] | number[]  (distributed)\n\n// Disable distribution by wrapping in a tuple\ntype IsNever<T> = [T] extends [never] ? true : false;\ntype B = IsNever<never>; // true"},
        ],
        "tags": ["conditional-types", "generics"],
        "gotchas": ["Distribution over `never` yields `never` (the empty union), which can produce surprising results in helpers.", "`boolean` distributes as `true | false`, so `T extends true` over `boolean` evaluates both branches."],
        "follow_ups": ["How does wrapping in `[T]` change distribution behavior?", "Why does `T extends any ? ... : ...` act as a distribution trigger rather than a real condition?"],
    },
    {
        "slug": "ts-mapped-types",
        "question": "How do mapped types work, and what are key remapping and modifier operators?",
        "difficulty": "MEDIUM",
        "tldr": "Mapped types iterate over keys of a type to build a new one, with `+`/`-` modifiers to add or remove `readonly`/`?`, and `as` clauses for key remapping.",
        "explanation": "A mapped type uses `[K in keyof T]` to generate a property per key, optionally transforming the value type. Modifier prefixes `+` and `-` add or strip `readonly` and optional (`?`) flags. The `as` clause (key remapping) lets you rename or filter keys, including dropping a key by mapping it to `never`.",
        "code_examples": [
            {"language": "typescript", "label": "Modifiers and key remapping",
             "code": "type Mutable<T> = {\n  -readonly [K in keyof T]: T[K]; // strip readonly\n};\n\ntype Getters<T> = {\n  [K in keyof T as `get${Capitalize<string & K>}`]: () => T[K];\n};\n\ntype P = Getters<{ name: string }>; // { getName: () => string }"},
        ],
        "tags": ["mapped-types", "key-remapping"],
        "gotchas": ["Mapping a key to `never` via `as` removes it entirely, which is the idiom for key filtering.", "Homomorphic mapped types (`[K in keyof T]`) preserve modifiers and array/tuple-ness, but adding `as` can break that preservation."],
        "follow_ups": ["What makes a mapped type homomorphic and why does it matter?", "How do template literal types combine with `as` for key transformation?"],
    },
    {
        "slug": "ts-satisfies-operator",
        "question": "What problem does the `satisfies` operator solve, and how does it differ from a type annotation or `as`?",
        "difficulty": "MEDIUM",
        "tldr": "`satisfies` validates that an expression matches a type while preserving the expression's narrowest inferred type, unlike an annotation which widens it.",
        "explanation": "A type annotation (`const x: T = ...`) checks the value but widens it to `T`, losing literal specificity. `as` forces a type without full checking. `satisfies` checks assignability to a constraint type yet keeps the more precise inferred type of the literal, giving you both validation and narrow inference.",
        "code_examples": [
            {"language": "typescript", "label": "satisfies preserves narrow inference",
             "code": "type Config = Record<string, string | number>;\n\nconst cfg = {\n  host: \"localhost\",\n  port: 8080,\n} satisfies Config;\n\ncfg.port.toFixed(0); // OK: port is still inferred as number"},
        ],
        "tags": ["satisfies", "inference"],
        "gotchas": ["`satisfies` does not change the runtime value or add properties; it is purely a check.", "It still permits excess property errors, so it is stricter than `as` but does not widen like an annotation."],
        "follow_ups": ["How does `satisfies` combine with `as const` for literal-typed config objects?", "Why might `satisfies` give better autocomplete than a plain annotation?"],
    },
    {
        "slug": "ts-generic-constraints",
        "question": "How do generic constraints (`extends`) work, and how do you constrain to keys of another parameter?",
        "difficulty": "MEDIUM",
        "tldr": "`T extends U` restricts a type parameter to assignable types; constraints can reference other parameters, e.g. `K extends keyof T`, enabling type-safe property access.",
        "explanation": "Generic constraints limit what a type parameter may be, enabling the compiler to assume certain members exist inside the generic body. A constraint can depend on another parameter—`K extends keyof T`—so a function can safely index into an object by key and return the precise value type. This is the foundation for type-safe getters and lenses.",
        "code_examples": [
            {"language": "typescript", "label": "keyof constraint and shape constraint",
             "code": "function getProp<T, K extends keyof T>(obj: T, key: K): T[K] {\n  return obj[key];\n}\n\nconst user = { id: 1, name: \"Ada\" };\nconst name = getProp(user, \"name\"); // string\n\nfunction longest<T extends { length: number }>(a: T, b: T): T {\n  return a.length >= b.length ? a : b;\n}"},
        ],
        "tags": ["generics", "constraints"],
        "gotchas": ["A default type parameter must still satisfy its own constraint, or the declaration errors.", "Over-constraining can cause inference to fall back to the constraint type rather than the narrow argument type."],
        "follow_ups": ["How do default type parameters interact with constraints?", "Why might inference widen `T` to the constraint when no argument pins it down?"],
    },
    {
        "slug": "ts-infer-keyword",
        "question": "What does the `infer` keyword do inside conditional types?",
        "difficulty": "MEDIUM",
        "tldr": "`infer` declares a type variable inside a conditional type's `extends` clause, capturing part of a matched type for use in the true branch.",
        "explanation": "Within the `extends` clause of a conditional type, `infer R` introduces a fresh type variable that the compiler unifies with whatever fits that position during matching. It is how built-ins like `ReturnType` and `Parameters` extract pieces of function or container types. Multiple `infer` variables in the same position produce a union or intersection depending on variance.",
        "code_examples": [
            {"language": "typescript", "label": "Extracting return and promise types",
             "code": "type MyReturn<T> = T extends (...args: any[]) => infer R ? R : never;\ntype Unwrap<T> = T extends Promise<infer U> ? U : T;\n\ntype A = MyReturn<() => number>; // number\ntype B = Unwrap<Promise<string>>; // string"},
        ],
        "tags": ["infer", "conditional-types"],
        "gotchas": ["Multiple `infer` for the same variable in covariant positions yields a union, but in contravariant (parameter) positions yields an intersection.", "`infer` only exists in the conditional's true branch; referencing it in the false branch is an error."],
        "follow_ups": ["Why does inferring a parameter type produce an intersection across overloads?", "How does recursive `infer` enable flattening nested arrays or promises?"],
    },
    {
        "slug": "ts-template-literal-types",
        "question": "What are template literal types, and what can they express that plain unions cannot?",
        "difficulty": "MEDIUM",
        "tldr": "Template literal types build string literal types from interpolated unions and support intrinsic string manipulation, enabling pattern-based and combinatorial string types.",
        "explanation": "Template literal types use backtick syntax with embedded type placeholders to construct new string literal types, distributing over any unions inside the placeholders. Combined with the intrinsic helpers `Uppercase`, `Lowercase`, `Capitalize`, and `Uncapitalize`, and with `infer`, they can parse and transform string patterns at the type level.",
        "code_examples": [
            {"language": "typescript", "label": "Combinatorial and parsing patterns",
             "code": "type Event = \"click\" | \"hover\";\ntype Handler = `on${Capitalize<Event>}`; // \"onClick\" | \"onHover\"\n\ntype Prefix<S> = S extends `${infer P}-${string}` ? P : never;\ntype X = Prefix<\"data-id\">; // \"data\""},
        ],
        "tags": ["template-literal-types", "string-types"],
        "gotchas": ["Cross-multiplying multiple large unions in a template explodes the number of members and can hit the compiler's limit.", "Number placeholders are coerced to their string form, so numeric structure is not preserved."],
        "follow_ups": ["How would you build a typed event-emitter API using template literal keys?", "What is the union-size limit risk when interpolating several unions?"],
    },
    {
        "slug": "ts-function-overloads",
        "question": "How do function overloads work in TypeScript, and how do they differ from a single union-typed signature?",
        "difficulty": "MEDIUM",
        "tldr": "Overloads declare multiple call signatures followed by one compatible implementation, giving callers precise input/output pairings that a single union signature cannot express.",
        "explanation": "You write several overload signatures and then one implementation signature that must be compatible with all of them but is not itself callable from outside. Overloads let the return type depend on which argument shape was passed—something a single signature with union parameters cannot capture relationally. The implementation typically narrows internally to satisfy each declared overload.",
        "code_examples": [
            {"language": "typescript", "label": "Relational overloads",
             "code": "function reverse(x: string): string;\nfunction reverse<T>(x: T[]): T[];\nfunction reverse(x: string | unknown[]): string | unknown[] {\n  return typeof x === \"string\"\n    ? x.split(\"\").reverse().join(\"\")\n    : [...x].reverse();\n}\n\nconst s = reverse(\"abc\"); // string\nconst a = reverse([1, 2]); // number[]"},
        ],
        "tags": ["overloads", "functions"],
        "gotchas": ["The implementation signature is invisible to callers; only the overload signatures are part of the public type.", "Overload resolution picks the first matching signature top-to-bottom, so order them from most specific to least."],
        "follow_ups": ["When is a single generic signature preferable to overloads?", "Why can the implementation signature be more permissive than every overload?"],
    },
    {
        "slug": "ts-index-signatures",
        "question": "What are index signatures, and what constraints do they impose on a type?",
        "difficulty": "MEDIUM",
        "tldr": "An index signature like `[key: string]: V` types arbitrary dynamic keys, but forces all explicit properties to be compatible with the index value type.",
        "explanation": "Index signatures describe objects whose keys are not known in advance, mapping `string`, `number`, or `symbol` keys to a value type. Any explicitly declared property must have a type assignable to the index signature's value type. Numeric index signatures must be compatible with the string index signature because JavaScript coerces numeric keys to strings.",
        "code_examples": [
            {"language": "typescript", "label": "Index signature constraints",
             "code": "interface StringMap {\n  [key: string]: number;\n  count: number;    // OK\n}\n\nconst m: StringMap = { count: 1, anything: 42 };\nconst v = m[\"unknown\"]; // number (no key-existence check at runtime)"},
        ],
        "tags": ["index-signatures", "type-system"],
        "gotchas": ["Reads through an index signature are typed as the value type even for missing keys, so `noUncheckedIndexedAccess` is recommended to add `undefined`.", "A numeric index signature's value type must be assignable to the string index signature's value type."],
        "follow_ups": ["What does the `noUncheckedIndexedAccess` flag change about index access?", "When should you use `Record<K, V>` instead of an inline index signature?"],
    },
    {
        "slug": "ts-type-vs-value-space",
        "question": "What is the distinction between TypeScript's type space and value space?",
        "difficulty": "MEDIUM",
        "tldr": "Identifiers live in separate type and value namespaces; some declarations (class, enum) create both, and `typeof`/indexed access bridge from value to type space.",
        "explanation": "TypeScript maintains two parallel namespaces: types (erased at compile time) and values (present at runtime). A `const` lives only in value space; an `interface` only in type space; a `class` or `enum` introduces a name in both. To reference a value's type you cross over with `typeof`, and to read a type's member you use indexed access (`T[\"key\"]`).",
        "code_examples": [
            {"language": "typescript", "label": "Type-space vs value-space references",
             "code": "class Point {\n  x = 0;\n}\n\nconst p: Point = new Point(); // `Point` used as type AND value\n\nconst settings = { mode: \"dark\" };\ntype Mode = (typeof settings)[\"mode\"]; // cross into type space\n\ninterface Shape { area(): number; }"},
        ],
        "tags": ["type-space", "value-space"],
        "gotchas": ["Using a type-only name where a value is expected (or vice versa) yields confusing 'refers to a value/type' errors.", "`import type` / `export type` strip imports that exist only in type space, which matters under isolatedModules."],
        "follow_ups": ["Why do classes occupy both namespaces while interfaces do not?", "When is `import type` required to avoid runtime side effects?"],
    },
    {
        "slug": "ts-type-assertions",
        "question": "What are type assertions in TypeScript, and what are their safety limitations?",
        "difficulty": "MEDIUM",
        "tldr": "Assertions (`value as T` or `<T>value`) tell the compiler to treat a value as a type without runtime checks; they can only widen or narrow within related types unless forced through `unknown`.",
        "explanation": "A type assertion overrides the compiler's inferred type but performs no runtime conversion or validation. TypeScript only allows assertions between types that overlap (one assignable to the other); to assert between unrelated types you must go through `unknown` (or `any`). Misused assertions are a common source of runtime errors because they suppress the type system's guarantees.",
        "code_examples": [
            {"language": "typescript", "label": "Assertions and double assertion",
             "code": "const el = document.getElementById(\"app\") as HTMLInputElement;\nel.value = \"hi\"; // compiler trusts the assertion\n\nconst n = \"123\" as unknown as number; // double assertion to force unrelated types\n\nconst x = { a: 1 } as const; // const assertion — different mechanism"},
        ],
        "tags": ["type-assertions", "type-system"],
        "gotchas": ["Assertions are erased at runtime, so `'123' as number` does not convert the string—the value is still a string.", "The angle-bracket form `<T>value` conflicts with JSX and is disallowed in .tsx files."],
        "follow_ups": ["Why is `as unknown as T` sometimes necessary and what does it signal about the code?", "How do non-null assertions (`x!`) differ from `as` assertions?"],
    },
    {
        "slug": "ts-tsconfig-strict-flags",
        "question": "What does the `strict` family of tsconfig flags enable, and why do they matter?",
        "difficulty": "MEDIUM",
        "tldr": "`strict: true` turns on a bundle of checks—including strictNullChecks, noImplicitAny, and strictFunctionTypes—that catch null bugs and unsafe assignments at compile time.",
        "explanation": "The `strict` option is a shorthand that enables a group of stricter type-checking flags. The most impactful are `strictNullChecks` (null/undefined are no longer assignable to every type), `noImplicitAny` (untyped values must be annotated), and `strictFunctionTypes` (contravariant parameter checks). Enabling them surfaces a large class of latent runtime errors during compilation.",
        "code_examples": [
            {"language": "typescript", "label": "Effects of strict checks",
             "code": "function first(arr: string[]): string {\n  return arr[0]; // with noUncheckedIndexedAccess, this would be string | undefined\n}\n\nlet name: string;\n// name = null; // Error under strictNullChecks"},
        ],
        "tags": ["tsconfig", "strict-mode"],
        "gotchas": ["`noUncheckedIndexedAccess` is NOT included in `strict`; it must be enabled separately.", "Enabling `strict` on a legacy codebase can surface thousands of errors at once—incremental adoption per-flag is often necessary."],
        "follow_ups": ["Which strict flags are most disruptive to enable on an existing codebase?", "Why is `noUncheckedIndexedAccess` excluded from the `strict` bundle?"],
    },
    {
        "slug": "ts-generics-defaults-variance",
        "question": "How do default type parameters and variance annotations (`in`/`out`) work in generics?",
        "difficulty": "MEDIUM",
        "tldr": "Default type parameters supply a fallback when an argument is omitted; `in`/`out` annotations explicitly mark a parameter as contravariant or covariant for variance checking.",
        "explanation": "A generic can declare defaults (`<T = string>`) so callers may omit arguments, with later parameters allowed to reference earlier ones. TypeScript 4.7+ supports optional variance annotations: `out T` marks a parameter as covariant (producer position) and `in T` as contravariant (consumer position), which improves error clarity and can speed up checking. Variance is otherwise inferred structurally.",
        "code_examples": [
            {"language": "typescript", "label": "Defaults and variance annotations",
             "code": "interface Container<T = unknown> {\n  value: T;\n}\nconst c: Container = { value: 42 }; // T defaults to unknown\n\ninterface Producer<out T> {\n  get(): T; // covariant\n}\ninterface Consumer<in T> {\n  set(v: T): void; // contravariant\n}"},
        ],
        "tags": ["generics", "variance"],
        "gotchas": ["Variance annotations are checked: marking a parameter `out` while using it in a contravariant position is an error.", "A default type parameter still must satisfy any constraint declared on that same parameter."],
        "follow_ups": ["When do explicit variance annotations improve compiler performance?", "How does method bivariance differ from property (strict) function-type variance?"],
    },
    {
        "slug": "ts-declaration-merging",
        "question": "What is declaration merging in TypeScript, and which declarations can merge?",
        "difficulty": "HARD",
        "tldr": "Declaration merging combines multiple declarations of the same name into one definition; interfaces, namespaces, and enums merge, and namespaces can merge with classes/functions/enums.",
        "explanation": "When the compiler sees two declarations sharing a name, it merges them under specific rules. Interfaces with the same name combine their members; namespaces merge and can also attach static members to a class, function, or enum of the same name. This underpins patterns like augmenting third-party types and adding statics to a function, but conflicting member types within a merge cause errors.",
        "code_examples": [
            {"language": "typescript", "label": "Interface augmentation and namespace merge",
             "code": "interface Window {\n  myGlobal: string;\n}\n\nfunction greet(name: string) {\n  return `Hi ${name}`;\n}\nnamespace greet {\n  export const version = \"1.0\";\n}\ngreet.version; // \"1.0\""},
        ],
        "tags": ["declaration-merging", "namespaces"],
        "gotchas": ["Merging interfaces with incompatible types for the same property is a compile error, not a silent override.", "Module augmentation requires the target module to be imported and the augmentation placed in a module or `declare module` block."],
        "follow_ups": ["How does `declare module` augmentation differ from global interface merging?", "Why can a namespace merge with a class but a class cannot merge with another class?"],
    },
    {
        "slug": "ts-recursive-conditional-types",
        "question": "How do recursive conditional types work, and what are practical examples like deep flattening?",
        "difficulty": "HARD",
        "tldr": "Conditional types can reference themselves, enabling recursive type-level computation such as deep unwrapping, tuple processing, and deep-readonly transformations within depth limits.",
        "explanation": "A conditional type may refer to itself in its branches, letting the compiler recurse over nested structures like nested promises, arrays, or object trees. Combined with `infer`, this powers utilities such as `Awaited`, deep flattening, and `DeepReadonly`. TypeScript bounds recursion depth (and supports tail-recursion elimination for some patterns), so excessively deep or unbounded recursion errors out.",
        "code_examples": [
            {"language": "typescript", "label": "DeepReadonly and recursive Flatten",
             "code": "type DeepReadonly<T> = T extends (infer E)[]\n  ? ReadonlyArray<DeepReadonly<E>>\n  : T extends object\n  ? { readonly [K in keyof T]: DeepReadonly<T[K]> }\n  : T;\n\ntype Flatten<T> = T extends (infer U)[] ? Flatten<U> : T;\ntype X = Flatten<number[][][]>; // number"},
        ],
        "tags": ["conditional-types", "recursion"],
        "gotchas": ["Recursion has a depth limit; deeply nested or non-terminating recursion triggers 'Type instantiation is excessively deep'.", "Functions match `T extends object`, so naive deep transforms may unintentionally recurse into callable members."],
        "follow_ups": ["How does TypeScript's tail-recursion elimination help with type-level list processing?", "How would you special-case functions and primitives to avoid recursing into them?"],
    },
    {
        "slug": "ts-branded-nominal-types",
        "question": "How can you simulate nominal typing in TypeScript's structural system using branded types?",
        "difficulty": "HARD",
        "tldr": "Add a phantom 'brand' property (often via intersection with a unique tag) so otherwise-identical structural types become mutually non-assignable.",
        "explanation": "Because TypeScript is structural, two `number`-based IDs are interchangeable by default. A branded type intersects the base type with a unique, non-existent marker property (frequently keyed by a unique symbol) so the compiler treats the branded type as distinct. The brand exists only at the type level; you construct branded values via a small assertion-based factory.",
        "code_examples": [
            {"language": "typescript", "label": "Symbol-based branded types",
             "code": "declare const brand: unique symbol;\ntype Brand<T, B> = T & { readonly [brand]: B };\n\ntype UserId = Brand<number, \"UserId\">;\ntype PostId = Brand<number, \"PostId\">;\n\nconst toUserId = (n: number) => n as UserId;\nconst uid = toUserId(1);\n// const pid: PostId = uid; // Error: brands differ"},
        ],
        "tags": ["branded-types", "nominal-typing"],
        "gotchas": ["The brand is erased at runtime, so branded values offer no runtime protection—validation must still happen at boundaries.", "Constructing branded values requires an assertion, which can be misused to brand invalid data if the factory does not validate."],
        "follow_ups": ["Why is a `unique symbol` brand key preferable to a plain string property?", "How do branded types interact with serialization across JSON boundaries?"],
    },
    {
        "slug": "ts-const-type-parameters",
        "question": "What do `const` type parameters (TS 5.0+) do, and how do they improve literal inference in generics?",
        "difficulty": "HARD",
        "tldr": "A `const` modifier on a type parameter (`<const T>`) makes the compiler infer the narrowest, `as const`-like type for arguments without requiring callers to write `as const`.",
        "explanation": "Normally generic inference widens literals (e.g., a string argument becomes `string`). Prefixing a type parameter with `const` tells the compiler to infer the most specific literal/readonly type for arguments matched to it, as if the caller had written `as const`. This is valuable for APIs that need to preserve exact tuple or literal shapes for downstream type computation.",
        "code_examples": [
            {"language": "typescript", "label": "const type parameter inference",
             "code": "function asTuple<const T extends readonly unknown[]>(t: T): T {\n  return t;\n}\n\nconst a = asTuple([1, \"x\", true]);\n// type: readonly [1, \"x\", true]  (literal, readonly — no `as const` needed)\n\nfunction route<const T extends string>(path: T): T {\n  return path;\n}\nconst r = route(\"/users\"); // \"/users\", not string"},
        ],
        "tags": ["const-type-parameters", "inference"],
        "gotchas": ["`const` type parameters only affect inference at call sites; passing a value already typed as a wide variable will not re-narrow it.", "The effect is limited by the constraint—if the constraint widens, the readonly/literal narrowing may not apply as expected."],
        "follow_ups": ["Why does passing a pre-declared `let` variable defeat the `const` parameter narrowing?", "How does a `const` type parameter compare to wrapping the argument in `as const`?"],
    },
]
