"""Canonical NeetCode 150 question list grouped by topic slug."""

QUESTIONS_BY_TOPIC: dict[str, list[dict]] = {
    "arrays-hashing": [
        {
            "title": "Contains Duplicate",
            "slug": "contains-duplicate",
            "difficulty": "EASY",
            "pattern": "Hashing",
            "leetcode_id": 217,
            "leetcode_slug": "contains-duplicate",
            "hint": "Think about what data structure gives constant-time membership lookups as you scan.",
            "key_insight": "A hash set lets you detect repeats in a single pass with O(n) time and O(n) space.",
            "companies": ["Amazon", "Google", "Microsoft"],
        },
        {
            "title": "Valid Anagram",
            "slug": "valid-anagram",
            "difficulty": "EASY",
            "pattern": "Hashing",
            "leetcode_id": 242,
            "leetcode_slug": "valid-anagram",
            "hint": "Two anagrams share the same character frequencies regardless of order.",
            "key_insight": "Count character frequencies in both strings and compare the maps; equality means anagram.",
            "companies": ["Amazon", "Bloomberg", "Apple"],
        },
        {
            "title": "Two Sum",
            "slug": "two-sum",
            "difficulty": "EASY",
            "pattern": "Hashing",
            "leetcode_id": 1,
            "leetcode_slug": "two-sum",
            "hint": "As you scan, ask what complement you would need to reach the target.",
            "key_insight": "Store seen values in a hash map keyed by value; check for target minus current in O(1).",
            "companies": ["Amazon", "Google", "Apple", "Microsoft"],
        },
        {
            "title": "Group Anagrams",
            "slug": "group-anagrams",
            "difficulty": "MEDIUM",
            "pattern": "Hashing",
            "leetcode_id": 49,
            "leetcode_slug": "group-anagrams",
            "hint": "Find a canonical signature shared by every member of an anagram group.",
            "key_insight": "Bucket strings by sorted characters or a 26-length count tuple to group anagrams in one pass.",
            "companies": ["Amazon", "Meta", "Uber", "Google"],
        },
        {
            "title": "Top K Frequent Elements",
            "slug": "top-k-frequent-elements",
            "difficulty": "MEDIUM",
            "pattern": "Bucket Sort",
            "leetcode_id": 347,
            "leetcode_slug": "top-k-frequent-elements",
            "hint": "Counts are bounded by n, so consider indexing by frequency rather than sorting it.",
            "key_insight": "Bucket sort by frequency achieves O(n) by leveraging that any count is at most n.",
            "companies": ["Amazon", "Meta", "Uber"],
        },
        {
            "title": "Encode and Decode Strings",
            "slug": "encode-and-decode-strings",
            "difficulty": "MEDIUM",
            "pattern": "String Encoding",
            "leetcode_id": 271,
            "leetcode_slug": "encode-and-decode-strings",
            "hint": "Prefix each string with metadata that makes its boundary unambiguous.",
            "key_insight": "Prefix length plus a delimiter encodes strings unambiguously regardless of their content.",
            "companies": ["Google", "Meta", "Amazon"],
        },
        {
            "title": "Product of Array Except Self",
            "slug": "product-of-array-except-self",
            "difficulty": "MEDIUM",
            "pattern": "Prefix Product",
            "leetcode_id": 238,
            "leetcode_slug": "product-of-array-except-self",
            "hint": "Avoid division; think about the product of everything to the left and right of each index.",
            "key_insight": "Two passes computing prefix and suffix products combine to yield the answer in O(n) and O(1) extra space.",
            "companies": ["Amazon", "Meta", "Apple", "Microsoft"],
        },
        {
            "title": "Valid Sudoku",
            "slug": "valid-sudoku",
            "difficulty": "MEDIUM",
            "pattern": "Hashing",
            "leetcode_id": 36,
            "leetcode_slug": "valid-sudoku",
            "hint": "Track what you have already seen in each row, column, and 3x3 box independently.",
            "key_insight": "Use 27 hash sets (rows, columns, boxes) and detect any collision during a single grid traversal.",
            "companies": ["Amazon", "Apple", "Uber"],
        },
        {
            "title": "Longest Consecutive Sequence",
            "slug": "longest-consecutive-sequence",
            "difficulty": "MEDIUM",
            "pattern": "Hashing",
            "leetcode_id": 128,
            "leetcode_slug": "longest-consecutive-sequence",
            "hint": "Only start counting a streak from a number that has no predecessor in the set.",
            "key_insight": "Iterating runs only from sequence starts keeps the total work linear despite the inner loop.",
            "companies": ["Google", "Meta", "Amazon"],
        },
    ],
    "two-pointers": [
        {
            "title": "Valid Palindrome",
            "slug": "valid-palindrome",
            "difficulty": "EASY",
            "pattern": "Two Pointers",
            "leetcode_id": 125,
            "leetcode_slug": "valid-palindrome",
            "hint": "Walk from both ends and skip whatever you should not be comparing.",
            "key_insight": "Two pointers converging from each end let you compare characters in place with O(1) space.",
            "companies": ["Meta", "Microsoft", "Amazon"],
        },
        {
            "title": "Two Sum II - Input Array Is Sorted",
            "slug": "two-sum-ii-input-array-is-sorted",
            "difficulty": "MEDIUM",
            "pattern": "Two Pointers",
            "leetcode_id": 167,
            "leetcode_slug": "two-sum-ii-input-array-is-sorted",
            "hint": "The sorted order tells you which direction to move when the sum is off.",
            "key_insight": "Move the left pointer right to grow the sum and the right pointer left to shrink it.",
            "companies": ["Amazon", "Google", "Apple"],
        },
        {
            "title": "3Sum",
            "slug": "3sum",
            "difficulty": "MEDIUM",
            "pattern": "Two Pointers",
            "leetcode_id": 15,
            "leetcode_slug": "3sum",
            "hint": "Fix one element and reduce the problem to a sorted two-sum on the remainder.",
            "key_insight": "Sort, then for each index run a two-pointer sweep while skipping duplicates to avoid repeats.",
            "companies": ["Meta", "Amazon", "Apple", "Adobe"],
        },
        {
            "title": "Container With Most Water",
            "slug": "container-with-most-water",
            "difficulty": "MEDIUM",
            "pattern": "Two Pointers",
            "leetcode_id": 11,
            "leetcode_slug": "container-with-most-water",
            "hint": "Width shrinks each step, so always move the side that limits the current height.",
            "key_insight": "Moving the shorter wall inward is the only direction that could ever increase the area.",
            "companies": ["Amazon", "Bloomberg", "Meta"],
        },
        {
            "title": "Trapping Rain Water",
            "slug": "trapping-rain-water",
            "difficulty": "HARD",
            "pattern": "Two Pointers",
            "leetcode_id": 42,
            "leetcode_slug": "trapping-rain-water",
            "hint": "At each index, water depends on the smaller of the highest walls to its left and right.",
            "key_insight": "Two pointers maintaining left and right max let you compute trapped water in O(n) time and O(1) space.",
            "companies": ["Amazon", "Google", "Apple", "Bloomberg"],
        },
    ],
    "sliding-window": [
        {
            "title": "Best Time to Buy and Sell Stock",
            "slug": "best-time-to-buy-and-sell-stock",
            "difficulty": "EASY",
            "pattern": "Sliding Window",
            "leetcode_id": 121,
            "leetcode_slug": "best-time-to-buy-and-sell-stock",
            "hint": "Track the lowest price seen so far while you scan forward.",
            "key_insight": "Maximum profit at each day equals current price minus the minimum price observed before it.",
            "companies": ["Amazon", "Meta", "Apple", "Bloomberg"],
        },
        {
            "title": "Longest Substring Without Repeating Characters",
            "slug": "longest-substring-without-repeating-characters",
            "difficulty": "MEDIUM",
            "pattern": "Variable Window",
            "leetcode_id": 3,
            "leetcode_slug": "longest-substring-without-repeating-characters",
            "hint": "Grow the window, and when a duplicate appears, shrink from the left until it disappears.",
            "key_insight": "A sliding window plus a hash set maintains the longest unique-character substring in O(n).",
            "companies": ["Amazon", "Meta", "Microsoft", "Bloomberg"],
        },
        {
            "title": "Longest Repeating Character Replacement",
            "slug": "longest-repeating-character-replacement",
            "difficulty": "MEDIUM",
            "pattern": "Variable Window",
            "leetcode_id": 424,
            "leetcode_slug": "longest-repeating-character-replacement",
            "hint": "A window is valid when its length minus its most frequent character count is at most k.",
            "key_insight": "Maintain max-frequency in the window; expand while window size minus that count stays within k.",
            "companies": ["Google", "Amazon", "Uber"],
        },
        {
            "title": "Permutation in String",
            "slug": "permutation-in-string",
            "difficulty": "MEDIUM",
            "pattern": "Fixed Window",
            "leetcode_id": 567,
            "leetcode_slug": "permutation-in-string",
            "hint": "Slide a window of the target's length and compare character frequencies.",
            "key_insight": "Two equal-sized frequency arrays let you confirm an anagram match in O(1) per shift.",
            "companies": ["Microsoft", "Amazon", "Adobe"],
        },
        {
            "title": "Minimum Window Substring",
            "slug": "minimum-window-substring",
            "difficulty": "HARD",
            "pattern": "Variable Window",
            "leetcode_id": 76,
            "leetcode_slug": "minimum-window-substring",
            "hint": "Expand until the window has everything you need, then shrink while it still does.",
            "key_insight": "Track required character counts; shrink whenever all needed characters are covered to minimize length.",
            "companies": ["Meta", "Amazon", "Uber", "Google"],
        },
        {
            "title": "Sliding Window Maximum",
            "slug": "sliding-window-maximum",
            "difficulty": "HARD",
            "pattern": "Monotonic Deque",
            "leetcode_id": 239,
            "leetcode_slug": "sliding-window-maximum",
            "hint": "Discard any element that is smaller than a newer one entering the window.",
            "key_insight": "A monotonic decreasing deque maintains the window maximum in amortized O(1) per step.",
            "companies": ["Amazon", "Google", "Meta"],
        },
    ],
    "stack": [
        {
            "title": "Valid Parentheses",
            "slug": "valid-parentheses",
            "difficulty": "EASY",
            "pattern": "Stack",
            "leetcode_id": 20,
            "leetcode_slug": "valid-parentheses",
            "hint": "Brackets must close in the reverse order they were opened.",
            "key_insight": "Push openers and pop on a matching closer; the string is valid iff the stack ends empty.",
            "companies": ["Amazon", "Meta", "Google", "Bloomberg"],
        },
        {
            "title": "Min Stack",
            "slug": "min-stack",
            "difficulty": "MEDIUM",
            "pattern": "Stack",
            "leetcode_id": 155,
            "leetcode_slug": "min-stack",
            "hint": "Carry the running minimum alongside each pushed value.",
            "key_insight": "Storing the current minimum at each stack frame yields O(1) min, push, and pop.",
            "companies": ["Amazon", "Google", "Bloomberg"],
        },
        {
            "title": "Evaluate Reverse Polish Notation",
            "slug": "evaluate-reverse-polish-notation",
            "difficulty": "MEDIUM",
            "pattern": "Stack",
            "leetcode_id": 150,
            "leetcode_slug": "evaluate-reverse-polish-notation",
            "hint": "Operators consume the two most recent values produced.",
            "key_insight": "Push numbers; on an operator pop two operands, apply it, and push the result back.",
            "companies": ["LinkedIn", "Amazon", "Google"],
        },
        {
            "title": "Generate Parentheses",
            "slug": "generate-parentheses",
            "difficulty": "MEDIUM",
            "pattern": "Backtracking",
            "leetcode_id": 22,
            "leetcode_slug": "generate-parentheses",
            "hint": "Only add a closing bracket when there is an unmatched opener available.",
            "key_insight": "Backtracking with open and close counters prunes invalid branches early.",
            "companies": ["Amazon", "Google", "Uber", "Meta"],
        },
        {
            "title": "Daily Temperatures",
            "slug": "daily-temperatures",
            "difficulty": "MEDIUM",
            "pattern": "Monotonic Stack",
            "leetcode_id": 739,
            "leetcode_slug": "daily-temperatures",
            "hint": "For each day, look for the next day that surpasses it - sound familiar?",
            "key_insight": "A monotonic decreasing stack of indices resolves the next-greater-element problem in O(n).",
            "companies": ["Amazon", "Google", "Bloomberg"],
        },
        {
            "title": "Car Fleet",
            "slug": "car-fleet",
            "difficulty": "MEDIUM",
            "pattern": "Stack",
            "leetcode_id": 853,
            "leetcode_slug": "car-fleet",
            "hint": "Sort cars by starting position and consider their arrival times from the back.",
            "key_insight": "Processing cars from closest-to-target back, each car either merges into the fleet ahead or forms a new one.",
            "companies": ["Google", "Amazon", "Uber"],
        },
        {
            "title": "Largest Rectangle in Histogram",
            "slug": "largest-rectangle-in-histogram",
            "difficulty": "HARD",
            "pattern": "Monotonic Stack",
            "leetcode_id": 84,
            "leetcode_slug": "largest-rectangle-in-histogram",
            "hint": "For every bar, find how far it can extend left and right without hitting a shorter bar.",
            "key_insight": "A monotonic increasing stack gives the nearest smaller bars on each side, enabling O(n) rectangle computation.",
            "companies": ["Amazon", "Google", "Meta"],
        },
    ],
    "binary-search": [
        {
            "title": "Binary Search",
            "slug": "binary-search",
            "difficulty": "EASY",
            "pattern": "Binary Search",
            "leetcode_id": 704,
            "leetcode_slug": "binary-search",
            "hint": "Each comparison should halve what remains to consider.",
            "key_insight": "Maintain inclusive bounds and converge by comparing the midpoint to the target each step.",
            "companies": ["Amazon", "Google", "Microsoft"],
        },
        {
            "title": "Search a 2D Matrix",
            "slug": "search-a-2d-matrix",
            "difficulty": "MEDIUM",
            "pattern": "Binary Search",
            "leetcode_id": 74,
            "leetcode_slug": "search-a-2d-matrix",
            "hint": "Treat the row-major matrix as a single sorted virtual array.",
            "key_insight": "Index n*r+c maps a flattened position to row r and column c, enabling one logarithmic search.",
            "companies": ["Amazon", "Apple", "Bloomberg"],
        },
        {
            "title": "Koko Eating Bananas",
            "slug": "koko-eating-bananas",
            "difficulty": "MEDIUM",
            "pattern": "Binary Search on Answer",
            "leetcode_id": 875,
            "leetcode_slug": "koko-eating-bananas",
            "hint": "Higher eating rates are monotonically feasible, so search over possible rates.",
            "key_insight": "Binary search the smallest rate k such that the total hours to eat all piles stays within the limit.",
            "companies": ["Google", "Amazon", "Meta"],
        },
        {
            "title": "Find Minimum in Rotated Sorted Array",
            "slug": "find-minimum-in-rotated-sorted-array",
            "difficulty": "MEDIUM",
            "pattern": "Binary Search",
            "leetcode_id": 153,
            "leetcode_slug": "find-minimum-in-rotated-sorted-array",
            "hint": "Compare the midpoint to the right end to decide which half is still sorted.",
            "key_insight": "If mid is greater than right, the minimum lies to the right of mid; otherwise it lies at or before mid.",
            "companies": ["Amazon", "Microsoft", "Bloomberg"],
        },
        {
            "title": "Search in Rotated Sorted Array",
            "slug": "search-in-rotated-sorted-array",
            "difficulty": "MEDIUM",
            "pattern": "Binary Search",
            "leetcode_id": 33,
            "leetcode_slug": "search-in-rotated-sorted-array",
            "hint": "One half of the array around the midpoint is always sorted - figure out which.",
            "key_insight": "Identify the sorted half at each step and check whether the target lies within its range to decide where to recurse.",
            "companies": ["Amazon", "Meta", "Microsoft", "Apple"],
        },
        {
            "title": "Time Based Key-Value Store",
            "slug": "time-based-key-value-store",
            "difficulty": "MEDIUM",
            "pattern": "Binary Search",
            "leetcode_id": 981,
            "leetcode_slug": "time-based-key-value-store",
            "hint": "Per key, the timestamps are inserted in increasing order; what can you do with that?",
            "key_insight": "Store per-key sorted lists and binary search for the largest timestamp at most the query time.",
            "companies": ["Google", "Amazon", "Uber"],
        },
        {
            "title": "Median of Two Sorted Arrays",
            "slug": "median-of-two-sorted-arrays",
            "difficulty": "HARD",
            "pattern": "Binary Search",
            "leetcode_id": 4,
            "leetcode_slug": "median-of-two-sorted-arrays",
            "hint": "Partition the smaller array so the combined left half has exactly half the total elements.",
            "key_insight": "Binary search the partition of the shorter array such that max-left is at most min-right across both sides.",
            "companies": ["Amazon", "Google", "Apple", "Adobe"],
        },
    ],
    "linked-list": [
        {
            "title": "Reverse Linked List",
            "slug": "reverse-linked-list",
            "difficulty": "EASY",
            "pattern": "Linked List",
            "leetcode_id": 206,
            "leetcode_slug": "reverse-linked-list",
            "hint": "Flip one pointer at a time while remembering the next node.",
            "key_insight": "Iteratively rewire each node's next to its predecessor using three pointers in O(1) space.",
            "companies": ["Amazon", "Meta", "Apple", "Microsoft"],
        },
        {
            "title": "Merge Two Sorted Lists",
            "slug": "merge-two-sorted-lists",
            "difficulty": "EASY",
            "pattern": "Two Pointers",
            "leetcode_id": 21,
            "leetcode_slug": "merge-two-sorted-lists",
            "hint": "Always splice off the smaller of the two current heads.",
            "key_insight": "A dummy node simplifies the merge by giving you a stable handle on the resulting list's head.",
            "companies": ["Amazon", "Google", "Apple", "Microsoft"],
        },
        {
            "title": "Reorder List",
            "slug": "reorder-list",
            "difficulty": "MEDIUM",
            "pattern": "Linked List",
            "leetcode_id": 143,
            "leetcode_slug": "reorder-list",
            "hint": "Split the list in half, reverse the second half, then interleave.",
            "key_insight": "Find the midpoint with slow/fast pointers, reverse the second half, then merge the two halves alternately.",
            "companies": ["Amazon", "Meta", "Bloomberg"],
        },
        {
            "title": "Remove Nth Node From End of List",
            "slug": "remove-nth-node-from-end-of-list",
            "difficulty": "MEDIUM",
            "pattern": "Two Pointers",
            "leetcode_id": 19,
            "leetcode_slug": "remove-nth-node-from-end-of-list",
            "hint": "Stagger two pointers by n nodes so they reach the end together.",
            "key_insight": "Advancing a lead pointer n steps ahead lets the trailing pointer land exactly before the target in one pass.",
            "companies": ["Amazon", "Meta", "Apple"],
        },
        {
            "title": "Copy List With Random Pointer",
            "slug": "copy-list-with-random-pointer",
            "difficulty": "MEDIUM",
            "pattern": "Hashing",
            "leetcode_id": 138,
            "leetcode_slug": "copy-list-with-random-pointer",
            "hint": "First create all the new nodes, then wire their pointers in a second pass.",
            "key_insight": "A hash map from original to clone resolves both next and random links in two linear traversals.",
            "companies": ["Amazon", "Meta", "Bloomberg", "Microsoft"],
        },
        {
            "title": "Add Two Numbers",
            "slug": "add-two-numbers",
            "difficulty": "MEDIUM",
            "pattern": "Linked List",
            "leetcode_id": 2,
            "leetcode_slug": "add-two-numbers",
            "hint": "Simulate grade-school addition, but watch the carry.",
            "key_insight": "Walk both lists together, summing digits and propagating a carry, allocating new nodes as you go.",
            "companies": ["Amazon", "Microsoft", "Adobe", "Bloomberg"],
        },
        {
            "title": "Linked List Cycle",
            "slug": "linked-list-cycle",
            "difficulty": "EASY",
            "pattern": "Floyd's Cycle",
            "leetcode_id": 141,
            "leetcode_slug": "linked-list-cycle",
            "hint": "If there is a loop, a faster runner will lap a slower one.",
            "key_insight": "Floyd's tortoise-and-hare pointers meet inside any cycle, detecting it without extra memory.",
            "companies": ["Amazon", "Microsoft", "Bloomberg"],
        },
        {
            "title": "Find the Duplicate Number",
            "slug": "find-the-duplicate-number",
            "difficulty": "MEDIUM",
            "pattern": "Floyd's Cycle",
            "leetcode_id": 287,
            "leetcode_slug": "find-the-duplicate-number",
            "hint": "Treat each value as a pointer into the array; a duplicate creates a cycle.",
            "key_insight": "Cycle detection on the index-to-value function finds the duplicate in O(n) time and O(1) space.",
            "companies": ["Amazon", "Google", "Bloomberg"],
        },
        {
            "title": "LRU Cache",
            "slug": "lru-cache",
            "difficulty": "MEDIUM",
            "pattern": "Hashing + Doubly Linked List",
            "leetcode_id": 146,
            "leetcode_slug": "lru-cache",
            "hint": "You need O(1) lookup and O(1) reordering of usage recency.",
            "key_insight": "Combine a hash map with a doubly linked list so move-to-front and eviction are both O(1).",
            "companies": ["Amazon", "Meta", "Microsoft", "Uber"],
        },
        {
            "title": "Merge k Sorted Lists",
            "slug": "merge-k-sorted-lists",
            "difficulty": "HARD",
            "pattern": "Heap",
            "leetcode_id": 23,
            "leetcode_slug": "merge-k-sorted-lists",
            "hint": "At any moment, the next node to emit is the smallest of the k current heads.",
            "key_insight": "A min-heap of the k current heads yields each output node in O(log k), totaling O(n log k).",
            "companies": ["Amazon", "Meta", "Google", "Uber"],
        },
        {
            "title": "Reverse Nodes in k-Group",
            "slug": "reverse-nodes-in-k-group",
            "difficulty": "HARD",
            "pattern": "Linked List",
            "leetcode_id": 25,
            "leetcode_slug": "reverse-nodes-in-k-group",
            "hint": "Reverse one block at a time and stitch the boundary pointers.",
            "key_insight": "Repeatedly detach a k-sized segment, reverse it in place, and reconnect to the previous tail.",
            "companies": ["Amazon", "Meta", "Microsoft"],
        },
    ],
    "trees": [
        {
            "title": "Invert Binary Tree",
            "slug": "invert-binary-tree",
            "difficulty": "EASY",
            "pattern": "DFS",
            "leetcode_id": 226,
            "leetcode_slug": "invert-binary-tree",
            "hint": "Swap children at every node, then recurse.",
            "key_insight": "Recursive swap of left and right subtrees at every node mirrors the tree in O(n).",
            "companies": ["Google", "Amazon", "Apple"],
        },
        {
            "title": "Maximum Depth of Binary Tree",
            "slug": "maximum-depth-of-binary-tree",
            "difficulty": "EASY",
            "pattern": "DFS",
            "leetcode_id": 104,
            "leetcode_slug": "maximum-depth-of-binary-tree",
            "hint": "Depth of a node is one more than the depth of its children.",
            "key_insight": "Recursively compute the max of left and right depths and add one for the current node.",
            "companies": ["Amazon", "Microsoft", "LinkedIn"],
        },
        {
            "title": "Diameter of Binary Tree",
            "slug": "diameter-of-binary-tree",
            "difficulty": "EASY",
            "pattern": "DFS",
            "leetcode_id": 543,
            "leetcode_slug": "diameter-of-binary-tree",
            "hint": "Diameter through a node equals left height plus right height.",
            "key_insight": "Compute heights bottom-up while updating a global maximum of left height plus right height.",
            "companies": ["Meta", "Amazon", "Google"],
        },
        {
            "title": "Balanced Binary Tree",
            "slug": "balanced-binary-tree",
            "difficulty": "EASY",
            "pattern": "DFS",
            "leetcode_id": 110,
            "leetcode_slug": "balanced-binary-tree",
            "hint": "Return both height and balance status from each recursive call.",
            "key_insight": "Bottom-up height computation lets you detect imbalance early and stop in O(n).",
            "companies": ["Amazon", "Google", "Bloomberg"],
        },
        {
            "title": "Same Tree",
            "slug": "same-tree",
            "difficulty": "EASY",
            "pattern": "DFS",
            "leetcode_id": 100,
            "leetcode_slug": "same-tree",
            "hint": "Two trees match iff their roots match and their corresponding subtrees match.",
            "key_insight": "Structural recursion compares both trees node by node in a single traversal.",
            "companies": ["Amazon", "Apple", "Bloomberg"],
        },
        {
            "title": "Subtree of Another Tree",
            "slug": "subtree-of-another-tree",
            "difficulty": "EASY",
            "pattern": "DFS",
            "leetcode_id": 572,
            "leetcode_slug": "subtree-of-another-tree",
            "hint": "Walk the main tree; at each node, check if the subtree rooted there equals the target.",
            "key_insight": "Combine an outer traversal of the main tree with an inner same-tree check at every visited node.",
            "companies": ["Amazon", "Microsoft", "Adobe"],
        },
        {
            "title": "Lowest Common Ancestor of a Binary Search Tree",
            "slug": "lowest-common-ancestor-of-a-binary-search-tree",
            "difficulty": "MEDIUM",
            "pattern": "BST",
            "leetcode_id": 235,
            "leetcode_slug": "lowest-common-ancestor-of-a-binary-search-tree",
            "hint": "The split point in the BST is where the two values diverge.",
            "key_insight": "The first node whose value lies between the two targets is their lowest common ancestor.",
            "companies": ["Amazon", "Meta", "LinkedIn"],
        },
        {
            "title": "Binary Tree Level Order Traversal",
            "slug": "binary-tree-level-order-traversal",
            "difficulty": "MEDIUM",
            "pattern": "BFS",
            "leetcode_id": 102,
            "leetcode_slug": "binary-tree-level-order-traversal",
            "hint": "Process the tree one layer at a time using a queue.",
            "key_insight": "Track the queue size at the start of each level to know exactly how many nodes belong to it.",
            "companies": ["Amazon", "Meta", "Microsoft", "Bloomberg"],
        },
        {
            "title": "Binary Tree Right Side View",
            "slug": "binary-tree-right-side-view",
            "difficulty": "MEDIUM",
            "pattern": "BFS",
            "leetcode_id": 199,
            "leetcode_slug": "binary-tree-right-side-view",
            "hint": "Whatever node ends each level is what you see from the right.",
            "key_insight": "Level-order traversal, recording the last node visited at each level, gives the right-side view.",
            "companies": ["Amazon", "Meta", "Bloomberg"],
        },
        {
            "title": "Count Good Nodes in Binary Tree",
            "slug": "count-good-nodes-in-binary-tree",
            "difficulty": "MEDIUM",
            "pattern": "DFS",
            "leetcode_id": 1448,
            "leetcode_slug": "count-good-nodes-in-binary-tree",
            "hint": "Carry the maximum seen on the path from the root downward.",
            "key_insight": "DFS while passing down the running max counts every node whose value is at least that max.",
            "companies": ["Microsoft", "Amazon", "Google"],
        },
        {
            "title": "Validate Binary Search Tree",
            "slug": "validate-binary-search-tree",
            "difficulty": "MEDIUM",
            "pattern": "DFS",
            "leetcode_id": 98,
            "leetcode_slug": "validate-binary-search-tree",
            "hint": "Each node must lie within bounds inherited from its ancestors.",
            "key_insight": "Recurse with shrinking lower and upper bounds, narrowing them as you go left or right.",
            "companies": ["Amazon", "Meta", "Microsoft", "Apple"],
        },
        {
            "title": "Kth Smallest Element in a BST",
            "slug": "kth-smallest-element-in-a-bst",
            "difficulty": "MEDIUM",
            "pattern": "DFS",
            "leetcode_id": 230,
            "leetcode_slug": "kth-smallest-element-in-a-bst",
            "hint": "An inorder traversal visits BST values in ascending order.",
            "key_insight": "Inorder traversal naturally enumerates BST values sorted; stop at the kth one.",
            "companies": ["Amazon", "Meta", "Uber"],
        },
        {
            "title": "Construct Binary Tree From Preorder and Inorder Traversal",
            "slug": "construct-binary-tree-from-preorder-and-inorder-traversal",
            "difficulty": "MEDIUM",
            "pattern": "DFS",
            "leetcode_id": 105,
            "leetcode_slug": "construct-binary-tree-from-preorder-and-inorder-traversal",
            "hint": "The first preorder element is the root; locate it in inorder to split subtrees.",
            "key_insight": "Preorder gives roots in order while inorder partitions left and right subtree ranges around each root.",
            "companies": ["Amazon", "Meta", "Bloomberg"],
        },
        {
            "title": "Binary Tree Maximum Path Sum",
            "slug": "binary-tree-maximum-path-sum",
            "difficulty": "HARD",
            "pattern": "DFS",
            "leetcode_id": 124,
            "leetcode_slug": "binary-tree-maximum-path-sum",
            "hint": "A path bends at exactly one node; compute its best left and right contributions.",
            "key_insight": "Return the best one-sided gain upward while updating the global answer with left plus right plus node.",
            "companies": ["Amazon", "Meta", "Google"],
        },
        {
            "title": "Serialize and Deserialize Binary Tree",
            "slug": "serialize-and-deserialize-binary-tree",
            "difficulty": "HARD",
            "pattern": "DFS",
            "leetcode_id": 297,
            "leetcode_slug": "serialize-and-deserialize-binary-tree",
            "hint": "Mark null children explicitly so the structure is unambiguous.",
            "key_insight": "Preorder traversal with explicit nulls produces a stream that uniquely reconstructs the original tree.",
            "companies": ["Amazon", "Meta", "Google", "Microsoft"],
        },
    ],
    "heap": [
        {
            "title": "Kth Largest Element in a Stream",
            "slug": "kth-largest-element-in-a-stream",
            "difficulty": "EASY",
            "pattern": "Min Heap",
            "leetcode_id": 703,
            "leetcode_slug": "kth-largest-element-in-a-stream",
            "hint": "Keep only the top k values seen so far at any moment.",
            "key_insight": "A min-heap of size k makes its root the running kth largest with O(log k) updates.",
            "companies": ["Amazon", "Google", "Apple"],
        },
        {
            "title": "Last Stone Weight",
            "slug": "last-stone-weight",
            "difficulty": "EASY",
            "pattern": "Max Heap",
            "leetcode_id": 1046,
            "leetcode_slug": "last-stone-weight",
            "hint": "You repeatedly need the two largest remaining values.",
            "key_insight": "A max-heap retrieves and updates the two heaviest stones each round in O(log n).",
            "companies": ["Amazon", "Google", "Bloomberg"],
        },
        {
            "title": "K Closest Points to Origin",
            "slug": "k-closest-points-to-origin",
            "difficulty": "MEDIUM",
            "pattern": "Max Heap",
            "leetcode_id": 973,
            "leetcode_slug": "k-closest-points-to-origin",
            "hint": "Maintain the k best candidates seen so far, evicting the worst when needed.",
            "key_insight": "A size-k max-heap on distance keeps the k closest points in O(n log k) total time.",
            "companies": ["Amazon", "Meta", "Uber", "Apple"],
        },
        {
            "title": "Kth Largest Element in an Array",
            "slug": "kth-largest-element-in-an-array",
            "difficulty": "MEDIUM",
            "pattern": "Quickselect",
            "leetcode_id": 215,
            "leetcode_slug": "kth-largest-element-in-an-array",
            "hint": "A heap works; quickselect's partitioning can be even faster on average.",
            "key_insight": "Quickselect partitions around a pivot to locate the kth largest in expected O(n).",
            "companies": ["Amazon", "Meta", "Apple", "Bloomberg"],
        },
        {
            "title": "Task Scheduler",
            "slug": "task-scheduler",
            "difficulty": "MEDIUM",
            "pattern": "Greedy + Heap",
            "leetcode_id": 621,
            "leetcode_slug": "task-scheduler",
            "hint": "Always schedule whichever task has the most remaining occurrences first.",
            "key_insight": "Greedy scheduling of the most frequent task with a cooldown queue minimizes idle slots.",
            "companies": ["Amazon", "Meta", "Uber"],
        },
        {
            "title": "Design Twitter",
            "slug": "design-twitter",
            "difficulty": "MEDIUM",
            "pattern": "Heap",
            "leetcode_id": 355,
            "leetcode_slug": "design-twitter",
            "hint": "A user's feed merges several time-ordered streams of tweets.",
            "key_insight": "A max-heap merges followees' tweet timelines to extract the ten most recent tweets efficiently.",
            "companies": ["Amazon", "Meta", "Uber"],
        },
        {
            "title": "Find Median From Data Stream",
            "slug": "find-median-from-data-stream",
            "difficulty": "HARD",
            "pattern": "Two Heaps",
            "leetcode_id": 295,
            "leetcode_slug": "find-median-from-data-stream",
            "hint": "Split the stream into a lower and upper half and keep them balanced.",
            "key_insight": "A max-heap of the lower half and min-heap of the upper half put the median at the heap tops in O(log n).",
            "companies": ["Amazon", "Google", "Meta", "Apple"],
        },
    ],
    "backtracking": [
        {
            "title": "Subsets",
            "slug": "subsets",
            "difficulty": "MEDIUM",
            "pattern": "Backtracking",
            "leetcode_id": 78,
            "leetcode_slug": "subsets",
            "hint": "At each element, decide whether to include it.",
            "key_insight": "Backtrack by choosing include or exclude at each index, recording the current path at every step.",
            "companies": ["Amazon", "Meta", "Google", "Bloomberg"],
        },
        {
            "title": "Combination Sum",
            "slug": "combination-sum",
            "difficulty": "MEDIUM",
            "pattern": "Backtracking",
            "leetcode_id": 39,
            "leetcode_slug": "combination-sum",
            "hint": "Keep an index to avoid permuting the same set of numbers twice.",
            "key_insight": "Recurse while subtracting from the remaining target and never going backward in the candidate list.",
            "companies": ["Amazon", "Uber", "Adobe"],
        },
        {
            "title": "Permutations",
            "slug": "permutations",
            "difficulty": "MEDIUM",
            "pattern": "Backtracking",
            "leetcode_id": 46,
            "leetcode_slug": "permutations",
            "hint": "Track which elements are already used in the current arrangement.",
            "key_insight": "Backtrack while marking and unmarking used positions to enumerate every ordering exactly once.",
            "companies": ["Amazon", "Meta", "Adobe", "Microsoft"],
        },
        {
            "title": "Subsets II",
            "slug": "subsets-ii",
            "difficulty": "MEDIUM",
            "pattern": "Backtracking",
            "leetcode_id": 90,
            "leetcode_slug": "subsets-ii",
            "hint": "After sorting, skip duplicate siblings at the same recursion depth.",
            "key_insight": "Sorting plus skipping equal elements at the same recursion level avoids duplicate subsets.",
            "companies": ["Amazon", "Microsoft", "Google"],
        },
        {
            "title": "Combination Sum II",
            "slug": "combination-sum-ii",
            "difficulty": "MEDIUM",
            "pattern": "Backtracking",
            "leetcode_id": 40,
            "leetcode_slug": "combination-sum-ii",
            "hint": "Use each candidate at most once and skip duplicates at the same depth.",
            "key_insight": "Sort and skip same-value siblings to prevent repeated combinations while still using each index at most once.",
            "companies": ["Amazon", "Google", "Bloomberg"],
        },
        {
            "title": "Word Search",
            "slug": "word-search",
            "difficulty": "MEDIUM",
            "pattern": "Backtracking",
            "leetcode_id": 79,
            "leetcode_slug": "word-search",
            "hint": "DFS from each cell, marking visits so you do not reuse them in the same path.",
            "key_insight": "DFS with on-the-fly marking and restoration of grid cells explores all paths without extra memory.",
            "companies": ["Amazon", "Meta", "Microsoft", "Bloomberg"],
        },
        {
            "title": "Palindrome Partitioning",
            "slug": "palindrome-partitioning",
            "difficulty": "MEDIUM",
            "pattern": "Backtracking",
            "leetcode_id": 131,
            "leetcode_slug": "palindrome-partitioning",
            "hint": "Try every possible next palindromic prefix and recurse on the rest.",
            "key_insight": "Backtrack by extending the current prefix only when it is palindromic, recursing on the remaining string.",
            "companies": ["Amazon", "Google", "Uber"],
        },
        {
            "title": "Letter Combinations of a Phone Number",
            "slug": "letter-combinations-of-a-phone-number",
            "difficulty": "MEDIUM",
            "pattern": "Backtracking",
            "leetcode_id": 17,
            "leetcode_slug": "letter-combinations-of-a-phone-number",
            "hint": "For each digit, choose one of its mapped letters.",
            "key_insight": "Backtrack over digits, branching on each mapped letter and accumulating the current prefix.",
            "companies": ["Amazon", "Meta", "Uber", "Apple"],
        },
        {
            "title": "N-Queens",
            "slug": "n-queens",
            "difficulty": "HARD",
            "pattern": "Backtracking",
            "leetcode_id": 51,
            "leetcode_slug": "n-queens",
            "hint": "Place one queen per row; remember the columns and diagonals already attacked.",
            "key_insight": "Track attacked columns and two diagonal sums as sets to prune row-by-row queen placements.",
            "companies": ["Amazon", "Google", "Apple"],
        },
    ],
    "graphs": [
        {
            "title": "Number of Islands",
            "slug": "number-of-islands",
            "difficulty": "MEDIUM",
            "pattern": "DFS",
            "leetcode_id": 200,
            "leetcode_slug": "number-of-islands",
            "hint": "Each new unvisited land cell starts a new island; flood it before continuing.",
            "key_insight": "DFS or BFS from each unvisited land cell sinks one entire island per outer iteration.",
            "companies": ["Amazon", "Meta", "Google", "Bloomberg"],
        },
        {
            "title": "Max Area of Island",
            "slug": "max-area-of-island",
            "difficulty": "MEDIUM",
            "pattern": "DFS",
            "leetcode_id": 695,
            "leetcode_slug": "max-area-of-island",
            "hint": "Flood-fill each island and accumulate its size.",
            "key_insight": "DFS returns the size of each island during flooding so you can track the maximum encountered.",
            "companies": ["Amazon", "Google", "Microsoft"],
        },
        {
            "title": "Clone Graph",
            "slug": "clone-graph",
            "difficulty": "MEDIUM",
            "pattern": "DFS",
            "leetcode_id": 133,
            "leetcode_slug": "clone-graph",
            "hint": "Map each original node to its clone as you traverse to avoid duplicating work.",
            "key_insight": "Memoizing original-to-clone mappings during DFS ensures each node is copied exactly once.",
            "companies": ["Amazon", "Meta", "Google", "Bloomberg"],
        },
        {
            "title": "Walls and Gates",
            "slug": "walls-and-gates",
            "difficulty": "MEDIUM",
            "pattern": "BFS",
            "leetcode_id": 286,
            "leetcode_slug": "walls-and-gates",
            "hint": "Run BFS from every gate at the same time.",
            "key_insight": "Multi-source BFS starting from all gates fills shortest distances in O(rows times cols).",
            "companies": ["Amazon", "Meta", "Google"],
        },
        {
            "title": "Rotting Oranges",
            "slug": "rotting-oranges",
            "difficulty": "MEDIUM",
            "pattern": "BFS",
            "leetcode_id": 994,
            "leetcode_slug": "rotting-oranges",
            "hint": "Rot expands one layer per minute; what traversal models that?",
            "key_insight": "Multi-source BFS from all initially rotten oranges measures the number of minutes until none remain fresh.",
            "companies": ["Amazon", "Google", "Apple"],
        },
        {
            "title": "Pacific Atlantic Water Flow",
            "slug": "pacific-atlantic-water-flow",
            "difficulty": "MEDIUM",
            "pattern": "DFS",
            "leetcode_id": 417,
            "leetcode_slug": "pacific-atlantic-water-flow",
            "hint": "Instead of simulating flow downhill, walk uphill from the borders.",
            "key_insight": "Reverse DFS from each ocean's border marks reachable cells; their intersection is the answer.",
            "companies": ["Amazon", "Google", "Meta"],
        },
        {
            "title": "Surrounded Regions",
            "slug": "surrounded-regions",
            "difficulty": "MEDIUM",
            "pattern": "DFS",
            "leetcode_id": 130,
            "leetcode_slug": "surrounded-regions",
            "hint": "Anything connected to the border survives; flip the rest.",
            "key_insight": "Mark border-connected regions first, then flip everything that was not marked.",
            "companies": ["Amazon", "Google", "Bloomberg"],
        },
        {
            "title": "Course Schedule",
            "slug": "course-schedule",
            "difficulty": "MEDIUM",
            "pattern": "Topological Sort",
            "leetcode_id": 207,
            "leetcode_slug": "course-schedule",
            "hint": "A schedule exists iff the prerequisite graph has no cycle.",
            "key_insight": "DFS three-color marking or Kahn's BFS detects cycles in the prerequisite directed graph.",
            "companies": ["Amazon", "Meta", "Google", "Uber"],
        },
        {
            "title": "Course Schedule II",
            "slug": "course-schedule-ii",
            "difficulty": "MEDIUM",
            "pattern": "Topological Sort",
            "leetcode_id": 210,
            "leetcode_slug": "course-schedule-ii",
            "hint": "Output the order in which prerequisites finish.",
            "key_insight": "Kahn's algorithm repeatedly removes zero-indegree nodes to emit a valid topological order or detect a cycle.",
            "companies": ["Amazon", "Meta", "Google"],
        },
        {
            "title": "Graph Valid Tree",
            "slug": "graph-valid-tree",
            "difficulty": "MEDIUM",
            "pattern": "Union Find",
            "leetcode_id": 261,
            "leetcode_slug": "graph-valid-tree",
            "hint": "A tree on n nodes has n minus one edges and is fully connected with no cycles.",
            "key_insight": "Union-find rejects any edge whose endpoints already share a root, certifying acyclicity and connectivity together.",
            "companies": ["Amazon", "Google", "Meta"],
        },
        {
            "title": "Number of Connected Components in an Undirected Graph",
            "slug": "number-of-connected-components-in-an-undirected-graph",
            "difficulty": "MEDIUM",
            "pattern": "Union Find",
            "leetcode_id": 323,
            "leetcode_slug": "number-of-connected-components-in-an-undirected-graph",
            "hint": "Start with n components and reduce the count whenever an edge merges two of them.",
            "key_insight": "Union-find decrements the component count exactly when union joins previously disjoint sets.",
            "companies": ["Amazon", "Google", "LinkedIn"],
        },
        {
            "title": "Redundant Connection",
            "slug": "redundant-connection",
            "difficulty": "MEDIUM",
            "pattern": "Union Find",
            "leetcode_id": 684,
            "leetcode_slug": "redundant-connection",
            "hint": "Adding the edge that closes a cycle is the redundant one.",
            "key_insight": "Process edges with union-find; the first edge whose endpoints already share a root is the redundant one.",
            "companies": ["Amazon", "Google", "Bloomberg"],
        },
        {
            "title": "Word Ladder",
            "slug": "word-ladder",
            "difficulty": "HARD",
            "pattern": "BFS",
            "leetcode_id": 127,
            "leetcode_slug": "word-ladder",
            "hint": "Each transformation is an edge of weight one; what algorithm finds shortest unweighted paths?",
            "key_insight": "BFS over wildcard patterns finds the shortest transformation sequence between words.",
            "companies": ["Amazon", "Google", "Meta"],
        },
    ],
    "advanced-graphs": [
        {
            "title": "Reconstruct Itinerary",
            "slug": "reconstruct-itinerary",
            "difficulty": "HARD",
            "pattern": "Eulerian Path",
            "leetcode_id": 332,
            "leetcode_slug": "reconstruct-itinerary",
            "hint": "Use every ticket exactly once and prefer lexicographically smaller next airports.",
            "key_insight": "Hierholzer's algorithm with lexicographic neighbors finds an Eulerian path through all tickets.",
            "companies": ["Google", "Amazon", "Meta"],
        },
        {
            "title": "Min Cost to Connect All Points",
            "slug": "min-cost-to-connect-all-points",
            "difficulty": "MEDIUM",
            "pattern": "MST (Prim)",
            "leetcode_id": 1584,
            "leetcode_slug": "min-cost-to-connect-all-points",
            "hint": "You want a minimum spanning tree on the complete graph of points.",
            "key_insight": "Prim's algorithm with a min-heap of cheapest edges grows the MST one point at a time.",
            "companies": ["Amazon", "Google", "Bloomberg"],
        },
        {
            "title": "Network Delay Time",
            "slug": "network-delay-time",
            "difficulty": "MEDIUM",
            "pattern": "Dijkstra",
            "leetcode_id": 743,
            "leetcode_slug": "network-delay-time",
            "hint": "Single-source shortest path with non-negative weights.",
            "key_insight": "Dijkstra from the source yields the time to reach every node; the answer is the maximum of those.",
            "companies": ["Amazon", "Google", "Meta"],
        },
        {
            "title": "Swim in Rising Water",
            "slug": "swim-in-rising-water",
            "difficulty": "HARD",
            "pattern": "Dijkstra",
            "leetcode_id": 778,
            "leetcode_slug": "swim-in-rising-water",
            "hint": "Each path's cost is determined by its highest cell; treat that maximum as the edge weight.",
            "key_insight": "Modified Dijkstra minimizes the maximum cell elevation along the path from corner to corner.",
            "companies": ["Google", "Amazon", "Uber"],
        },
        {
            "title": "Alien Dictionary",
            "slug": "alien-dictionary",
            "difficulty": "HARD",
            "pattern": "Topological Sort",
            "leetcode_id": 269,
            "leetcode_slug": "alien-dictionary",
            "hint": "Adjacent word pairs reveal ordering constraints between letters.",
            "key_insight": "Build a directed graph from inter-word character mismatches and topologically sort it.",
            "companies": ["Google", "Amazon", "Meta", "Uber"],
        },
        {
            "title": "Cheapest Flights Within K Stops",
            "slug": "cheapest-flights-within-k-stops",
            "difficulty": "MEDIUM",
            "pattern": "Bellman-Ford",
            "leetcode_id": 787,
            "leetcode_slug": "cheapest-flights-within-k-stops",
            "hint": "Limit the number of edge relaxations to k plus one.",
            "key_insight": "Bellman-Ford bounded by k plus one relaxation rounds enforces the stop constraint while finding cheapest cost.",
            "companies": ["Amazon", "Google", "Uber"],
        },
    ],
    "dp-1d": [
        {
            "title": "Climbing Stairs",
            "slug": "climbing-stairs",
            "difficulty": "EASY",
            "pattern": "Bottom-up DP",
            "leetcode_id": 70,
            "leetcode_slug": "climbing-stairs",
            "hint": "Ways to reach a step depend on the two preceding steps.",
            "key_insight": "The recurrence dp[i] equals dp[i-1] plus dp[i-2] is the Fibonacci sequence with O(1) rolling state.",
            "companies": ["Amazon", "Adobe", "Apple"],
        },
        {
            "title": "Min Cost Climbing Stairs",
            "slug": "min-cost-climbing-stairs",
            "difficulty": "EASY",
            "pattern": "Bottom-up DP",
            "leetcode_id": 746,
            "leetcode_slug": "min-cost-climbing-stairs",
            "hint": "The cost to stand on step i is the cheaper of arriving from step i-1 or i-2.",
            "key_insight": "dp[i] equals cost[i] plus the minimum of dp[i-1] and dp[i-2]; only two rolling values are needed.",
            "companies": ["Amazon", "Apple", "Bloomberg"],
        },
        {
            "title": "House Robber",
            "slug": "house-robber",
            "difficulty": "MEDIUM",
            "pattern": "Bottom-up DP",
            "leetcode_id": 198,
            "leetcode_slug": "house-robber",
            "hint": "At each house decide to rob it (skip neighbor) or skip it.",
            "key_insight": "dp[i] equals max of dp[i-1] and dp[i-2] plus nums[i], compressible to two rolling values.",
            "companies": ["Amazon", "Google", "LinkedIn"],
        },
        {
            "title": "House Robber II",
            "slug": "house-robber-ii",
            "difficulty": "MEDIUM",
            "pattern": "Bottom-up DP",
            "leetcode_id": 213,
            "leetcode_slug": "house-robber-ii",
            "hint": "The first and last houses are now neighbors, so split into two linear cases.",
            "key_insight": "Run the linear House Robber DP twice, excluding either the first or last house, and take the maximum.",
            "companies": ["Amazon", "Google", "Microsoft"],
        },
        {
            "title": "Longest Palindromic Substring",
            "slug": "longest-palindromic-substring",
            "difficulty": "MEDIUM",
            "pattern": "Expand Around Center",
            "leetcode_id": 5,
            "leetcode_slug": "longest-palindromic-substring",
            "hint": "Every palindrome has a center; try every possible center.",
            "key_insight": "Expand from each of the 2n minus one centers to find the longest palindrome in O(n^2).",
            "companies": ["Amazon", "Meta", "Microsoft", "Bloomberg"],
        },
        {
            "title": "Palindromic Substrings",
            "slug": "palindromic-substrings",
            "difficulty": "MEDIUM",
            "pattern": "Expand Around Center",
            "leetcode_id": 647,
            "leetcode_slug": "palindromic-substrings",
            "hint": "Count by trying every possible palindrome center.",
            "key_insight": "Expanding from each center accumulates the total count of palindromic substrings in O(n^2).",
            "companies": ["Amazon", "Meta", "Uber"],
        },
        {
            "title": "Decode Ways",
            "slug": "decode-ways",
            "difficulty": "MEDIUM",
            "pattern": "Bottom-up DP",
            "leetcode_id": 91,
            "leetcode_slug": "decode-ways",
            "hint": "Decode either one or two digits at a time and check validity.",
            "key_insight": "dp[i] equals dp[i-1] when the single digit is valid plus dp[i-2] when the previous two-digit number is valid.",
            "companies": ["Amazon", "Meta", "Microsoft", "Uber"],
        },
        {
            "title": "Coin Change",
            "slug": "coin-change",
            "difficulty": "MEDIUM",
            "pattern": "Unbounded Knapsack",
            "leetcode_id": 322,
            "leetcode_slug": "coin-change",
            "hint": "For every amount, try every coin and take the best.",
            "key_insight": "dp[amount] equals one plus the min over coins c of dp[amount-c]; coins are reusable so iterate amounts outer.",
            "companies": ["Amazon", "Google", "Bloomberg", "Uber"],
        },
        {
            "title": "Maximum Product Subarray",
            "slug": "maximum-product-subarray",
            "difficulty": "MEDIUM",
            "pattern": "Bottom-up DP",
            "leetcode_id": 152,
            "leetcode_slug": "maximum-product-subarray",
            "hint": "Negatives flip the role of current min and max - track both.",
            "key_insight": "Maintain rolling min and max products since a negative number swaps which one extends best.",
            "companies": ["Amazon", "LinkedIn", "Google"],
        },
        {
            "title": "Word Break",
            "slug": "word-break",
            "difficulty": "MEDIUM",
            "pattern": "Bottom-up DP",
            "leetcode_id": 139,
            "leetcode_slug": "word-break",
            "hint": "A prefix is breakable if some shorter breakable prefix plus a dictionary word covers it.",
            "key_insight": "dp[i] is true when some j with dp[j] true has the substring s[j:i] in the dictionary.",
            "companies": ["Amazon", "Meta", "Google", "Bloomberg"],
        },
    ],
    "dp-2d": [
        {
            "title": "Unique Paths",
            "slug": "unique-paths",
            "difficulty": "MEDIUM",
            "pattern": "Grid DP",
            "leetcode_id": 62,
            "leetcode_slug": "unique-paths",
            "hint": "Each cell sums the ways to reach its top and left neighbors.",
            "key_insight": "dp[i][j] equals dp[i-1][j] plus dp[i][j-1]; a single row of state suffices to compute it.",
            "companies": ["Amazon", "Google", "Bloomberg"],
        },
        {
            "title": "Longest Common Subsequence",
            "slug": "longest-common-subsequence",
            "difficulty": "MEDIUM",
            "pattern": "2D DP",
            "leetcode_id": 1143,
            "leetcode_slug": "longest-common-subsequence",
            "hint": "Compare last characters: equal extends the LCS; otherwise drop one of the two and recurse.",
            "key_insight": "dp[i][j] equals dp[i-1][j-1] plus one on match, else the max of dp[i-1][j] and dp[i][j-1].",
            "companies": ["Amazon", "Google", "Microsoft"],
        },
        {
            "title": "Longest Increasing Subsequence",
            "slug": "longest-increasing-subsequence",
            "difficulty": "MEDIUM",
            "pattern": "Patience Sorting",
            "leetcode_id": 300,
            "leetcode_slug": "longest-increasing-subsequence",
            "hint": "Maintain the smallest possible tail for each length to allow more extensions later.",
            "key_insight": "Binary searching tails of running subsequences gives the LIS length in O(n log n).",
            "companies": ["Amazon", "Google", "Microsoft", "Meta"],
        },
        {
            "title": "Edit Distance",
            "slug": "edit-distance",
            "difficulty": "HARD",
            "pattern": "2D DP",
            "leetcode_id": 72,
            "leetcode_slug": "edit-distance",
            "hint": "At each step you insert, delete, or replace - take the cheapest.",
            "key_insight": "dp[i][j] equals dp[i-1][j-1] on match, otherwise one plus the min of insert, delete, or replace transitions.",
            "companies": ["Amazon", "Google", "Microsoft", "Uber"],
        },
        {
            "title": "Best Time to Buy and Sell Stock With Cooldown",
            "slug": "best-time-to-buy-and-sell-stock-with-cooldown",
            "difficulty": "MEDIUM",
            "pattern": "State Machine DP",
            "leetcode_id": 309,
            "leetcode_slug": "best-time-to-buy-and-sell-stock-with-cooldown",
            "hint": "Track three states per day: holding, sold yesterday (cooldown), or idle.",
            "key_insight": "A three-state machine (hold, sold, rest) transitions per day to encode the cooldown constraint in O(n).",
            "companies": ["Amazon", "Google", "Bloomberg"],
        },
        {
            "title": "Coin Change II",
            "slug": "coin-change-ii",
            "difficulty": "MEDIUM",
            "pattern": "Unbounded Knapsack",
            "leetcode_id": 518,
            "leetcode_slug": "coin-change-ii",
            "hint": "Iterate coins on the outside to count combinations rather than permutations.",
            "key_insight": "Putting coins on the outer loop ensures order does not matter, counting combinations not permutations.",
            "companies": ["Amazon", "Google", "Adobe"],
        },
        {
            "title": "Target Sum",
            "slug": "target-sum",
            "difficulty": "MEDIUM",
            "pattern": "0/1 Knapsack",
            "leetcode_id": 494,
            "leetcode_slug": "target-sum",
            "hint": "Reduce to picking a subset whose sum is (total plus target) divided by two.",
            "key_insight": "Choosing plus and minus signs equates to a subset-sum problem solvable via 0/1 knapsack DP.",
            "companies": ["Amazon", "Google", "Meta"],
        },
        {
            "title": "Interleaving String",
            "slug": "interleaving-string",
            "difficulty": "MEDIUM",
            "pattern": "2D DP",
            "leetcode_id": 97,
            "leetcode_slug": "interleaving-string",
            "hint": "At each position decide which source string contributes the next character.",
            "key_insight": "dp[i][j] is reachable if either string1[i-1] matches the next char from dp[i-1][j] or string2[j-1] from dp[i][j-1].",
            "companies": ["Amazon", "Google", "Bloomberg"],
        },
        {
            "title": "Longest Increasing Path in a Matrix",
            "slug": "longest-increasing-path-in-a-matrix",
            "difficulty": "HARD",
            "pattern": "DFS + Memoization",
            "leetcode_id": 329,
            "leetcode_slug": "longest-increasing-path-in-a-matrix",
            "hint": "Cache the longest path starting from each cell since the graph is acyclic.",
            "key_insight": "DFS with memoization treats the grid as a DAG; each cell's longest path is computed once.",
            "companies": ["Amazon", "Google", "Meta"],
        },
        {
            "title": "Distinct Subsequences",
            "slug": "distinct-subsequences",
            "difficulty": "HARD",
            "pattern": "2D DP",
            "leetcode_id": 115,
            "leetcode_slug": "distinct-subsequences",
            "hint": "Compare last chars: when they match, sum the include and skip cases.",
            "key_insight": "dp[i][j] equals dp[i-1][j-1] plus dp[i-1][j] when chars match, else dp[i-1][j] alone.",
            "companies": ["Amazon", "Bloomberg", "Google"],
        },
        {
            "title": "Burst Balloons",
            "slug": "burst-balloons",
            "difficulty": "HARD",
            "pattern": "Interval DP",
            "leetcode_id": 312,
            "leetcode_slug": "burst-balloons",
            "hint": "Instead of which balloon to pop first, decide which one to pop last in each interval.",
            "key_insight": "Interval DP indexed by the last balloon popped in each range avoids the dependency tangle of pop order.",
            "companies": ["Amazon", "Google", "Meta"],
        },
    ],
    "greedy": [
        {
            "title": "Maximum Subarray",
            "slug": "maximum-subarray",
            "difficulty": "MEDIUM",
            "pattern": "Kadane",
            "leetcode_id": 53,
            "leetcode_slug": "maximum-subarray",
            "hint": "Reset the running sum whenever it would hurt to extend the current subarray.",
            "key_insight": "Kadane's algorithm keeps a running sum, resetting on negatives, to find max subarray in O(n).",
            "companies": ["Amazon", "LinkedIn", "Apple", "Bloomberg"],
        },
        {
            "title": "Jump Game",
            "slug": "jump-game",
            "difficulty": "MEDIUM",
            "pattern": "Greedy",
            "leetcode_id": 55,
            "leetcode_slug": "jump-game",
            "hint": "Track the furthest index you can currently reach as you scan left to right.",
            "key_insight": "Sweep and update the max reachable index; if it ever lags the current index, the end is unreachable.",
            "companies": ["Amazon", "Meta", "Apple", "Bloomberg"],
        },
        {
            "title": "Jump Game II",
            "slug": "jump-game-ii",
            "difficulty": "MEDIUM",
            "pattern": "Greedy",
            "leetcode_id": 45,
            "leetcode_slug": "jump-game-ii",
            "hint": "Within the reach of the current jump, plan where the next jump should land.",
            "key_insight": "BFS-style layers: extend the current reach and increment jumps when you exhaust it.",
            "companies": ["Amazon", "Meta", "Bloomberg"],
        },
        {
            "title": "Gas Station",
            "slug": "gas-station",
            "difficulty": "MEDIUM",
            "pattern": "Greedy",
            "leetcode_id": 134,
            "leetcode_slug": "gas-station",
            "hint": "If you fail at station i, no station between the previous start and i can succeed either.",
            "key_insight": "Reset the candidate start after any deficit; total gas at least total cost guarantees a valid start exists.",
            "companies": ["Amazon", "Google", "Bloomberg"],
        },
        {
            "title": "Hand of Straights",
            "slug": "hand-of-straights",
            "difficulty": "MEDIUM",
            "pattern": "Greedy",
            "leetcode_id": 846,
            "leetcode_slug": "hand-of-straights",
            "hint": "Always start the next group at the smallest remaining card.",
            "key_insight": "Process the smallest available card and consume the next w consecutive cards greedily; failure means impossible.",
            "companies": ["Amazon", "Google", "Microsoft"],
        },
        {
            "title": "Merge Triplets to Form Target Triplet",
            "slug": "merge-triplets-to-form-target-triplet",
            "difficulty": "MEDIUM",
            "pattern": "Greedy",
            "leetcode_id": 1899,
            "leetcode_slug": "merge-triplets-to-form-target-triplet",
            "hint": "Only triplets that never exceed the target on any component can be merged in.",
            "key_insight": "Keep triplets bounded by the target component-wise and check if their element-wise max equals the target.",
            "companies": ["Amazon", "Google", "Adobe"],
        },
        {
            "title": "Partition Labels",
            "slug": "partition-labels",
            "difficulty": "MEDIUM",
            "pattern": "Greedy",
            "leetcode_id": 763,
            "leetcode_slug": "partition-labels",
            "hint": "A partition must extend at least as far as the last occurrence of every character it contains.",
            "key_insight": "Sweep, extending the current partition's end to the max last-index of seen chars and closing when reached.",
            "companies": ["Amazon", "Meta", "Google"],
        },
        {
            "title": "Valid Parenthesis String",
            "slug": "valid-parenthesis-string",
            "difficulty": "MEDIUM",
            "pattern": "Greedy",
            "leetcode_id": 678,
            "leetcode_slug": "valid-parenthesis-string",
            "hint": "Track the min and max possible number of unmatched opens at each point.",
            "key_insight": "Maintain a range of possible open-count values; the string is valid iff zero stays in that range throughout.",
            "companies": ["Amazon", "Google", "Bloomberg"],
        },
    ],
    "intervals": [
        {
            "title": "Insert Interval",
            "slug": "insert-interval",
            "difficulty": "MEDIUM",
            "pattern": "Intervals",
            "leetcode_id": 57,
            "leetcode_slug": "insert-interval",
            "hint": "Walk the sorted intervals and merge any that overlap the new one.",
            "key_insight": "Append non-overlapping prefixes, merge the overlapping run with the new interval, then append the suffix.",
            "companies": ["Amazon", "Google", "LinkedIn"],
        },
        {
            "title": "Merge Intervals",
            "slug": "merge-intervals",
            "difficulty": "MEDIUM",
            "pattern": "Intervals",
            "leetcode_id": 56,
            "leetcode_slug": "merge-intervals",
            "hint": "Sort by start, then extend the last result whenever it overlaps the next.",
            "key_insight": "Sort by start; merge into the last result interval whenever its end is at least the next start.",
            "companies": ["Amazon", "Meta", "Bloomberg", "Google"],
        },
        {
            "title": "Non Overlapping Intervals",
            "slug": "non-overlapping-intervals",
            "difficulty": "MEDIUM",
            "pattern": "Greedy",
            "leetcode_id": 435,
            "leetcode_slug": "non-overlapping-intervals",
            "hint": "Keep intervals that finish earliest so future ones can fit.",
            "key_insight": "Sort by end time and greedily keep intervals that do not overlap the last kept one.",
            "companies": ["Amazon", "Google", "Bloomberg"],
        },
        {
            "title": "Meeting Rooms",
            "slug": "meeting-rooms",
            "difficulty": "EASY",
            "pattern": "Intervals",
            "leetcode_id": 252,
            "leetcode_slug": "meeting-rooms",
            "hint": "Sort meetings by start time and check adjacent pairs for overlap.",
            "key_insight": "After sorting by start, any adjacent pair overlapping means the meetings cannot all be attended.",
            "companies": ["Amazon", "Meta", "Google"],
        },
        {
            "title": "Meeting Rooms II",
            "slug": "meeting-rooms-ii",
            "difficulty": "MEDIUM",
            "pattern": "Heap",
            "leetcode_id": 253,
            "leetcode_slug": "meeting-rooms-ii",
            "hint": "Track the earliest ending room and reuse it when its meeting ends in time.",
            "key_insight": "A min-heap of meeting end times tells you when a room frees up; its size is the rooms needed.",
            "companies": ["Amazon", "Meta", "Google", "Uber"],
        },
        {
            "title": "Minimum Interval to Include Each Query",
            "slug": "minimum-interval-to-include-each-query",
            "difficulty": "HARD",
            "pattern": "Heap",
            "leetcode_id": 1851,
            "leetcode_slug": "minimum-interval-to-include-each-query",
            "hint": "Process queries in order, adding intervals as their start passes and removing those whose end is gone.",
            "key_insight": "Offline sort queries and intervals, maintaining a min-heap of (length, end) for currently active intervals.",
            "companies": ["Google", "Amazon", "Bloomberg"],
        },
    ],
    "math-geometry": [
        {
            "title": "Rotate Image",
            "slug": "rotate-image",
            "difficulty": "MEDIUM",
            "pattern": "Matrix",
            "leetcode_id": 48,
            "leetcode_slug": "rotate-image",
            "hint": "Transpose then reverse rows, or rotate four cells at a time.",
            "key_insight": "Transpose plus row reversal yields a 90-degree clockwise rotation in O(n^2) and O(1) extra space.",
            "companies": ["Amazon", "Meta", "Apple", "Microsoft"],
        },
        {
            "title": "Spiral Matrix",
            "slug": "spiral-matrix",
            "difficulty": "MEDIUM",
            "pattern": "Matrix",
            "leetcode_id": 54,
            "leetcode_slug": "spiral-matrix",
            "hint": "Shrink the boundary inward after each side is traversed.",
            "key_insight": "Track four shrinking bounds and traverse each side once per layer until they cross.",
            "companies": ["Amazon", "Meta", "Microsoft", "Uber"],
        },
        {
            "title": "Set Matrix Zeroes",
            "slug": "set-matrix-zeroes",
            "difficulty": "MEDIUM",
            "pattern": "Matrix",
            "leetcode_id": 73,
            "leetcode_slug": "set-matrix-zeroes",
            "hint": "Use the matrix's own first row and column as flags to avoid extra storage.",
            "key_insight": "Use the first row and column as in-place markers, handling them specially to achieve O(1) extra space.",
            "companies": ["Amazon", "Microsoft", "Adobe"],
        },
        {
            "title": "Happy Number",
            "slug": "happy-number",
            "difficulty": "EASY",
            "pattern": "Floyd's Cycle",
            "leetcode_id": 202,
            "leetcode_slug": "happy-number",
            "hint": "If you never reach 1, you must be in a cycle.",
            "key_insight": "Cycle detection on the digit-square map distinguishes happy numbers from looping ones in O(1) space.",
            "companies": ["Amazon", "Apple", "Google"],
        },
        {
            "title": "Plus One",
            "slug": "plus-one",
            "difficulty": "EASY",
            "pattern": "Math",
            "leetcode_id": 66,
            "leetcode_slug": "plus-one",
            "hint": "Simulate grade-school addition starting from the least significant digit.",
            "key_insight": "Carry propagates only through trailing nines, occasionally needing a new leading digit.",
            "companies": ["Amazon", "Google", "Apple"],
        },
        {
            "title": "Pow(x, n)",
            "slug": "powx-n",
            "difficulty": "MEDIUM",
            "pattern": "Fast Exponentiation",
            "leetcode_id": 50,
            "leetcode_slug": "powx-n",
            "hint": "Halve the exponent and square the base at each step.",
            "key_insight": "Exponentiation by squaring computes x to the n in O(log n) by halving n recursively.",
            "companies": ["Amazon", "Meta", "Bloomberg", "Apple"],
        },
        {
            "title": "Multiply Strings",
            "slug": "multiply-strings",
            "difficulty": "MEDIUM",
            "pattern": "Math",
            "leetcode_id": 43,
            "leetcode_slug": "multiply-strings",
            "hint": "Multiplying digit i of one by digit j of the other contributes to position i plus j.",
            "key_insight": "Use an array of length m plus n where digit products land at index i plus j and propagate carries.",
            "companies": ["Amazon", "Meta", "Uber"],
        },
        {
            "title": "Detect Squares",
            "slug": "detect-squares",
            "difficulty": "MEDIUM",
            "pattern": "Hashing",
            "leetcode_id": 2013,
            "leetcode_slug": "detect-squares",
            "hint": "Pick a diagonal partner and count the other two corners required.",
            "key_insight": "For each point sharing the diagonal, count occurrences of the two completing corners using a hash map.",
            "companies": ["Google", "Amazon", "Bloomberg"],
        },
    ],
    "bit-manipulation": [
        {
            "title": "Single Number",
            "slug": "single-number",
            "difficulty": "EASY",
            "pattern": "XOR",
            "leetcode_id": 136,
            "leetcode_slug": "single-number",
            "hint": "Pairs cancel each other under one specific operation.",
            "key_insight": "XOR of all elements cancels pairs and leaves the unique element in O(n) time, O(1) space.",
            "companies": ["Amazon", "Google", "Bloomberg"],
        },
        {
            "title": "Number of 1 Bits",
            "slug": "number-of-1-bits",
            "difficulty": "EASY",
            "pattern": "Bit Manipulation",
            "leetcode_id": 191,
            "leetcode_slug": "number-of-1-bits",
            "hint": "There is an operation that clears the lowest set bit each step.",
            "key_insight": "Repeatedly applying n AND (n minus 1) clears the lowest set bit; the count of iterations is the answer.",
            "companies": ["Amazon", "Apple", "Microsoft"],
        },
        {
            "title": "Counting Bits",
            "slug": "counting-bits",
            "difficulty": "EASY",
            "pattern": "DP",
            "leetcode_id": 338,
            "leetcode_slug": "counting-bits",
            "hint": "Use the bit count of a smaller number to derive that of a larger one.",
            "key_insight": "dp[i] equals dp[i >> 1] plus (i AND 1) computes set-bit counts for 0..n in O(n).",
            "companies": ["Amazon", "Apple", "Google"],
        },
        {
            "title": "Reverse Bits",
            "slug": "reverse-bits",
            "difficulty": "EASY",
            "pattern": "Bit Manipulation",
            "leetcode_id": 190,
            "leetcode_slug": "reverse-bits",
            "hint": "Push the input bits out the bottom and shift the output bits in the top.",
            "key_insight": "Shift the result left while shifting the input right; OR the lowest input bit into the result each iteration.",
            "companies": ["Amazon", "Apple", "Bloomberg"],
        },
        {
            "title": "Missing Number",
            "slug": "missing-number",
            "difficulty": "EASY",
            "pattern": "XOR",
            "leetcode_id": 268,
            "leetcode_slug": "missing-number",
            "hint": "XOR all numbers together with all indices.",
            "key_insight": "XOR of values and 0..n cancels matched pairs and leaves the missing number.",
            "companies": ["Amazon", "Microsoft", "Bloomberg"],
        },
        {
            "title": "Sum of Two Integers",
            "slug": "sum-of-two-integers",
            "difficulty": "MEDIUM",
            "pattern": "Bit Manipulation",
            "leetcode_id": 371,
            "leetcode_slug": "sum-of-two-integers",
            "hint": "XOR adds without carry; AND tells you where the carry goes.",
            "key_insight": "Iteratively sum XOR (no-carry add) and shift-left AND (carry) until the carry is zero.",
            "companies": ["Amazon", "Microsoft", "Apple"],
        },
        {
            "title": "Reverse Integer",
            "slug": "reverse-integer",
            "difficulty": "MEDIUM",
            "pattern": "Math",
            "leetcode_id": 7,
            "leetcode_slug": "reverse-integer",
            "hint": "Peel digits with mod ten and push them on with multiply by ten - watch overflow.",
            "key_insight": "Check before each multiply that the running result will not exceed 32-bit signed bounds.",
            "companies": ["Amazon", "Apple", "Bloomberg"],
        },
    ],
}
