"""Static topic definitions for the AlgoTrail.ai roadmap.

The slugs here are the source of truth; questions_data.py keys must match.
"""

TOPICS: list[dict] = [
    {
        "slug": "arrays-hashing",
        "title": "Arrays & Hashing",
        "icon": "📦",
        "order": 1,
        "estimated_days": 5,
        "description": "The foundation of every DSA interview. Master hashing and array traversal — most other patterns build on these.",
        "patterns": ["Hashing", "Prefix Sum", "Counter"],
        "color": "#3B82F6",
    },
    {
        "slug": "two-pointers",
        "title": "Two Pointers",
        "icon": "↔️",
        "order": 2,
        "estimated_days": 3,
        "description": "Walk two indices through a sequence to avoid nested loops. Critical for sorted arrays and palindromes.",
        "patterns": ["Opposite Ends", "Same Direction", "Fast & Slow"],
        "color": "#8B5CF6",
    },
    {
        "slug": "sliding-window",
        "title": "Sliding Window",
        "icon": "🪟",
        "order": 3,
        "estimated_days": 3,
        "description": "Maintain a moving range over an array or string. Fixed and variable windows unlock substring and subarray problems.",
        "patterns": ["Fixed Window", "Variable Window"],
        "color": "#EC4899",
    },
    {
        "slug": "stack",
        "title": "Stack",
        "icon": "📚",
        "order": 4,
        "estimated_days": 4,
        "description": "LIFO data structure. Monotonic stacks dominate 'next greater element' style problems and parsing.",
        "patterns": ["Monotonic Stack", "Bracket Matching"],
        "color": "#F59E0B",
    },
    {
        "slug": "binary-search",
        "title": "Binary Search",
        "icon": "🔎",
        "order": 5,
        "estimated_days": 4,
        "description": "Halve the search space each step. Recognize when answers are monotonic and binary search becomes obvious.",
        "patterns": ["Classic Binary Search", "Binary Search on Answer"],
        "color": "#06B6D4",
    },
    {
        "slug": "linked-list",
        "title": "Linked List",
        "icon": "🔗",
        "order": 6,
        "estimated_days": 5,
        "description": "Pointers and cycles. Master the dummy head trick and Floyd's tortoise-and-hare.",
        "patterns": ["Dummy Head", "Floyd's Cycle", "Reversal"],
        "color": "#10B981",
    },
    {
        "slug": "trees",
        "title": "Trees",
        "icon": "🌳",
        "order": 7,
        "estimated_days": 7,
        "description": "Recursion on hierarchical data. DFS vs BFS, in-/pre-/post-order — pick the right traversal for each problem.",
        "patterns": ["DFS", "BFS", "Recursion"],
        "color": "#22C55E",
    },
    {
        "slug": "heap",
        "title": "Heap / Priority Queue",
        "icon": "⛰️",
        "order": 8,
        "estimated_days": 4,
        "description": "Always-sorted-on-demand. Top-K and merge problems collapse to a one-liner with a heap.",
        "patterns": ["Top-K", "Merge K Lists", "Median Stream"],
        "color": "#A855F7",
    },
    {
        "slug": "backtracking",
        "title": "Backtracking",
        "icon": "🧭",
        "order": 9,
        "estimated_days": 5,
        "description": "Recursive choose-explore-unchoose. The pattern behind permutations, combinations, and constraint problems.",
        "patterns": ["Subsets", "Permutations", "N-Queens"],
        "color": "#F43F5E",
    },
    {
        "slug": "graphs",
        "title": "Graphs",
        "icon": "🕸️",
        "order": 10,
        "estimated_days": 6,
        "description": "Nodes and edges. DFS/BFS, connected components, and topological sort cover most graph interview questions.",
        "patterns": ["DFS", "BFS", "Union-Find", "Topological Sort"],
        "color": "#0EA5E9",
    },
    {
        "slug": "advanced-graphs",
        "title": "Advanced Graphs",
        "icon": "🗺️",
        "order": 11,
        "estimated_days": 5,
        "description": "Shortest paths, MST, and edge-cases. Dijkstra and Bellman-Ford show up surprisingly often.",
        "patterns": ["Dijkstra", "Bellman-Ford", "Kruskal", "Prim"],
        "color": "#6366F1",
    },
    {
        "slug": "dp-1d",
        "title": "1D Dynamic Programming",
        "icon": "📈",
        "order": 12,
        "estimated_days": 6,
        "description": "Decisions over a single dimension. Find the recurrence; the code follows.",
        "patterns": ["Top-down DP", "Bottom-up DP", "Rolling Array"],
        "color": "#EF4444",
    },
    {
        "slug": "dp-2d",
        "title": "2D Dynamic Programming",
        "icon": "🧩",
        "order": 13,
        "estimated_days": 7,
        "description": "Two-dimensional state. Grid DP, longest common subsequence, edit distance.",
        "patterns": ["Grid DP", "Interval DP", "LCS-style"],
        "color": "#D946EF",
    },
    {
        "slug": "greedy",
        "title": "Greedy",
        "icon": "🪙",
        "order": 14,
        "estimated_days": 4,
        "description": "Make the locally optimal choice. The hard part is proving it's globally optimal — pattern recognition matters.",
        "patterns": ["Sort + Pick", "Exchange Argument"],
        "color": "#FACC15",
    },
    {
        "slug": "intervals",
        "title": "Intervals",
        "icon": "📅",
        "order": 15,
        "estimated_days": 3,
        "description": "Ranges with start and end. Sort and sweep your way through merge, overlap, and scheduling problems.",
        "patterns": ["Sort by Start", "Sweep Line"],
        "color": "#FB923C",
    },
    {
        "slug": "math-geometry",
        "title": "Math & Geometry",
        "icon": "📐",
        "order": 16,
        "estimated_days": 4,
        "description": "Number theory and coordinate geometry. Often a thin layer of math wrapped around a familiar pattern.",
        "patterns": ["Math Identities", "Matrix Manipulation"],
        "color": "#14B8A6",
    },
    {
        "slug": "bit-manipulation",
        "title": "Bit Manipulation",
        "icon": "⚡",
        "order": 17,
        "estimated_days": 3,
        "description": "Reason about individual bits. XOR is your friend. Most problems collapse to a one-line trick.",
        "patterns": ["XOR Tricks", "Bit Counting"],
        "color": "#64748B",
    },
]
